INSERT INTO public.skills (id, name, unit, prerequisites) VALUES
('SK_AVERAGE_RATE_CHANGE', 'Average Rate of Change', 'Unit 8', '{}'),
('SK_DEFINITE_INTEGRAL_EVAL', 'Evaluating Definite Integrals', 'Unit 8', '{}'),
('SK_FTC_ACCUMULATION', 'FTC Accumulation Functions', 'Unit 8', '{}'),
('SK_INTERPRET_GRAPH', 'Interpreting Graphs', 'Unit 8', '{}'),
('SK_MAX_POSITION_FROM_VELOCITY', 'Finding Max Position from Velocity', 'Unit 8', '{}'),
('SK_MOTION_DISPLACEMENT_INTEGRAL', 'Motion Displacement Integral', 'Unit 8', '{}'),
('SK_MOTION_DISTANCE_FROM_VELOCITY_GRAPH', 'Distance from Velocity Graph', 'Unit 8', '{}'),
('SK_MOTION_POSITION_FROM_VELOCITY', 'Position from Velocity', 'Unit 8', '{}'),
('SK_ACCUM_FUNC_PROPERTIES', 'Properties of Accumulation Functions', 'Unit 8', '{}'),
('SK_AREA_BETWEEN_CURVES_DX', 'Area Between Curves (dx)', 'Unit 8', '{}'),
('SK_AVG_ROC', 'Average Rate of Change', 'Unit 8', '{}'),
('SK_DEF_INT_EVAL', 'Evaluating Definite Integrals', 'Unit 8', '{}'),
('SK_FIND_INTERSECTIONS', 'Finding Intersections', 'Unit 8', '{}'),
('SK_INTERPRET_DEF_INT', 'Interpreting Definite Integrals', 'Unit 8', '{}'),
('SK_PIECEWISE_INTEGRAL', 'Piecewise Integration', 'Unit 8', '{}'),
('SK_PIECEWISE_SETUP', 'Piecewise Setup', 'Unit 8', '{}'),
('SK_SOLVE_EQUATION', 'Solving Equations', 'Unit 8', '{}'),
('SK_CS_SQ_RECT_AREA', 'Cross Section Area (Square/Rect)', 'Unit 8', '{}'),
('SK_CS_TRI_SEMI_AREA', 'Cross Section Area (Tri/Semi)', 'Unit 8', '{}'),
('SK_FIND_BOUNDS_INTERSECTION', 'Finding Integration Bounds', 'Unit 8', '{}'),
('SK_INTEGRATE_LOG', 'Integration Involving Logarithms', 'Unit 8', '{}'),
('SK_VOLUME_INTEGRAL', 'Volume Integral Setup', 'Unit 8', '{}'),
('SK_AXIS_SHIFT', 'Integration with Axis Shift', 'Unit 8', '{}'),
('SK_FUNCTION_INVERSION', 'Inverting Functions for Integration', 'Unit 8', '{}'),
('SK_VOL_DISC_EVALUATE', 'Volume by Disc Method (Evaluate)', 'Unit 8', '{}'),
('SK_AXIS_SHIFT_WASHER', 'Integration with Axis Shift (Washer)', 'Unit 8', '{}'),
('SK_INTEGRAL_EVAL', 'Integral Evaluation', 'Unit 8', '{}'),
('SK_ORIENTATION_CHOICE', 'Orientation Choice (dx vs dy)', 'Unit 8', '{}'),
('SK_OUTER_INNER', 'Washer Outer/Inner Radius', 'Unit 8', '{}'),
('SK_ARCLENGTH_FUNC', 'Arc Length of Function y=f(x)', 'Unit 8', '{}'),
('SK_ARCLENGTH_PARAM', 'Arc Length of Parametric Curve', 'Unit 8', '{}'),
('SK_AREA_FROM_GRAPH', 'Area from Graph Interpretation', 'Unit 8', '{}'),
('SK_DISTANCE_TRAVELED', 'Total Distance Traveled', 'Unit 8', '{}'),
('SK_INT_TECH', 'Integration Techniques (General)', 'Unit 8', '{}'),
('SK_PARAM_DERIV', 'Parametric Derivatives', 'Unit 8', '{}'),
('SK_SIGN_ANALYSIS', 'Sign Analysis for Distance', 'Unit 8', '{}'),
('SK_ACCUMULATION', 'Accumulation Functions', 'Unit 8', '{}'),
('SK_ARC_LENGTH', 'Arc Length Formula', 'Unit 8', '{}'),
('SK_AREA_BETWEEN_DX', 'Area Between Curves (dx)', 'Unit 8', '{}'),
('SK_AREA_BETWEEN_DY', 'Area Between Curves (dy)', 'Unit 8', '{}'),
('SK_FORMULA_RECALL', 'Formula Recall', 'Unit 8', '{}'),
('SK_FTC', 'Fundamental Theorem of Calculus', 'Unit 8', '{}'),
('SK_GEOMETRY_AREA', 'Geometry Area Formulas', 'Unit 8', '{}'),
('SK_INTERPRET_UNITS', 'Interpreting Units', 'Unit 8', '{}'),
('SK_INTERSECTIONS', 'Finding Intersections', 'Unit 8', '{}'),
('SK_MOTION_V_FROM_A', 'Motion: Velocity from Acceleration', 'Unit 8', '{}'),
('SK_SETUP_INTEGRAL', 'Setting Up Integrals', 'Unit 8', '{}'),
('SK_TOTAL_AREA', 'Total Area vs Net Area', 'Unit 8', '{}'),
('SK_VOLUME_CROSS_SECTIONS', 'Volume by Cross Sections', 'Unit 8', '{}'),
('SK_VOLUME_DISC', 'Volume by Disc Method', 'Unit 8', '{}'),
('SK_VOLUME_WASHER', 'Volume by Washer Method', 'Unit 8', '{}'),
('SK_AREA_DY', 'Area Between Curves (dy)', 'Unit 8', '{}'),
('SK_SOLVE_INTERSECTIONS', 'Solving Intersections', 'Unit 8', '{}'),
('SK_SETUP_DY', 'Setup Integral (dy)', 'Unit 8', '{}'),
('SK_SPLIT_INTEGRAL', 'Splitting Integrals', 'Unit 8', '{}'),
('SK_AREA_DX', 'Area Between Curves (dx)', 'Unit 8', '{}'),
('SK_FIND_ZEROS_SIGN', 'Finding Zeros and Sign', 'Unit 8', '{}'),
('SK_ABS_AREA', 'Absolute Area', 'Unit 8', '{}'),
('SK_SOLVE_TRIG_INTERSECTIONS', 'Solving Trig Intersections', 'Unit 8', '{}'),
('SK_CONVERT_DX_TO_DY', 'Convert dx to dy', 'Unit 8', '{}'),
('SK_VOL_DISC_SETUP', 'Volume Disc Setup', 'Unit 8', '{}'),
('SK_TRIG_IDENTITIES', 'Trigonometric Identities', 'Unit 8', '{}')







ON CONFLICT (id) DO NOTHING;
