-- Attributes:
--   id: text
--   name: text
--   unit: text
--   metadata: jsonb

INSERT INTO public.skills (id, name, unit, prerequisites)
VALUES

('SK_SERIES_DEF_CONVERGENCE', 'Definition of Series Convergence', 'Unit 10', '{}'),
('SK_PARTIAL_SUMS_CONCEPT', 'Concept of Partial Sums', 'Unit 10', '{}'),
('SK_PARTIAL_SUMS_COMPUTE', 'Computing Partial Sums', 'Unit 10', '{}'),
('SK_TELESCOPING_SUMS', 'Telescoping Sums', 'Unit 10', '{}'),
('SK_SEQUENCE_VS_SERIES', 'Sequence vs Series', 'Unit 10', '{}'),
('SK_PARTIAL_SUMS_LIMIT', 'Limit of Partial Sums', 'Unit 10', '{}'),
('SK_SERIES_VALUE_FROM_PARTIAL_SUMS', 'Series Value from Partial Sums', 'Unit 10', '{}'),
('SK_MONOTONE_BOUNDED_PARTIAL_SUMS', 'Monotone Bounded Partial Sums', 'Unit 10', '{}'),
('SK_GEOM_CONVERGENCE_CONDITION', 'Geometric Series Convergence Condition', 'Unit 10', '{}'),
('SK_GEOM_IDENTIFY_RATIO', 'Identifying Geometric Ratio', 'Unit 10', '{}'),
('SK_GEOM_SUM_INFINITE', 'Infinite Geometric Sum', 'Unit 10', '{}'),
('SK_GEOM_IDENTIFY_A_AND_R', 'Identifying a and r in Geometric Series', 'Unit 10', '{}'),
('SK_REPEAT_DECIMAL_GEOM_MODEL', 'Repeating Decimal as Geometric Series', 'Unit 10', '{}'),
('SK_GEOM_SOLVE_FOR_RATIO', 'Solving for Geometric Ratio', 'Unit 10', '{}'),
('SK_GEOM_SIGMA_NOTATION', 'Geometric Series in Sigma Notation', 'Unit 10', '{}'),
('SK_GEOM_IDENTIFY_FIRST_TERM', 'Identifying First Term in Geometric Series', 'Unit 10', '{}'),
('SK_NTH_TERM_TEST', 'Nth-Term Test for Divergence', 'Unit 10', '{}'),
('SK_LIMITS', 'Evaluating Limits', 'Unit 10', '{}'),
('SK_ALGEBRA_SIMPLIFY', 'Algebraic Simplification', 'Unit 10', '{}'),
('SK_INTEGRAL_TEST', 'Integral Test for Convergence', 'Unit 10', '{}'),
('SK_IMPROPER_INTEGRAL', 'Evaluating Improper Integrals', 'Unit 10', '{}'),
('SK_SUBSTITUTION', 'Integration by Substitution', 'Unit 10', '{}'),
('SK_TEST_CONDITIONS', 'Verifying Test Conditions', 'Unit 10', '{}'),
('SK_P_SERIES_TEST', 'p-Series Test', 'Unit 10', '{}'),
('SK_HARMONIC_SERIES', 'Harmonic Series', 'Unit 10', '{}'),
('SK_INDEX_SHIFT', 'Index Shifting', 'Unit 10', '{}'),
('SK_EXPONENT_RULES', 'Exponent Rules', 'Unit 10', '{}'),
('SK_LOG_PROPERTIES', 'Logarithm Properties', 'Unit 10', '{}'),
('SK_DIRECT_COMPARISON', 'Direct Comparison Test', 'Unit 10', '{}'),
('SK_ASYMPTOTIC_BEHAVIOR', 'Asymptotic Behavior', 'Unit 10', '{}'),
('SK_LIMIT_COMPARISON', 'Limit Comparison Test', 'Unit 10', '{}'),
('SK_SERIES_ALTERNATING_TEST', 'Alternating Series Test', 'Unit 10', '{}'),
('SK_SERIES_TERMS_TO_ZERO', 'Terms to Zero Condition', 'Unit 10', '{}'),
('SK_INEQUALITIES_MONOTONICITY', 'Inequalities and Monotonicity', 'Unit 10', '{}'),
('SK_LOG_EXP_MANIPULATION', 'Logarithmic and Exponential Manipulation', 'Unit 10', '{}'),
('SK_SEQUENCE_MONOTONICITY', 'Sequence Monotonicity', 'Unit 10', '{}'),
('SK_LIMIT_EVALUATION', 'Limit Evaluation', 'Unit 10', '{}'),
('SK_SERIES_RATIO_TEST', 'Ratio Test', 'Unit 10', '{}'),
('SK_FACTORIAL_MANIPULATION', 'Factorial Manipulation', 'Unit 10', '{}'),
('SK_EXPONENTIAL_GROWTH_COMPARISON', 'Exponential Growth Comparison', 'Unit 10', '{}'),
('SK_RATIO_TEST_INCONCLUSIVE', 'Ratio Test Inconclusive Case', 'Unit 10', '{}'),
('SK_SERIES_ABS_COND_CLASSIFY', 'Absolute vs Conditional Convergence', 'Unit 10', '{}'),
('SK_ALT_SERIES_TEST', 'Alternating Series Test (Short)', 'Unit 10', '{}'),
('SK_ALT_ERROR_BOUND', 'Alternating Series Error Bound', 'Unit 10', '{}'),
('SK_INEQUALITY_SOLVE', 'Solving Inequalities', 'Unit 10', '{}'),
('SK_REMAINDER_INTERPRET', 'Interpreting Remainders', 'Unit 10', '{}'),
('SK_REMAINDER_ESTIMATE', 'Estimating Remainders', 'Unit 10', '{}'),
('SK_P_SERIES', 'p-Series (Short)', 'Unit 10', '{}'),
('SK_TAYLOR_POLY_BUILD', 'Building Taylor Polynomials', 'Unit 10', '{}'),
('SK_DERIV_EVAL', 'Evaluating Derivatives', 'Unit 10', '{}'),
('SK_TAYLOR_APPROX_VALUE', 'Approximating Values with Taylor Polynomials', 'Unit 10', '{}'),
('SK_MACLAURIN_COEFF', 'Maclaurin Series Coefficients', 'Unit 10', '{}'),
('SK_SERIES_ALGEBRA', 'Algebra with Series', 'Unit 10', '{}'),
('SK_FUNCTION_COMPOSITION_SERIES', 'Series Function Composition', 'Unit 10', '{}'),
('SK_LAGRANGE_ERROR_BOUND', 'Lagrange Error Bound', 'Unit 10', '{}'),
('SK_BOUND_MAX_DERIV', 'Bounding Maximum Derivative', 'Unit 10', '{}'),
('SK_REMAINDER_SETUP', 'Setting up Remainder Formula', 'Unit 10', '{}'),
('SK_RADIUS_OF_CONVERGENCE', 'Radius of Convergence', 'Unit 10', '{}'),
('SK_ENDPOINT_TESTING', 'Testing Endpoints', 'Unit 10', '{}'),
('SK_HARMONIC_P_SERIES', 'Harmonic and p-Series', 'Unit 10', '{}'),
('SK_POWER_SERIES_CENTER', 'Center of Power Series', 'Unit 10', '{}'),
('SK_INTERVAL_NOTATION', 'Interval Notation', 'Unit 10', '{}'),
('SK_INTERVAL_OF_CONVERGENCE', 'Interval of Convergence', 'Unit 10', '{}'),
('SK_MACLAURIN_SERIES', 'Maclaurin Series', 'Unit 10', '{}'),
('SK_TAYLOR_POLYNOMIAL', 'Taylor Polynomial', 'Unit 10', '{}'),
('SK_DERIVATIVE_AT_POINT', 'Derivative at a Point', 'Unit 10', '{}'),
('SK_SERIES_SUBSTITUTION', 'Series Substitution', 'Unit 10', '{}'),
('SK_COEFFICIENT_EXTRACTION', 'Coefficient Extraction', 'Unit 10', '{}'),
('SK_SERIES_COMPOSITION', 'Series Composition', 'Unit 10', '{}'),
('SK_TAYLOR_APPROXIMATION', 'Taylor Approximation', 'Unit 10', '{}'),
('SK_REP_FUNCTION_AS_POWER_SERIES', 'Representing Functions as Power Series', 'Unit 10', '{}'),
('SK_INDEX_SHIFT_REWRITE', 'Rewriting with Index Shift', 'Unit 10', '{}'),
('SK_GEOMETRIC_SERIES_SUBSTITUTION', 'Geometric Series Substitution', 'Unit 10', '{}'),
('SK_POWER_SERIES_DIFF_INT', 'Differentiation and Integration of Power Series', 'Unit 10', '{}'),
('SK_ALGEBRA_REWRITE_FOR_SERIES', 'Algebraic Rewrite for Series', 'Unit 10', '{}'),
('SK_SERIES_CONVERGENCE_CLASSIFY', 'Classifying Series Convergence', 'Unit 10', '{}'),
('SK_GEOMETRIC_SERIES', 'Geometric Series', 'Unit 10', '{}'),
('SK_LOG_SUBSTITUTION', 'Logarithmic Substitution', 'Unit 10', '{}'),
('SK_ABS_COND_CONVERGENCE', 'Absolute vs Conditional Convergence', 'Unit 10', '{}'),
('SK_ALTERNATING_ERROR_BOUND', 'Alternating Series Error Bound', 'Unit 10', '{}'),
('SK_MACLAURIN_KNOWN_SERIES', 'Known Maclaurin Series', 'Unit 10', '{}'),
('SK_RADIUS_CONVERGENCE', 'Radius of Convergence', 'Unit 10', '{}'),
('SK_INTERVAL_CONVERGENCE', 'Interval of Convergence', 'Unit 10', '{}'),
('SK_POWER_SERIES_FROM_GEOMETRIC', 'Power Series from Geometric', 'Unit 10', '{}'),
('SK_POWER_SERIES_OPERATIONS', 'Power Series Operations', 'Unit 10', '{}'),
('SK_DERIVATIVE_OF_POWER_SERIES', 'Derivative of Power Series', 'Unit 10', '{}'),
('SK_COMPARISON_TEST', 'Comparison Test', 'Unit 10', '{}'),
('SK_BOUNDED_TERMS', 'Bounded Terms', 'Unit 10', '{}'),
('SK_LIMITS_WITH_E', 'Limits involving e', 'Unit 10', '{}'),
('SK_LINEARIZATION', 'Linearization', 'Unit 10', '{}'),
('SK_TANGENT_LINE', 'Tangent Line Approximations', 'Unit 10', '{}'),
('SK_DIFFERENTIALS', 'Differentials', 'Unit 10', '{}'),
('SK_NEWTON_METHOD', 'Newton''s Method', 'Unit 10', '{}'),
('SK_FUNCTION_SIGN', 'Function Sign Analysis', 'Unit 10', '{}'),
('SK_LINEARIZATION_ERROR', 'Linearization Error Bound', 'Unit 10', '{}'),
('SK_SECOND_DERIVATIVE_BOUND', 'Second Derivative Bound', 'Unit 10', '{}')

ON CONFLICT (id) DO NOTHING;
