
export type CourseType = 'AB' | 'BC';

export interface UserPreferences {
  emailNotifications: boolean;
  soundEffects: boolean;
}

export interface UserProfileStats {
  posts: number;
  friends: number;
  channels: number;
}

export interface User {
  id: string; // Supabase UUID
  name: string;
  email: string;
  avatarUrl: string;
  currentCourse: CourseType;
  masteryRate: number;
  problemsSolved: number;
  studyHours: number[]; // Weekly data M-S
  streakDays: number;
  percentile: number; // e.g. Top 15%
  preferences: UserPreferences;
  isCreator: boolean; // RBAC Role
  equippedTitleId?: string;
  equippedTitle?: Title;
  subscriptionTier?: 'basic' | 'pro';
  subscriptionPeriodEnd?: string;
  hasSeenProIntro?: boolean;
  stats?: UserProfileStats;
  bio?: string;
  avatarColor?: string;
  showName?: boolean;
  showEmail?: boolean;
  showBio?: boolean;
}

export interface Title {
  id: string;
  name: string;
  description: string;
  category: 'streak' | 'mastery_unit' | 'mastery_course' | 'social' | 'influence' | string;
  threshold: number;
}

export interface UserTitle {
  user_id: string;
  title_id: string;
  unlocked_at: string;
  title?: Title;
}

// --- Question Engine Types ---

export type QuestionType = 'MCQ' | 'Numeric' | 'FRQ';
export type DifficultyLevel = 1 | 2 | 3 | 4 | 5;
export type QuestionCourseType = 'AB' | 'BC' | 'Both';

export interface QuestionOption {
  id: string; // option_id (Generated by Backend)
  label: string; // A, B, C, D
  value: string; // The text/latex content
  type?: 'text' | 'image';
  errorTagId?: string; // Optional: Map specific wrong answer to an error ID (e.g. ERR_SIGN)
  explanation?: string; // Specific feedback for this option
  explanationType?: 'text' | 'image'; // Type of explanation content
}

export interface Question {
  id: string; // question_id (Generated by Backend)
  title: string; // User-facing name/title
  course: QuestionCourseType; // Supports 'Both' for syncing
  topic: string; // The parent Unit ID (e.g., "Limits" or "AB_Limits")
  topicId?: string; // Unified topic identifier (e.g. BC_Series)
  subTopicId: string; // Chapter (e.g., "1.2")
  sectionId?: string; // Explicit Section ID FK (matches subTopicId usually)

  // Metadata
  status: 'draft' | 'published';
  version: number;
  source: string;
  sourceYear?: number;
  notes?: string;

  // Algorithm Weights
  weightPrimary?: number;
  weightSupporting?: number;

  type: QuestionType;
  calculatorAllowed: boolean;
  difficulty: DifficultyLevel;
  targetTimeSeconds: number; // Algorithm metadata

  skillTags: string[]; // List of skill_ids (Legacy/Cache)
  errorTags: string[]; // List of error_ids for potential tagging (general - Legacy/Cache)

  // Relations
  primarySkillId?: string;
  supportingSkillIds?: string[];
  errorPatternIds?: string[]; // Explicit Error Pattern IDs

  promptType: 'text' | 'image';
  prompt: string;
  latex?: string; // Optional latex representation

  // MCQ Specific
  options: QuestionOption[];
  correctOptionId: string; // points to option_id or holds numeric value if type is Numeric

  // Numeric Specific
  tolerance?: number; // Optional +/- tolerance for numeric answers

  explanation: string; // General solution
  explanationType?: 'text' | 'image'; // Type of explanation

  // Advanced Adaptive Fields
  microExplanations?: Record<string, string>; // Map error_tag_id -> specific explanation
  recommendationReasons?: string[]; // e.g. ['LOW_MASTERY', 'SPACED_REVIEW_DUE']
}

export interface SubTopic {
  id: string;
  title: string;
  description: string;
  description_2?: string; // Detailed description
  content: string; // Markdown-like text for the lesson
  estimatedMinutes: number;
  hasLesson?: boolean;
  hasPractice?: boolean;
  courseScope?: 'both' | 'ab_only' | 'bc_only';
}

export interface UnitTestConfig {
  title: string;
  description: string;
  estimatedMinutes: number;
}

export interface UnitContent {
  id: string;
  title: string;
  description: string;
  subTopics: SubTopic[];
  unitTest?: UnitTestConfig;
}

export interface TopicMastery {
  subject: string;
  A: number; // For Radar Chart
  fullMark: number;
}

export interface Activity {
  id: number;
  title: string;
  description: string;
  timestamp: string;
  type: 'quiz' | 'practice' | 'mastery';
  score?: number;
}

export interface CourseModule {
  id: string;
  title: string;
  progress: number; // 0-100
  status: 'locked' | 'active' | 'completed';
}

export interface CourseState {
  id: CourseType;
  title: string;
  status: 'In Progress' | 'Not Started' | 'Paused' | 'Completed';
  currentModuleIndex: number; // Index in modules array
  modules: CourseModule[];
}

export type SessionMode = 'Adaptive' | 'Review' | 'Random' | 'Summary';

export interface Recommendation {
  topic: string;
  reason: string;
  currentMastery: number;
  targetMastery: number;
  mode: SessionMode;
}

export interface AppNotification {
  id: number;
  text: string;
  time: string;
  unread: boolean;
  link: string;
  type?: string; // e.g. 'gift_claim', 'system', 'chat'
  metadata?: any; // For flexible dynamic content
  chatId?: string; // For direct messages
  channelId?: string; // For forum channels
  messageId?: string; // For deep linking to specific message
  senderName?: string; // For conditional display
  senderId?: string; // For friend status check
  isAccepted?: boolean; // For friend requests persistency
}

// --- Agent Insight Types ---

export interface UserStats {
  userId: string;
  totalAttempts: number;
  correctAttempts: number;
  accuracyRate: number;
  uniqueQuestionsAttempted: number;
  streakCorrect: number;
  streakWrong: number;
  currentStreakDays: number;
  longestStreakDays: number;
  totalTimeMinutes: number;
  lastPracticed: string | null;
}

export interface UserSkillMastery {
  skillId: string;
  skillName: string;
  mastery: number;
  confidence: number;
  streakWrong: number;
  lastPracticed: string | null;
}

export interface UserErrorStat {
  errorTagId: string;
  errorName: string;
  category: string;
  count: number;
}

export interface ReviewQueueItem {
  questionId: string;
  nextReviewAt: string;
  reviewCount: number;
  intervalDays: number;
  isOverdue: boolean;
  questionTopic?: string;
  questionPrompt?: string;
}

export interface QuestionRecommendation {
  questionId: string;
  score: number;
  reason: 'low_mastery' | 'spaced_review' | 'challenge';
  reasonDetail: string;
  skillId?: string;
}

export interface UserInsights {
  stats: UserStats;
  weakSkills: UserSkillMastery[];
  topErrors: UserErrorStat[];
  reviewQueue: ReviewQueueItem[];
  recommendations: QuestionRecommendation[];
}

export interface UserQuestionState {
  userId: string;
  questionId: string;
  isStarred: boolean;
  isFlagged: boolean;
  personalTags: string[];
  personalNote?: string;
  nextReviewAt?: string;
  easeFactor: number;
  intervalDays: number;
  reviewCount: number;
  lastAttemptId?: string;
}

export interface SubmitAttemptParams {
  questionId: string;
  isCorrect: boolean;
  selectedOptionId?: string;
  answerNumeric?: number;
  timeSpentSeconds: number;
  errorTags: string[];
}

export interface SubmitAttemptResult {
  success: boolean;
  attemptId?: string;
  attemptNo?: number;
  isCorrect?: boolean;
  error?: string;
}

export interface QuestionAttempt {
  id: string;
  userId: string;
  questionId: string;
  isCorrect: boolean;
  selectedOptionId?: string;
  answerNumeric?: number;
  timeSpentSeconds: number;
  attemptNo: number;
  errorTags: string[];
  questionVersionId?: string;
  createdAt: string;
}

export interface SubTopicProgress {
  subTopicId: string;
  totalQuestions: number;
  attemptedQuestions: number;
  correctQuestions: number;
  lastActivity: string | null;
}

export interface UserSectionProgress {
  section_id: string;
  status: 'in_progress' | 'completed';
  data: any;
  score: number;
  correct_questions: number;
  total_questions: number;
  last_accessed_at: string;
  entity_type?: 'course' | 'unit' | 'section';
}

export interface UserPrestige {
  user_id: string;
  planet_level: number; // 1-10
  star_level: number; // 0-3
  current_stardust: number;
  total_stardust_collected: number;
}


