
export type CourseType = 'AB' | 'BC';

export interface UserPreferences {
  emailNotifications: boolean;
  soundEffects: boolean;
}

export interface User {
  id: string; // Supabase UUID
  name: string;
  email: string;
  avatarUrl: string;
  currentCourse: CourseType;
  masteryRate: number;
  problemsSolved: number;
  studyHours: number[]; // Weekly data M-S
  streakDays: number;
  percentile: number; // e.g. Top 15%
  preferences: UserPreferences;
  isCreator: boolean; // RBAC Role
}

// --- Question Engine Types ---

export type QuestionType = 'MCQ' | 'Numeric' | 'FRQ';
export type DifficultyLevel = 1 | 2 | 3 | 4 | 5;
export type QuestionCourseType = 'AB' | 'BC' | 'Both';

export interface QuestionOption {
  id: string; // option_id (Generated by Backend)
  label: string; // A, B, C, D
  value: string; // The text/latex content
  type?: 'text' | 'image';
  errorTagId?: string; // Optional: Map specific wrong answer to an error ID (e.g. ERR_SIGN)
  explanation?: string; // Specific feedback for this option
}

export interface Question {
  id: string; // question_id (Generated by Backend)
  title: string; // User-facing name/title
  course: QuestionCourseType; // Supports 'Both' for syncing
  topic: string; // The parent Unit ID (e.g., "Limits" or "AB_Limits")
  subTopicId: string; // Chapter (e.g., "1.2")
  sectionId?: string; // Explicit Section ID FK (matches subTopicId usually)

  // Metadata
  status: 'draft' | 'published';
  version: number;
  source: 'CollegeBoard' | 'textbook' | 'self';
  sourceYear?: number;
  notes?: string;

  // Algorithm Weights
  weightPrimary?: number;
  weightSupporting?: number;

  type: QuestionType;
  calculatorAllowed: boolean;
  difficulty: DifficultyLevel;
  targetTimeSeconds: number; // Algorithm metadata

  skillTags: string[]; // List of skill_ids (Legacy/Cache)
  errorTags: string[]; // List of error_ids for potential tagging (general - Legacy/Cache)

  // Relations
  primarySkillId?: string;
  supportingSkillIds?: string[];
  errorPatternIds?: string[]; // Explicit Error Pattern IDs

  promptType: 'text' | 'image';
  prompt: string;
  latex?: string; // Optional latex representation

  // MCQ Specific
  options: QuestionOption[];
  correctOptionId: string; // points to option_id or holds numeric value if type is Numeric

  // Numeric Specific
  tolerance?: number; // Optional +/- tolerance for numeric answers

  explanation: string; // General solution

  // Advanced Adaptive Fields
  microExplanations?: Record<string, string>; // Map error_tag_id -> specific explanation
  recommendationReasons?: string[]; // e.g. ['LOW_MASTERY', 'SPACED_REVIEW_DUE']
}

export interface SubTopic {
  id: string;
  title: string;
  description: string;
  content: string; // Markdown-like text for the lesson
  estimatedMinutes: number;
  hasLesson?: boolean;
  hasPractice?: boolean;
}

export interface UnitTestConfig {
  title: string;
  description: string;
  estimatedMinutes: number;
}

export interface UnitContent {
  id: string;
  title: string;
  description: string;
  subTopics: SubTopic[];
  unitTest?: UnitTestConfig;
}

export interface TopicMastery {
  subject: string;
  A: number; // For Radar Chart
  fullMark: number;
}

export interface Activity {
  id: number;
  title: string;
  description: string;
  timestamp: string;
  type: 'quiz' | 'practice' | 'mastery';
  score?: number;
}

export interface CourseModule {
  id: string;
  title: string;
  progress: number; // 0-100
  status: 'locked' | 'active' | 'completed';
}

export interface CourseState {
  id: CourseType;
  title: string;
  status: 'In Progress' | 'Not Started' | 'Paused' | 'Completed';
  currentModuleIndex: number; // Index in modules array
  modules: CourseModule[];
}

export type SessionMode = 'Adaptive' | 'Review' | 'Random';

export interface Recommendation {
  topic: string;
  reason: string;
  currentMastery: number;
  targetMastery: number;
  mode: SessionMode;
}

export interface AppNotification {
  id: number;
  text: string;
  time: string;
  unread: boolean;
  link: string;
}
