INSERT INTO public.skills (id, name, unit, prerequisites) VALUES
('SK_ALGEBRA_FLUENCY', 'Algebraic Fluency', 'Unit 7', '{}'),
('SK_CHAIN_RULE', 'Chain Rule', 'Unit 7', '{}'),
('SK_DEPENDENCE_XY', 'Slope Field Dependence on X/Y', 'Unit 7', '{}'),
('SK_DERIV_RULES', 'Derivative Rules (General)', 'Unit 7', '{}'),
('SK_DE_MODEL_VERBAL', 'Modeling with Differential Equations (Verbal)', 'Unit 7', '{}'),
('SK_DE_VERIFY', 'Verifying Solutions to Differential Equations', 'Unit 7', '{}'),
('SK_DOMAIN', 'Domain of Solutions', 'Unit 7', '{}'),
('SK_EQUILIBRIUM_STABILITY', 'Equilibrium Solutions and Stability', 'Unit 7', '{}'),
('SK_EVAL_DYDX_POINT', 'Evaluating dy/dx at a Point', 'Unit 7', '{}'),
('SK_ISOCLINE_ANALYSIS', 'Isocline Analysis', 'Unit 7', '{}'),
('SK_IVP_CHECK', 'Initial Value Problem Verification', 'Unit 7', '{}'),
('SK_IVP_EVAL_DERIV', 'Evaluating Derivative from IVP', 'Unit 7', '{}'),
('SK_MATCH_DE_BEHAVIOR', 'Matching DE to Qualitative Behavior', 'Unit 7', '{}'),
('SK_QUAL_BEHAVIOR', 'Qualitative Behavior of Solutions', 'Unit 7', '{}'),
('SK_RATE_INTERPRET', 'Interpreting Rates of Change', 'Unit 7', '{}'),
('SK_SLOPE_FIELD_READ', 'Reading Slope Fields', 'Unit 7', '{}'),
('SK_SLOPE_FIELD_REASON', 'Reasoning with Slope Fields', 'Unit 7', '{}'),
('SK_SLOPE_FIELD_SKETCH', 'Sketching Slope Fields', 'Unit 7', '{}'),
('SK_APPLY_IC', 'Applying Initial Conditions', 'Unit 7', '{}'),
('SK_COMPARE_EXACT', 'Comparing Approximate vs Exact Solutions', 'Unit 7', '{}'),
('SK_CONCAVITY_REASONING', 'Reasoning with Concavity', 'Unit 7', '{}'),
('SK_EULER_ERROR_CONCAVITY', 'Euler Method Error Analysis (Concavity)', 'Unit 7', '{}'),
('SK_EULER_METHOD', 'Euler''s Method', 'Unit 7', '{}'),
('SK_IDENTIFY_SEPARABLE', 'Identifying Separable Differential Equations', 'Unit 7', '{}'),
('SK_INTEGRATE_BASIC', 'Basic Integration Techniques', 'Unit 7', '{}'),
('SK_LOG_PROPERTIES', 'Logarithmic Properties', 'Unit 7', '{}'),
('SK_PARTIAL_FRACTIONS', 'Partial Fractions', 'Unit 7', '{}'),
('SK_POWER_LAW_SOLUTION', 'Power Law Solutions', 'Unit 7', '{}'),
('SK_SEP_VARIABLES', 'Separation of Variables', 'Unit 7', '{}'),
('SK_SLOPE_EVAL', 'Evaluating Slope', 'Unit 7', '{}'),
('SK_SOLVE_FOR_Y', 'Solving for y (Explicit Solution)', 'Unit 7', '{}'),
('SK_TABLE_ITERATION', 'Euler Method Iteration Table', 'Unit 7', '{}'),
('SK_ALGEBRA', 'Algebraic Manipulation', 'Unit 7', '{}'),
('SK_ALGEBRA_PARTIAL_FRACTIONS', 'Algebraic Partial Fractions', 'Unit 7', '{}'),
('SK_BRANCH_CHOICE', 'Branch Choice (Square Roots)', 'Unit 7', '{}'),
('SK_DATA_FROM_TABLE', 'Extracting Data from Tables', 'Unit 7', '{}'),
('SK_EQUILIBRIA_STABILITY', 'Equilibrium Stability Analysis', 'Unit 7', '{}'),
('SK_EXP_MODEL', 'Exponential Growth/Decay Models', 'Unit 7', '{}'),
('SK_INITIAL_CONDITION', 'Applying Initial Conditions', 'Unit 7', '{}'),
('SK_INTERPRET_K', 'Interpreting Growth Constant k', 'Unit 7', '{}'),
('SK_LOGISTIC_MODEL', 'Logistic Growth Models', 'Unit 7', '{}'),
('SK_LOG_RULES', 'Logarithm Rules', 'Unit 7', '{}'),
('SK_PARAMETER_ESTIMATION', 'Parameter Estimation', 'Unit 7', '{}'),
('SK_PARAMETER_INTERPRET', 'Parameter Interpretation', 'Unit 7', '{}'),
('SK_SEPARATION', 'Separation of Variables', 'Unit 7', '{}'),
('SK_ALGEBRA_SOLVE_FOR_Y', 'Solving for y via Algebra', 'Unit 7', '{}'),
('SK_APPLY_INITIAL_CONDITION', 'Applying Initial Condition', 'Unit 7', '{}'),
('SK_COMPARE_TO_EXACT', 'Comparing to Exact Solution', 'Unit 7', '{}'),
('SK_COMPUTE_ITERATES', 'Computing Euler Iterates', 'Unit 7', '{}'),
('SK_DIFFERENTIATE', 'Differentiating Functions', 'Unit 7', '{}'),
('SK_EQUILIBRIUM', 'Finding Equilibrium Solutions', 'Unit 7', '{}'),
('SK_ERROR_ANALYSIS', 'Error Analysis', 'Unit 7', '{}'),
('SK_EVALUATE_DERIVATIVE_AT_POINT', 'Evaluating Derivative at a Point', 'Unit 7', '{}'),
('SK_EVALUATE_FUNCTION', 'Evaluating Functions', 'Unit 7', '{}'),
('SK_EXPONENTIAL_MODEL', 'Exponential Models', 'Unit 7', '{}'),
('SK_EXPONENT_ALGEBRA', 'Exponent Algebra', 'Unit 7', '{}'),
('SK_HALF_LIFE', 'Half-Life Calculations', 'Unit 7', '{}'),
('SK_IMPLICIT_SOLUTION', 'Implicit Solutions', 'Unit 7', '{}'),
('SK_INTEGRATE', 'Integration', 'Unit 7', '{}'),
('SK_INTERPRET_RATE', 'Interpreting Rate of Change', 'Unit 7', '{}'),
('SK_LOGARITHMS', 'Logarithms', 'Unit 7', '{}'),
('SK_LONG_TERM_BEHAVIOR', 'Long-Term Behavior Analysis', 'Unit 7', '{}'),
('SK_MODELING_DE', 'Modeling with Differential Equations', 'Unit 7', '{}'),
('SK_NUMERICAL_APPROX', 'Numerical Approximation', 'Unit 7', '{}'),
('SK_RECOGNIZE_SOLUTION_FORM', 'Recognizing Solution Forms', 'Unit 7', '{}'),
('SK_SEPARATION_VARIABLES', 'Separation of Variables (Full Term)', 'Unit 7', '{}'),
('SK_SIGN_CHART_AUTONOMOUS', 'Sign Charts for Autonomous DEs', 'Unit 7', '{}'),
('SK_SLOPE_FIELD_INTERPRET', 'Interpreting Slope Fields', 'Unit 7', '{}'),
('SK_SOLVE_EXPLICIT', 'Solving Explicitly', 'Unit 7', '{}'),
('SK_SOLVE_PARAMETER', 'Solving for Parameters', 'Unit 7', '{}'),
('SK_STABILITY', 'Stability Analysis', 'Unit 7', '{}'),
('SK_SUBSTITUTE_INTO_DE', 'Substitution into Differential Equations', 'Unit 7', '{}'),
('SK_USE_TABLE', 'Using Data Tables', 'Unit 7', '{}'),
('SK_VERIFY_SOLUTION', 'Verifying Solutions', 'Unit 7', '{}')



ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    unit = EXCLUDED.unit;
