-- Update Script for Unit 3 Detailed Descriptions
-- Unit: ABBC_Composite (Unit 3)

-- 3.1 The Chain Rule
UPDATE public.sections
SET description2 = 'This chapter focuses on how to differentiate functions that are built from multiple “layers,” where one function is applied inside another. You will learn how to identify the inner and outer structure of a composite expression and determine how changes in the input propagate through each layer. Practice problems emphasize recognizing common patterns quickly, such as nested polynomials, trig expressions inside exponentials, or roots inside rational expressions. You will also strengthen procedural fluency while avoiding common mistakes like differentiating only the outside layer or forgetting to multiply by the derivative of the inside function. Many questions are designed to look simple at first glance but require careful structure recognition. By the end of the chapter, you should be able to efficiently compute derivatives of multi-step expressions and explain why the chain rule is required rather than a basic power or trig rule alone.'
WHERE topic_id = 'ABBC_Composite' AND id = '3.1';

-- 3.2 Implicit Differentiation
UPDATE public.sections
SET description2 = 'This chapter teaches how to differentiate relationships where the dependent variable is not isolated. Instead of solving for one variable first, you will differentiate both sides directly, treating the dependent variable as a function of the independent variable throughout the process. You will learn how to correctly apply derivative rules to mixed-variable terms, including products and powers that contain the dependent variable. A major focus is on consistently applying the chain rule when differentiating terms involving the dependent variable, and on correctly collecting terms to solve for the derivative at the end. Practice includes both straightforward algebraic relationships and more complex expressions that require multiple rules at once. You will also develop error-checking habits, such as confirming that every term was differentiated and that the final expression isolates the derivative correctly. This chapter builds essential skills for later applications like related rates and curve analysis.'
WHERE topic_id = 'ABBC_Composite' AND id = '3.2';

-- 3.3 Differentiating Inverse Functions
UPDATE public.sections
SET description2 = 'This chapter covers how to find derivatives of inverse functions using functional relationships and the idea that inverse functions reverse inputs and outputs. You will learn how to compute the derivative of an inverse at a specific point using information from the original function, often without explicitly finding an inverse formula. Practice problems emphasize interpreting what a given point means for both the function and its inverse, and how to translate values correctly between them. Many questions are designed to test careful thinking about which quantity is known and which must be inferred. You will also work with inverse relationships presented in tables or graphs, requiring precise reading of coordinates and consistent use of function meaning. Common mistakes include swapping the wrong values, using the wrong point, or confusing the derivative of a function with the derivative of its inverse. Mastery here improves both conceptual clarity and exam efficiency.'
WHERE topic_id = 'ABBC_Composite' AND id = '3.3';

-- 3.4 Differentiating Inverse Trigonometric Functions
UPDATE public.sections
SET description2 = 'This chapter focuses on derivatives involving inverse trigonometric functions and how they differ from standard trig derivatives. You will learn the correct derivative patterns and how to combine them with other derivative rules when inverse trig functions appear inside more complex expressions. A major emphasis is recognizing when the chain rule must be applied and avoiding confusion between trig and inverse trig behavior. Problems often require careful attention to structure, sign, and simplification. You will also practice identifying when an expression is in a form that matches an inverse trig derivative template, and when additional rewriting is necessary. Many exam-style questions include inverse trig functions nested inside algebraic terms, requiring multiple steps. Typical errors include mixing up inverse trig derivatives with regular trig derivatives, forgetting a needed multiplier from the inside expression, or incorrectly simplifying the result. This chapter is high value because inverse trig appears frequently in AP-style derivative computation and reasoning tasks.'
WHERE topic_id = 'ABBC_Composite' AND id = '3.4';

-- 3.5 Selecting Procedures for Calculating Derivatives
UPDATE public.sections
SET description2 = 'This chapter trains you to choose the most efficient and correct differentiation method depending on the structure of the problem. Instead of always applying rules mechanically, you will practice identifying which rules are necessary and which are unnecessary. You will compare situations where direct rules work immediately versus cases where the chain rule, product rule, quotient rule, or implicit differentiation is required. You will also learn how to simplify expressions strategically before differentiating to reduce errors and time, and how to recognize when simplifying is risky or unhelpful. Many questions in this chapter resemble “trap” problems where multiple methods seem possible but only one is appropriate or efficient. The goal is to build decision-making speed and accuracy under test conditions. By the end, you should be able to justify your method choice, avoid overcomplicating simple derivatives, and reduce common mistakes caused by choosing the wrong rule.'
WHERE topic_id = 'ABBC_Composite' AND id = '3.5';

-- 3.6 Calculating Higher-Order Derivatives
UPDATE public.sections
SET description2 = 'This chapter covers derivatives beyond the first derivative, including second and higher derivatives used for analyzing how a function’s behavior changes. You will learn how to take repeated derivatives accurately and efficiently, especially for expressions involving products, composites, and special functions. Practice emphasizes staying organized, tracking signs, and avoiding errors from repeated application of rules. You will also connect higher-order derivatives to function behavior, such as how a second derivative relates to whether a function is bending upward or downward, and how repeated derivatives can reveal patterns in certain families of functions. Some problems focus on computation, while others require interpreting what a higher-order derivative means in context. Common mistakes include treating higher derivatives as powers, losing terms during repeated differentiation, or incorrectly applying product and chain rules multiple times. This chapter builds foundation for later topics like motion analysis and curve sketching.'
WHERE topic_id = 'ABBC_Composite' AND id = '3.6';

-- Unit Test (Unit 3 Comprehensive Assessment)
UPDATE public.sections
SET description2 = 'The Unit 3 test is designed to assess mastery across composite differentiation, implicit differentiation, inverse function derivatives, inverse trig derivatives, method selection, and higher-order derivatives. Questions are balanced between procedural accuracy and conceptual understanding, including identifying correct methods, interpreting given information, and connecting values between related functions. The test typically mixes direct computation items with reasoning-focused items that require interpreting graphs, tables, or functional relationships. You will see problems that require multiple rules in a single question, such as chain rule combined with product/quotient structure, or implicit differentiation followed by evaluation at a point. Strategy questions are included to ensure you can choose the simplest correct approach instead of defaulting to a longer method. A strong performance indicates you can differentiate efficiently, avoid common traps, and apply derivative ideas flexibly in AP exam-style settings.'
WHERE topic_id = 'ABBC_Composite' AND id = 'unit_test';
