-- Fix options JSON format for Unit 1 questions (change 'text' to 'value')
BEGIN;

UPDATE questions SET options = '[]'::jsonb WHERE title = 'C3Q1_LeftHandLimitAt2';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C3Q2_TwoSidedLimitJumpAt1';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C3Q3_InfiniteLimitAt0Plus';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C3Q4_RemovableDiscontinuityAtMinus1';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C3Q5_RightHandLimitAt0';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C4Q1_TableLimitApproaches6';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C4Q2_TableTwoSidedLimitDNE';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C4Q3_TableInfiniteLimit';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C4Q4_DifferenceQuotientFromTable';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C4Q5_TableOscillationDNE';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q1_Polynomial_Limit_Substitution';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q2_GraphBased_Limit_Laws';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q3_Combine_Given_Limits';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q4_Quotient_Denominator_Zero';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q5_Rational_Substitution_NonzeroDen';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q1_Factor_Cancel_Basic';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q2_Rationalize_Sqrt_Classic';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q3_Rationalize_DiffOfRoots';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q4_DiffOfCubes_Cancel';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q5_FillTheHole_Continuity';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C7Q1 Procedure from Graph';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C7Q2 Best Procedure for 0/0';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C7Q3 One-Sided Needed at 0';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C7Q4 Infinite Limit at a Vertical Asymptote';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C7Q5 Procedure Choice for Jump Discontinuity';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C8Q1 Trig-Oscillation Product Squeeze';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C8Q2 Squeeze Visualization';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C8Q3 Oscillation Not Squeezed';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C8Q4 Inequality-Form Squeeze';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C8Q5 Squeeze/Product with Trig Square';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C9Q1_Limit_Consistent_With_Graph';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C9Q2_Limit_Using_Symbolic_With_Redefinition';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C9Q3_Connect_Table_To_OneSided_Limits';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C9Q4_Limit_From_Table_At_2';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C9Q5_Connect_AbsoluteValue_To_OneSided';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C10Q1_Classify_Discontinuity_From_Graph';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C10Q2_Remove_Discontinuity_By_Definition';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C10Q3_Infinite_Limit_And_Asymptote';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C10Q4_Classify_Removable_From_Limit_Facts';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C10Q5_Removable_When_Value_Differs_From_Limit';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C11Q1_DefinitionCheck_PiecewiseValue';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C11Q2_GraphContinuityAtPoint';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C11Q3_RemovableDiscontinuity_SetK';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C11Q4_PiecewiseJunction_Continuity';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C11Q5_SolveA_GivenB_Continuity';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C12Q1_ContinuityInterval_RadicalDomain';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C12Q2_ContinuityAllReals_SolveK';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C12Q3_ContinuityOverIntervalGraph';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C12Q4_RationalFunction_ContinuityDomain';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C12Q5_IVT_ContinuityOnInterval';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C13-Q1 Fill the Hole by Defining f(3)';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C13-Q2 Choose k for Continuity at x=1';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C13-Q3 Limit at a Removable Discontinuity';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C13-Q4 Continuity + Point Value Determines Line';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C13-Q5 Conjugate to Evaluate a Limit';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C14-Q1 One-Sided Infinite Limit of Reciprocal';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C14-Q2 Hole vs Vertical Asymptote After Cancellation';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C14-Q3 Odd Power Denominator Sign to -Infinity';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C14-Q4 Identify Vertical Asymptote vs Hole by Factoring';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'C14-Q5 Even Power Denominator Gives +Infinity Both Sides';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q1_HorizontalAsymptote_EqualDegrees';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q2_TableLimitAtInfinity';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q3_EndBehaviorFromGraph';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q4_LimitAtNegativeInfinity_LeadingTerms';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C15_Q5_HorizontalAsymptote_RadicalOverX';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q1_IVT_GuaranteedZero';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q2_IVT_SetupFor_fxEqualsK';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q3_IVT_GraphYEquals2';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q4_IVT_FailsDueToHoleInInterval';
UPDATE questions SET options = '[]'::jsonb WHERE title = 'U1C16_Q5_DiscontinuityCounterexample';
COMMIT;
