-- Insert Unit 2 Questions
BEGIN;

DELETE FROM questions WHERE title = 'U2C2.1-Q1 Average ROC from Endpoint Values';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.1-Q1 Average ROC from Endpoint Values', 'Let $f$ be a function with $f(1)=3$ and $f(5)=-1$. What is the average rate of change of $f$ on the interval $[1,5]$?', 'text', 'mcq', 'Level2', 2, 'AP_Calculus_BC', 'Both_Derivatives', '2.1', 'Unit2', 'SK_AVG_ROC', '{SK_SLOPE_2PTS,SK_FUNC_EVAL}', '{Average rate of change,Slope from two points,Function evaluation}', '{Swap x-values in slope,Confuse average vs instantaneous rate}', '[{"id": "A", "explanation": "This would come from using $f(1)-f(5)$ in the numerator but not matching the denominator sign correctly.", "value": "$1$", "label": "A"}, {"id": "B", "explanation": "This is $\\dfrac{-1-3}{4}=-1$.", "value": "$-1$", "label": "B"}, {"id": "C", "explanation": "This incorrectly uses $f(5)-f(1)$ but forgets to divide by $5-1$.", "value": "$-4$", "label": "C"}, {"id": "D", "explanation": "This incorrectly uses $f(1)-f(5)=4$ without dividing by the interval length.", "value": "$4$", "label": "D"}]'::jsonb, 'B', 'Average rate of change on $[1,5]$ is
$$\frac{f(5)-f(1)}{5-1}=\frac{-1-3}{4}=\frac{-4}{4}=-1.$$', NULL, 'published', 1);

DELETE FROM questions WHERE title = 'U2C2.1-Q2 Instantaneous Velocity as a Limit';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.1-Q2 Instantaneous Velocity as a Limit', 'A car’s position (in meters) is given by $s(t)$. Which expression best represents the instantaneous velocity at $t=4$ (in m/s)?', 'text', 'mcq', 'Level3', 3, 'AP_Calculus_BC', 'Both_Derivatives', '2.1', 'Unit2', 'SK_INST_ROC', '{SK_LIMIT_INTUITION}', '{Instantaneous rate of change,Secant-to-tangent reasoning,Limit intuition}', '{Confuse average vs instantaneous rate,Treat h as 0 too early}', '[{"id": "A", "explanation": "This is an average velocity on $[3,5]$, not instantaneous at $t=4$.", "value": "$\\dfrac{s(5)-s(3)}{2}$", "label": "A"}, {"id": "B", "explanation": "This is an average velocity on $[0,4]$.", "value": "$\\dfrac{s(4)-s(0)}{4}$", "label": "B"}, {"id": "C", "explanation": "This is the limit definition of instantaneous velocity at $t=4$.", "value": "$\\lim_{h\\to 0}\\dfrac{s(4+h)-s(4)}{h}$", "label": "C"}, {"id": "D", "explanation": "Substituting $h=0$ creates division by zero; you must take a limit.", "value": "$\\dfrac{s(4+0)-s(4)}{0}$", "label": "D"}]'::jsonb, 'C', 'Instantaneous velocity is the derivative $s''(t)$, defined by
$$s''(4)=\lim_{h\to 0}\frac{s(4+h)-s(4)}{h}.$$', NULL, 'published', 1);

DELETE FROM questions WHERE title = 'U2C2.1-Q3 Bounding Average ROC Using Derivative Bounds';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.1-Q3 Bounding Average ROC Using Derivative Bounds', 'Suppose $f$ is differentiable on $[2,6]$ and you know that $-3\le f''(x)\le 1$ for all $x$ in $(2,6)$. Which statement must be true about the average rate of change of $f$ on $[2,6]$?', 'text', 'mcq', 'Level4', 4, 'AP_Calculus_BC', 'Both_Derivatives', '2.1', 'Unit2', 'SK_AVG_ROC', '{SK_INEQUALITY_REASONING}', '{Average rate of change,Interval reasoning,Inequalities}', '{Confuse average vs instantaneous rate,Sign error in difference quotient}', '[{"id": "A", "explanation": "The derivative bounds do not force a single exact average slope.", "value": "The average rate of change on $[2,6]$ is exactly $-1$.", "label": "A"}, {"id": "B", "explanation": "It cannot be less than the minimum possible slope bound.", "value": "The average rate of change on $[2,6]$ is less than $-3$.", "label": "B"}, {"id": "C", "explanation": "The average slope must lie within the derivative bounds.", "value": "The average rate of change on $[2,6]$ is between $-3$ and $1$, inclusive.", "label": "C"}, {"id": "D", "explanation": "It cannot exceed the maximum possible slope bound.", "value": "The average rate of change on $[2,6]$ is greater than $1$.", "label": "D"}]'::jsonb, 'C', 'Since $f$ is differentiable and $-3\le f''(x)\le 1$ on $(2,6)$, the change in $f$ over $[2,6]$ cannot produce an average slope outside these bounds. Therefore,
$$-3\le \frac{f(6)-f(2)}{6-2}\le 1.$$', NULL, 'published', 1);

DELETE FROM questions WHERE title = 'U2C2.1-Q4 Linear Function Average ROC';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.1-Q4 Linear Function Average ROC', 'The function $g$ is linear and passes through $(2,7)$ and $(6,1)$. What is the average rate of change of $g$ on $[2,6]$?', 'text', 'mcq', 'Level1', 1, 'AP_Calculus_BC', 'Both_Derivatives', '2.1', 'Unit2', 'SK_SLOPE_2PTS', '{SK_AVG_ROC}', '{Slope from two points,Average rate of change}', '{Swap x-values in slope}', '[{"id": "A", "explanation": "This comes from using $\\dfrac{7-1}{6-2}$ but forgetting the sign.", "value": "$\\dfrac{3}{2}$", "label": "A"}, {"id": "B", "explanation": "This is $\\dfrac{1-7}{6-2}=-\\dfrac{6}{4}=-\\dfrac{3}{2}$.", "value": "$-\\dfrac{3}{2}$", "label": "B"}, {"id": "C", "explanation": "This incorrectly divides by $2$ instead of $4$.", "value": "$-3$", "label": "C"}, {"id": "D", "explanation": "This ignores the negative change in $y$.", "value": "$3$", "label": "D"}]'::jsonb, 'B', 'Average rate of change on $[2,6]$ is the secant slope:
$$\frac{g(6)-g(2)}{6-2}=\frac{1-7}{4}=\frac{-6}{4}=-\frac{3}{2}.$$', NULL, 'published', 1);

DELETE FROM questions WHERE title = 'U2C2.1-Q5 Derivative as a Limit Statement';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.1-Q5 Derivative as a Limit Statement', 'For a differentiable function $f$, which statement is always true?', 'text', 'mcq', 'Level3', 3, 'AP_Calculus_BC', 'Both_Derivatives', '2.1', 'Unit2', 'SK_INST_ROC', '{}', '{Instantaneous rate of change,Tangent slope concept}', '{Confuse average vs instantaneous rate}', '[{"id": "A", "explanation": "This would only hold for special functions (e.g., linear), not always.", "value": "The instantaneous rate of change at $x=a$ equals the average rate of change on every interval $[a,a+h]$.", "label": "A"}, {"id": "B", "explanation": "Average slope over an interval does not always equal the derivative at the right endpoint.", "value": "The average rate of change on $[a,a+h]$ equals $f''(a+h)$ for all small $h$.", "label": "B"}, {"id": "C", "explanation": "This is precisely the definition of the derivative.", "value": "If the limit $\\lim_{h\\to 0}\\dfrac{f(a+h)-f(a)}{h}$ exists, it equals $f''(a)$.", "label": "C"}, {"id": "D", "explanation": "Differentiability gives a limit, not equality for each nonzero $h$.", "value": "If $f$ is differentiable at $a$, then $\\dfrac{f(a+h)-f(a)}{h}=f''(a)$ for $h\\ne 0$.", "label": "D"}]'::jsonb, 'C', 'By definition, the derivative at $x=a$ is
$$f''(a)=\lim_{h\to 0}\frac{f(a+h)-f(a)}{h}$$
provided that this limit exists.', NULL, 'published', 1);

DELETE FROM questions WHERE title = 'U2C2.2-Q1 Correct Notation for $f''(3)$';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.2-Q1 Correct Notation for $f''(3)$', 'If $y=f(x)$, which notation correctly represents the derivative of $f$ with respect to $x$ evaluated at $x=3$?', 'text', 'mcq', 'Level2', 2, 'AP_Calculus_BC', 'Both_Derivatives', '2.2', 'Unit2', 'SK_DERIV_NOTATION', '{SK_SYMBOL_INTERPRET}', '{Derivative notation,Interpret derivative as slope}', '{Misread derivative notation}', '[{"id": "A", "explanation": "This is the standard notation for the derivative evaluated at $x=3$.", "value": "$f''(3)$", "label": "A"}, {"id": "B", "explanation": "This is not standard; the prime applies to the function, not to the value written this way.", "value": "$f(3)''$", "label": "B"}, {"id": "C", "explanation": "This sets the derivative equal to 3 without any information; it is not an evaluation notation.", "value": "$\\dfrac{dy}{dx}=3$", "label": "C"}, {"id": "D", "explanation": "The denominator should be $dx$, not a number.", "value": "$\\dfrac{df}{d3}$", "label": "D"}]'::jsonb, 'A', 'The derivative of $f$ evaluated at $x=3$ is written $f''(3)$. An equivalent form is $\left.\dfrac{dy}{dx}\right|_{x=3}$ if $y=f(x)$.', NULL, 'published', 1);

DELETE FROM questions WHERE title = 'U2C2.2-Q2 Limit Definition to Compute $f''(2)$';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.2-Q2 Limit Definition to Compute $f''(2)$', 'Use the limit definition to find $f''(2)$ for $f(x)=x^2-4x$.', 'text', 'mcq', 'Level3', 3, 'AP_Calculus_BC', 'Both_Derivatives', '2.2', 'Unit2', 'SK_LIMIT_DEF_DERIV', '{SK_DIFF_QUOTIENT,SK_ALGEBRA_SIMPLIFY}', '{Limit definition of derivative,Difference quotient,Algebraic simplification}', '{Treat h as 0 too early,Cancel incorrectly}', '[{"id": "A", "explanation": "This is the correct result: the tangent slope at $x=2$ is zero.", "value": "$0$", "label": "A"}, {"id": "B", "explanation": "This can come from plugging $h=0$ too early or mishandling terms.", "value": "$-4$", "label": "B"}, {"id": "C", "explanation": "This often results from a sign error when expanding $f(2+h)$.", "value": "$4$", "label": "C"}, {"id": "D", "explanation": "Polynomials are differentiable everywhere, so the derivative exists at $x=2$.", "value": "Does not exist", "label": "D"}]'::jsonb, 'A', 'Compute using the limit definition:
$$f(2)=2^2-4\cdot 2=4-8=-4.$$
Next,
$$f(2+h)=(2+h)^2-4(2+h)=4+4h+h^2-8-4h=h^2-4.$$
So
$$\frac{f(2+h)-f(2)}{h}=\frac{(h^2-4)-(-4)}{h}=\frac{h^2}{h}=h.$$
Taking the limit gives $\lim_{h\to 0} h=0$.', NULL, 'published', 1);

DELETE FROM questions WHERE title = 'U2C2.2-Q3 Simplify Limit Definition for $\sqrt{x}$';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.2-Q3 Simplify Limit Definition for $\sqrt{x}$', 'Let $f(x)=\sqrt{x}$. Which expression is equal to $f''(a)$ for $a>0$ using the limit definition, after simplifying to remove radicals from the denominator?', 'text', 'mcq', 'Level4', 4, 'AP_Calculus_BC', 'Both_Derivatives', '2.2', 'Unit2', 'SK_LIMIT_DEF_DERIV', '{SK_ALGEBRA_SIMPLIFY,SK_DIFF_QUOTIENT}', '{Difference quotient,Algebraic simplification,Limit definition of derivative}', '{Cancel incorrectly,Sign error in difference quotient}', '[{"id": "A", "explanation": "This is not equivalent; rationalization requires multiplying numerator and denominator, not replacing terms.", "value": "$\\lim_{h\\to 0}\\dfrac{\\sqrt{a+h}+\\sqrt{a}}{h}$", "label": "A"}, {"id": "B", "explanation": "This inverts the expression incorrectly.", "value": "$\\lim_{h\\to 0}\\dfrac{1}{\\sqrt{a+h}-\\sqrt{a}}$", "label": "B"}, {"id": "C", "explanation": "After rationalizing, the expression becomes $\\dfrac{1}{\\sqrt{a+h}+\\sqrt{a}}$.", "value": "$\\lim_{h\\to 0}\\dfrac{1}{\\sqrt{a+h}+\\sqrt{a}}$", "label": "C"}, {"id": "D", "explanation": "This omits the necessary $h$ factor cancellation step and is not equal to the derivative expression.", "value": "$\\lim_{h\\to 0}\\dfrac{\\sqrt{a+h}-\\sqrt{a}}{\\sqrt{a+h}+\\sqrt{a}}$", "label": "D"}]'::jsonb, 'C', 'Begin with
$$f''(a)=\lim_{h\to 0}\frac{\sqrt{a+h}-\sqrt{a}}{h}.$$ 
Multiply numerator and denominator by the conjugate $\sqrt{a+h}+\sqrt{a}$:
$$\frac{\sqrt{a+h}-\sqrt{a}}{h}\cdot\frac{\sqrt{a+h}+\sqrt{a}}{\sqrt{a+h}+\sqrt{a}}=
\frac{(a+h)-a}{h(\sqrt{a+h}+\sqrt{a})}=
\frac{h}{h(\sqrt{a+h}+\sqrt{a})}=
\frac{1}{\sqrt{a+h}+\sqrt{a}}.$$ 
So the derivative is
$$f''(a)=\lim_{h\to 0}\frac{1}{\sqrt{a+h}+\sqrt{a}}.$$', NULL, 'published', 1);

DELETE FROM questions WHERE title = 'U2C2.2-Q4 Meaning of $f''(5)=-2$';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.2-Q4 Meaning of $f''(5)=-2$', 'If $f''(5)=-2$, which statement is correct?', 'text', 'mcq', 'Level1', 1, 'AP_Calculus_BC', 'Both_Derivatives', '2.2', 'Unit2', 'SK_SYMBOL_INTERPRET', '{}', '{Derivative notation,Interpret derivative as slope}', '{Misread derivative notation}', '[{"id": "A", "explanation": "This is exactly what $f''(5)=-2$ means.", "value": "The tangent line to $y=f(x)$ at $x=5$ has slope $-2$.", "label": "A"}, {"id": "B", "explanation": "The derivative value is not the same as the function value.", "value": "$f(5)=-2$.", "label": "B"}, {"id": "C", "explanation": "A derivative at a point does not determine an average slope over a larger interval.", "value": "The secant line from $x=0$ to $x=5$ has slope $-2$.", "label": "C"}, {"id": "D", "explanation": "$f''(5)<0$ only guarantees decreasing behavior near $x=5$, not everywhere.", "value": "The function is decreasing for all $x$.", "label": "D"}]'::jsonb, 'A', 'By definition, $f''(5)$ is the slope of the tangent line to $y=f(x)$ at $x=5$. So $f''(5)=-2$ means that tangent slope is $-2$.', NULL, 'published', 1);

DELETE FROM questions WHERE title = 'U2C2.2-Q5 Simplify Difference Quotient for $1/x$';
INSERT INTO questions (title, prompt, prompt_type, type, difficulty, reasoning_level, course, topic, sub_topic_id, section_id, primary_skill_id, supporting_skill_ids, skill_tags, error_tags, options, correct_option_id, explanation, tolerance, status, version) VALUES ('U2C2.2-Q5 Simplify Difference Quotient for $1/x$', 'For $f(x)=\dfrac{1}{x}$, evaluate the simplified expression
$$\frac{f(a+h)-f(a)}{h}$$
for $a\ne 0$ and $h\ne 0$, $a+h\ne 0$.', 'text', 'mcq', 'Level5', 5, 'AP_Calculus_BC', 'Both_Derivatives', '2.2', 'Unit2', 'SK_DIFF_QUOTIENT', '{SK_ALGEBRA_SIMPLIFY,SK_DERIV_NOTATION}', '{Difference quotient,Derivative notation,Algebraic simplification}', '{Sign error in difference quotient,Cancel incorrectly}', '[{"id": "A", "explanation": "This misses the negative sign that arises from $\\frac{1}{a+h}-\\frac{1}{a}$.", "value": "$\\dfrac{1}{a(a+h)}$", "label": "A"}, {"id": "B", "explanation": "Correct: $\\dfrac{\\frac{1}{a+h}-\\frac{1}{a}}{h}=-\\dfrac{1}{a(a+h)}$.", "value": "$-\\dfrac{1}{a(a+h)}$", "label": "B"}, {"id": "C", "explanation": "An extra $h$ remains; it should cancel during simplification.", "value": "$-\\dfrac{h}{a(a+h)}$", "label": "C"}, {"id": "D", "explanation": "This incorrectly treats $f(x)=1/x$ like a linear function.", "value": "$\\dfrac{a+h-a}{h}$", "label": "D"}]'::jsonb, 'B', 'Compute the difference quotient:
$$\frac{f(a+h)-f(a)}{h}=\frac{\frac{1}{a+h}-\frac{1}{a}}{h}=
\frac{\frac{a-(a+h)}{a(a+h)}}{h}=
\frac{\frac{-h}{a(a+h)}}{h}=-\frac{1}{a(a+h)}.$$', NULL, 'published', 1);

COMMIT;
