-- Insert/Update script for Unit 1 Unit Test Questions
BEGIN;
-- Question: UT1-Q01-PolynomialLimit
DELETE FROM public.questions WHERE title = 'UT1-Q01-PolynomialLimit';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 2, 75, ARRAY['LimitNotation', 'LimitLaws']::text[], ARRAY['NotationMisread', 'OneSidedVsTwoSided']::text[], 'Evaluate the limit.

$$\lim_{x\to 3}\left(2x^2-5x+1\right)$$', '$$\lim_{x\to 3}\left(2x^2-5x+1\right)$$', '[{"id": "A", "text": "4", "explanation": "This comes from substituting $x=2$, not $x=3$."}, {"id": "B", "text": "4", "explanation": "Substitute $x=3$: $2(9)-5(3)+1=18-15+1=4$."}, {"id": "C", "text": "10", "explanation": "This is $2(9)-5(3)$ but forgetting the $+1$."}, {"id": "D", "text": "-4", "explanation": "Sign error in $-5x$ or arithmetic error."}]', 'B', 'Polynomials are continuous everywhere, so evaluate by direct substitution:
$$\lim_{x\to 3}(2x^2-5x+1)=2(3^2)-5(3)+1=18-15+1=4.$$', '[{"option_id": "A", "text": "Used the wrong approach value."}, {"option_id": "B", "text": "Correct direct substitution."}, {"option_id": "C", "text": "Dropped the constant term."}, {"option_id": "D", "text": "Arithmetic/sign mistake."}]', ARRAY['Reinforces limit-as-substitution for continuous functions.', 'Checks careful arithmetic under time pressure.']::text[], 'published', 1, 1, 1.0, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.2 Defining limits and limit notation (evaluate basic limits of continuous functions).', 0.8, 0.2, 'UT1-Q01-PolynomialLimit', 'text', 'LimitNotation', ARRAY['LimitLaws']::text[], NOW(), NOW());

-- Question: UT1-Q02-FactoringCancelLimit
DELETE FROM public.questions WHERE title = 'UT1-Q02-FactoringCancelLimit';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 3, 110, ARRAY['AlgebraicLimit', 'LimitLaws']::text[], ARRAY['AlgebraicCancelError', 'NotationMisread']::text[], 'Evaluate the limit.

$$\lim_{x\to 2}\frac{x^2-4}{x-2}$$', '$$\lim_{x\to 2}\frac{x^2-4}{x-2}$$', '[{"id": "A", "text": "0", "explanation": "This is the numerator value at $x=2$, not the simplified limit."}, {"id": "B", "text": "2", "explanation": "This would be $x$ at $2$, but the simplified expression is $x+2$."}, {"id": "C", "text": "Does not exist", "explanation": "The original form is $0/0$, which is indeterminate, not automatically DNE."}, {"id": "D", "text": "4", "explanation": "Factor: $x^2-4=(x-2)(x+2)$, cancel $x-2$, then evaluate $x+2$ at $2$."}]', 'D', 'Rewrite and simplify:
$$\frac{x^2-4}{x-2}=\frac{(x-2)(x+2)}{x-2}=x+2\quad (x\ne 2).$$
So
$$\lim_{x\to 2}\frac{x^2-4}{x-2}=\lim_{x\to 2}(x+2)=4.$$', '[{"option_id": "A", "text": "Confused numerator value with limit value."}, {"option_id": "B", "text": "Simplified incorrectly."}, {"option_id": "C", "text": "Indeterminate form requires algebra/other method."}, {"option_id": "D", "text": "Correct factoring and cancellation."}]', ARRAY['Targets the classic $0/0$ indeterminate form.', 'Builds factoring/canceling fluency for limits.']::text[], 'published', 1, 2, 1.1, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.6 Determining limits using algebraic manipulation (factoring/canceling).', 0.75, 0.25, 'UT1-Q02-FactoringCancelLimit', 'text', 'AlgebraicLimit', ARRAY['LimitLaws']::text[], NOW(), NOW());

-- Question: UT1-Q03-GraphLimit
DELETE FROM public.questions WHERE title = 'UT1-Q03-GraphLimit';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 2, 90, ARRAY['GraphicalLimit']::text[], ARRAY['OneSidedVsTwoSided', 'AsymptoteMisread']::text[], 'Use the graph provided to evaluate.

What is
$$\lim_{x\to 2} f(x)?$$

(See image.)', '$$\lim_{x\to 2} f(x)$$', '[{"id": "A", "text": "Does not exist", "explanation": "As $x\\to 2^-$, $f(x)\\to -\\infty$ and as $x\\to 2^+$, $f(x)\\to +\\infty$, so the two-sided limit does not exist."}, {"id": "B", "text": "0", "explanation": "Confuses the $x$-axis intersection with the limit at $x=2$."}, {"id": "C", "text": "$+\\infty$", "explanation": "That is only the right-hand behavior; two-sided limit requires both sides match."}, {"id": "D", "text": "$-\\infty$", "explanation": "That is only the left-hand behavior; two-sided limit requires both sides match."}]', 'A', 'From the graph, there is a vertical asymptote at $x=2$. The function decreases without bound as $x\to 2^-$ and increases without bound as $x\to 2^+$. Since the one-sided behaviors are not equal, the two-sided limit does not exist.', '[{"option_id": "A", "text": "Opposite infinite one-sided behavior."}, {"option_id": "B", "text": "Read the wrong feature of the graph."}, {"option_id": "C", "text": "Only right-hand limit."}, {"option_id": "D", "text": "Only left-hand limit."}]', ARRAY['Checks correct interpretation of vertical asymptotes.', 'Forces two-sided vs one-sided distinction from a graph.']::text[], 'published', 1, 2, 1.1, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.3 Estimating limit values from graphs (including infinite limits and two-sided existence).', 1.0, 0.0, 'UT1-Q03-GraphLimit', 'text_and_image', 'GraphicalLimit', ARRAY[]::text[], NOW(), NOW());

-- Question: UT1-Q04-TableLimit
DELETE FROM public.questions WHERE title = 'UT1-Q04-TableLimit';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 2, 85, ARRAY['NumericalLimit']::text[], ARRAY['DirectionConfusion', 'NotationMisread']::text[], 'Use the table provided to estimate.

What is the best estimate of
$$\lim_{x\to 2} g(x)?$$

(See image.)', '$$\lim_{x\to 2} g(x)$$', '[{"id": "A", "text": "3.6", "explanation": "This uses the value at $x=1.9$ only and ignores values closer to $2$."}, {"id": "B", "text": "3.9", "explanation": "This uses $x=1.99$ only and ignores the trend from both sides."}, {"id": "C", "text": "4.0", "explanation": "Values approach $4$ from both sides: $3.996001$ (left) and $4.004001$ (right)."}, {"id": "D", "text": "4.4", "explanation": "This uses the value at $x=2.1$ which is not very close to $2$."}]', 'C', 'As $x$ gets closer to $2$ from the left, $g(x)$ is near $3.996$, and from the right, $g(x)$ is near $4.004$. Both sides approach $4$, so the best estimate is $4.0$.', '[{"option_id": "A", "text": "Used a point too far from 2."}, {"option_id": "B", "text": "Ignored right-hand approach."}, {"option_id": "C", "text": "Correct two-sided estimate near 4."}, {"option_id": "D", "text": "Used a point too far from 2."}]', ARRAY['Trains reading two-sided trend from a table.', 'Reinforces that limits depend on approach, not necessarily value at the point.']::text[], 'published', 1, 2, 1.0, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.4 Estimating limit values from tables (two-sided numerical evidence).', 1.0, 0.0, 'UT1-Q04-TableLimit', 'text_and_image', 'NumericalLimit', ARRAY[]::text[], NOW(), NOW());

-- Question: UT1-Q05-LimitLawsRationals
DELETE FROM public.questions WHERE title = 'UT1-Q05-LimitLawsRationals';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 3, 115, ARRAY['LimitLaws', 'StrategySelection']::text[], ARRAY['InfinityArithmetic', 'NotationMisread']::text[], 'Evaluate the limit using limit laws.

$$\lim_{x\to -1}\left(\frac{3}{x+2}+\frac{2x}{x^2+3}\right)$$', '$$\lim_{x\to -1}\left(\frac{3}{x+2}+\frac{2x}{x^2+3}\right)$$', '[{"id": "A", "text": "$\\frac{5}{4}$", "explanation": "Compute each term at $x=-1$: $\\frac{3}{1}=3$ and $\\frac{2(-1)}{1+3}=-\\frac12$; sum $=\\frac{5}{2}$, not $\\frac{5}{4}$."}, {"id": "B", "text": "$\\frac{5}{2}$", "explanation": "Direct substitution works since denominators are nonzero at $x=-1$."}, {"id": "C", "text": "$\\frac{1}{2}$", "explanation": "This is only the second term value, missing the first term."}, {"id": "D", "text": "Does not exist", "explanation": "The expression is defined at $x=-1$, so the limit exists."}]', 'B', 'Both denominators are nonzero at $x=-1$, so substitute:
$$\frac{3}{-1+2}+\frac{2(-1)}{(-1)^2+3}=\frac{3}{1}-\frac{2}{4}=3-\frac12=\frac{5}{2}.$$', '[{"option_id": "A", "text": "Arithmetic slip in the sum."}, {"option_id": "B", "text": "Correct: both terms continuous at $x=-1$."}, {"option_id": "C", "text": "Forgot the first term."}, {"option_id": "D", "text": "Mistakenly assumed nonexistence."}]', ARRAY['Checks denominator-nonzero condition before substituting.', 'Reinforces combining rational limits via limit laws.']::text[], 'published', 1, 2, 1.05, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.5 Algebraic properties of limits (sum of rational functions).', 0.7, 0.3, 'UT1-Q05-LimitLawsRationals', 'text', 'LimitLaws', ARRAY['StrategySelection']::text[], NOW(), NOW());

-- Question: UT1-Q06-RationalizeLimit
DELETE FROM public.questions WHERE title = 'UT1-Q06-RationalizeLimit';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 4, 140, ARRAY['AlgebraicLimit', 'StrategySelection']::text[], ARRAY['AlgebraicCancelError', 'NotationMisread']::text[], 'Evaluate the limit.

$$\lim_{x\to 0}\frac{\sqrt{1+x}-1}{x}$$', '$$\lim_{x\to 0}\frac{\sqrt{1+x}-1}{x}$$', '[{"id": "A", "text": "0", "explanation": "Direct substitution gives $0/0$, which is indeterminate."}, {"id": "B", "text": "1", "explanation": "This is the common value for a related form, but the correct limit is $\\frac12$."}, {"id": "C", "text": "2", "explanation": "This would come from incorrect rationalization (inverting the factor)."}, {"id": "D", "text": "$\\frac12$", "explanation": "Rationalize: multiply by $\\sqrt{1+x}+1$ to simplify and then substitute."}]', 'D', 'Rationalize:
$$\frac{\sqrt{1+x}-1}{x}\cdot\frac{\sqrt{1+x}+1}{\sqrt{1+x}+1}=\frac{(1+x)-1}{x(\sqrt{1+x}+1)}=\frac{1}{\sqrt{1+x}+1}.$$ 
Now substitute $x=0$:
$$\lim_{x\to 0}\frac{1}{\sqrt{1+x}+1}=\frac{1}{2}.$$', '[{"option_id": "A", "text": "Stopped at indeterminate form."}, {"option_id": "B", "text": "Confused with a different standard limit."}, {"option_id": "C", "text": "Algebra error in rationalization."}, {"option_id": "D", "text": "Correct rationalization and substitution."}]', ARRAY['Core algebraic manipulation limit (rationalization).', 'High-frequency AP error: stopping at $0/0$.']::text[], 'published', 1, 3, 1.2, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.6 Algebraic manipulation (rationalizing radicals).', 0.8, 0.2, 'UT1-Q06-RationalizeLimit', 'text', 'AlgebraicLimit', ARRAY['StrategySelection']::text[], NOW(), NOW());

-- Question: UT1-Q07-ValueVsLimit
DELETE FROM public.questions WHERE title = 'UT1-Q07-ValueVsLimit';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 3, 120, ARRAY['StrategySelection']::text[], ARRAY['NotationMisread', 'OneSidedVsTwoSided']::text[], 'Let
$$f(x)=\begin{cases}
\frac{x^2-1}{x-1},& x\ne 1\\
7,& x=1
\end{cases}$$
Which statement is true?', '$$f(x)=\begin{cases}\frac{x^2-1}{x-1},& x\ne 1\\7,& x=1\end{cases}$$', '[{"id": "A", "text": "$\\lim_{x\\to 1}f(x)=7$", "explanation": "The limit depends on nearby values, not $f(1)$."}, {"id": "B", "text": "$\\lim_{x\\to 1}f(x)=2$ but $f(1)=7$", "explanation": "For $x\\ne 1$, $\\frac{x^2-1}{x-1}=x+1$, so the limit at $1$ is $2$, while the defined value is $7$."}, {"id": "C", "text": "$\\lim_{x\\to 1}f(x)$ does not exist because $f(1)$ is defined differently", "explanation": "A redefined point value does not destroy the limit if nearby behavior is consistent."}, {"id": "D", "text": "$\\lim_{x\\to 1}f(x)=7$ and $f$ is continuous at $x=1$", "explanation": "Continuity would require $f(1)=\\lim_{x\\to 1}f(x)$, which is false here."}]', 'B', 'For $x\ne 1$, factor $x^2-1=(x-1)(x+1)$ so $f(x)=x+1$. Thus
$$\lim_{x\to 1}f(x)=\lim_{x\to 1}(x+1)=2,$$
while $f(1)=7$ by definition. The limit exists but the function is not continuous at $x=1$.', '[{"option_id": "A", "text": "Confused limit with function value."}, {"option_id": "B", "text": "Correct: limit 2, value 7."}, {"option_id": "C", "text": "Point redefinition does not force DNE."}, {"option_id": "D", "text": "Continuity condition violated."}]', ARRAY['Tests choosing the right method (simplify first, then evaluate).', 'Separates $\lim_{x\to a}f(x)$ from $f(a)$.']::text[], 'published', 1, 2, 1.15, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.7 Selecting procedures for determining limits (distinguish value vs limit; simplify first).', 0.9, 0.1, 'UT1-Q07-ValueVsLimit', 'text', 'StrategySelection', ARRAY['AlgebraicLimit']::text[], NOW(), NOW());

-- Question: UT1-Q08-SqueezeOscillation
DELETE FROM public.questions WHERE title = 'UT1-Q08-SqueezeOscillation';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 4, 150, ARRAY['SqueezeTheorem']::text[], ARRAY['SqueezeTheoremMisuse', 'InfinityArithmetic']::text[], 'Evaluate the limit.

$$\lim_{x\to 0} x^2\sin\left(\frac{1}{x}\right)$$', '$$\lim_{x\to 0} x^2\sin\left(\frac{1}{x}\right)$$', '[{"id": "A", "text": "Does not exist", "explanation": "$\\sin(1/x)$ oscillates, but the $x^2$ factor forces the product to $0$."}, {"id": "B", "text": "1", "explanation": "There is no reason the product should approach $1$; the factor $x^2$ tends to $0$."}, {"id": "C", "text": "0", "explanation": "Since $-1\\le \\sin(1/x)\\le 1$, we have $-x^2\\le x^2\\sin(1/x)\\le x^2$, and both bounds go to $0$."}, {"id": "D", "text": "$-1$", "explanation": "The expression is not trapped near $-1$; the amplitude shrinks to $0$."}]', 'C', 'Because $-1\le \sin(1/x)\le 1$, multiplying by $x^2\ge 0$ gives
$$-x^2\le x^2\sin(1/x)\le x^2.$$ 
As $x\to 0$, both $-x^2$ and $x^2$ go to $0$, so by the Squeeze Theorem the limit is $0$.', '[{"option_id": "A", "text": "Ignored shrinking amplitude."}, {"option_id": "B", "text": "No justification; wrong scale."}, {"option_id": "C", "text": "Correct squeeze argument to 0."}, {"option_id": "D", "text": "Misread oscillation bounds."}]', ARRAY['Canonical squeeze theorem limit.', 'High-yield oscillation-with-damping structure.']::text[], 'published', 1, 3, 1.2, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.8 Determining limits using the Squeeze Theorem.', 1.0, 0.0, 'UT1-Q08-SqueezeOscillation', 'text', 'SqueezeTheorem', ARRAY[]::text[], NOW(), NOW());

-- Question: UT1-Q09-ChooseXValues
DELETE FROM public.questions WHERE title = 'UT1-Q09-ChooseXValues';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 3, 105, ARRAY['StrategySelection', 'GraphicalLimit', 'NumericalLimit']::text[], ARRAY['DirectionConfusion', 'OneSidedVsTwoSided']::text[], 'A student wants to estimate $\lim_{x\to 1} f(x)$.

Which set of $x$-values is most appropriate for a numerical estimate of the limit?', '$$\lim_{x\to 1} f(x)$$', '[{"id": "A", "text": "$x=0.5,\\ 0.6,\\ 0.7,\\ 0.8$", "explanation": "These values approach $1$ only from the left and are not very close."}, {"id": "B", "text": "$x=1,\\ 1,\\ 1,\\ 1$", "explanation": "A limit is about nearby values; repeatedly using $x=1$ does not estimate approach behavior."}, {"id": "C", "text": "$x=1.1,\\ 1.2,\\ 1.3,\\ 1.4$", "explanation": "These values approach $1$ only from the right and are not very close."}, {"id": "D", "text": "$x=0.9,\\ 0.99,\\ 0.999,\\ 1.001,\\ 1.01,\\ 1.1$", "explanation": "These values approach $1$ from both sides and get progressively closer to $1$."}]', 'D', 'To estimate a two-sided limit numerically, choose $x$-values that approach the target from both sides and get very close without being exactly equal to the target. Option D satisfies this.', '[{"option_id": "A", "text": "Left side only; not close enough."}, {"option_id": "B", "text": "Uses only the point, not approach."}, {"option_id": "C", "text": "Right side only; not close enough."}, {"option_id": "D", "text": "Both sides, increasingly close."}]', ARRAY['Directly tests strategy selection for numerical limits.', 'Targets a common misconception: plugging in the point.']::text[], 'published', 1, 2, 1.05, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.9 Connecting multiple representations of limits (appropriate numerical sampling near a point).', 0.7, 0.30000000000000004, 'UT1-Q09-ChooseXValues', 'text', 'StrategySelection', ARRAY['NumericalLimit', 'GraphicalLimit']::text[], NOW(), NOW());

-- Question: UT1-Q10-DiscontinuityGraph
DELETE FROM public.questions WHERE title = 'UT1-Q10-DiscontinuityGraph';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 3, 120, ARRAY['DiscontinuityClassification', 'GraphicalLimit']::text[], ARRAY['OneSidedVsTwoSided', 'ContinuityConditionOmitted']::text[], 'Use the graph provided.

At $x=1$, what type of discontinuity does $h(x)$ have?

(See image.)', '$$\text{Type of discontinuity at }x=1$$', '[{"id": "A", "text": "Removable discontinuity", "explanation": "The left- and right-hand limits are not equal, so it is not removable."}, {"id": "B", "text": "Jump discontinuity", "explanation": "Left-hand limit is $2$ (open circle), right-hand limit is $3$ (horizontal segment), so limits differ."}, {"id": "C", "text": "Infinite discontinuity", "explanation": "There is no vertical asymptote behavior here."}, {"id": "D", "text": "No discontinuity (continuous)", "explanation": "Continuity would require both one-sided limits match and equal $h(1)$."}]', 'B', 'From the graph, as $x\to 1^-$, $h(x)\to 2$ (open circle). As $x\to 1^+$, $h(x)\to 3$ (right-hand constant segment). Since the one-sided limits are finite but unequal, the discontinuity is a jump discontinuity.', '[{"option_id": "A", "text": "Would require equal one-sided limits."}, {"option_id": "B", "text": "Correct: finite but unequal one-sided limits."}, {"option_id": "C", "text": "No unbounded behavior shown."}, {"option_id": "D", "text": "Graph shows mismatch at $x=1$."}]', ARRAY['High-frequency classification task from a graph.', 'Reinforces one-sided limits as the criterion for jump.']::text[], 'published', 1, 2, 1.1, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.10 Exploring types of discontinuities (graph-based classification).', 0.8, 0.2, 'UT1-Q10-DiscontinuityGraph', 'text_and_image', 'DiscontinuityClassification', ARRAY['GraphicalLimit']::text[], NOW(), NOW());

-- Question: UT1-Q11-ContinuityConditions
DELETE FROM public.questions WHERE title = 'UT1-Q11-ContinuityConditions';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 3, 125, ARRAY['ContinuityAtPoint', 'LimitNotation']::text[], ARRAY['ContinuityConditionOmitted', 'NotationMisread']::text[], 'Which condition is NOT required for $f$ to be continuous at $x=a$?', '$$\text{Continuity at }x=a$$', '[{"id": "A", "text": "$f(a)$ is defined", "explanation": "This is required."}, {"id": "B", "text": "$\\lim_{x\\to a} f(x)$ exists", "explanation": "This is required."}, {"id": "C", "text": "$\\lim_{x\\to a} f(x)=f(a)$", "explanation": "This is required."}, {"id": "D", "text": "$f''(a)$ exists", "explanation": "Differentiability is stronger than continuity; it is not required for continuity."}]', 'D', 'Continuity at $x=a$ requires: (1) $f(a)$ exists, (2) $\lim_{x\to a}f(x)$ exists, and (3) the limit equals the function value. Differentiability is not required.', '[{"option_id": "A", "text": "Required part of definition."}, {"option_id": "B", "text": "Required part of definition."}, {"option_id": "C", "text": "Required equality condition."}, {"option_id": "D", "text": "Not required; differentiability is stronger."}]', ARRAY['Definition-level mastery check for continuity.', 'Targets the common confusion: continuity vs differentiability.']::text[], 'published', 1, 1, 1.0, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.11 Defining continuity at a point (definition/conditions).', 1.0, 0.0, 'UT1-Q11-ContinuityConditions', 'text', 'ContinuityAtPoint', ARRAY[]::text[], NOW(), NOW());

-- Question: UT1-Q12-ContinuityInterval
DELETE FROM public.questions WHERE title = 'UT1-Q12-ContinuityInterval';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 4, 150, ARRAY['ContinuityOnInterval', 'ContinuityAtPoint', 'DiscontinuityClassification']::text[], ARRAY['EndpointAssumption', 'ContinuityConditionOmitted']::text[], 'Let
$$f(x)=\frac{1}{x-3}.$$ 
On which interval is $f$ continuous?', '$$f(x)=\frac{1}{x-3}$$', '[{"id": "A", "text": "$(-\\infty,\\infty)$", "explanation": "The function is undefined at $x=3$."}, {"id": "B", "text": "$(-\\infty,3]$", "explanation": "Including $3$ is invalid because $f(3)$ is undefined."}, {"id": "C", "text": "$(-\\infty,3)\\cup(3,\\infty)$", "explanation": "Rational functions are continuous on their domains; exclude $x=3$."}, {"id": "D", "text": "$[3,\\infty)$", "explanation": "This includes $x=3$ where the function is undefined."}]', 'C', 'A rational function is continuous wherever its denominator is nonzero. Here $x-3\ne 0\Rightarrow x\ne 3$, so $f$ is continuous on $(-\infty,3)\cup(3,\infty)$.', '[{"option_id": "A", "text": "Forgot domain restriction."}, {"option_id": "B", "text": "Included the excluded point 3."}, {"option_id": "C", "text": "Correct: continuous on its domain."}, {"option_id": "D", "text": "Includes 3 where undefined."}]', ARRAY['Tests continuity over intervals via domain analysis.', 'Targets endpoint inclusion mistakes.']::text[], 'published', 1, 2, 1.15, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.12 Confirming continuity over an interval (domain-based continuity).', 0.8, 0.2, 'UT1-Q12-ContinuityInterval', 'text', 'ContinuityOnInterval', ARRAY['DiscontinuityClassification']::text[], NOW(), NOW());

-- Question: UT1-Q13-FixRemovableDiscontinuity
DELETE FROM public.questions WHERE title = 'UT1-Q13-FixRemovableDiscontinuity';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 4, 150, ARRAY['RemoveRemovableDiscontinuity', 'AlgebraicLimit', 'ContinuityAtPoint']::text[], ARRAY['AlgebraicCancelError', 'ContinuityConditionOmitted']::text[], 'Find the value of $k$ that makes $f$ continuous at $x=2$.

$$f(x)=\begin{cases}
\frac{x^2-4}{x-2},& x\ne 2\\
k,& x=2
\end{cases}$$', '$$f(x)=\begin{cases}\frac{x^2-4}{x-2},& x\ne 2\\k,& x=2\end{cases}$$', '[{"id": "A", "text": "0", "explanation": "Continuity requires $k$ equal the limit, not the numerator value."}, {"id": "B", "text": "4", "explanation": "Simplify gives $x+2$, so the limit at $2$ is $4$."}, {"id": "C", "text": "2", "explanation": "This is the approach value, not the limit value."}, {"id": "D", "text": "Does not exist", "explanation": "The limit exists; you can define $k$ to match it."}]', 'B', 'For $x\ne 2$,
$$\frac{x^2-4}{x-2}=\frac{(x-2)(x+2)}{x-2}=x+2.$$
Thus
$$\lim_{x\to 2}f(x)=\lim_{x\to 2}(x+2)=4.$$
Continuity at $x=2$ requires $k=4$.', '[{"option_id": "A", "text": "Used numerator at 2, not the limit."}, {"option_id": "B", "text": "Correct: set value equal to limit 4."}, {"option_id": "C", "text": "Confused $x$ with $f(x)$."}, {"option_id": "D", "text": "Limit exists after simplification."}]', ARRAY['Classic removable discontinuity ‘repair’ problem.', 'Links algebraic limits to continuity definition.']::text[], 'published', 1, 3, 1.2, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.13 Removing discontinuities (define a point value to make continuous).', 0.7, 0.30000000000000004, 'UT1-Q13-FixRemovableDiscontinuity', 'text', 'RemoveRemovableDiscontinuity', ARRAY['AlgebraicLimit', 'ContinuityAtPoint']::text[], NOW(), NOW());

-- Question: UT1-Q14-InfiniteLimitSquareDenom
DELETE FROM public.questions WHERE title = 'UT1-Q14-InfiniteLimitSquareDenom';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 3, 110, ARRAY['InfiniteLimitsVerticalAsymptotes', 'GraphicalLimit']::text[], ARRAY['AsymptoteMisread', 'OneSidedVsTwoSided']::text[], 'Let
$$f(x)=\frac{5}{(x-4)^2}.$$ 
Evaluate
$$\lim_{x\to 4} f(x).$$', '$$\lim_{x\to 4}\frac{5}{(x-4)^2}$$', '[{"id": "A", "text": "0", "explanation": "The denominator goes to $0$, so the fraction does not go to $0$."}, {"id": "B", "text": "$-\\infty$", "explanation": "$(x-4)^2\\ge 0$, so the expression is nonnegative near $4$."}, {"id": "C", "text": "Does not exist", "explanation": "The expression grows without bound in the same direction from both sides, so the limit is $+\\infty$."}, {"id": "D", "text": "$+\\infty$", "explanation": "As $x\\to 4$, $(x-4)^2\\to 0^+$, so $\\frac{5}{(x-4)^2}\\to +\\infty$."}]', 'D', 'Because $(x-4)^2\to 0^+$ as $x\to 4$ and the numerator is positive, the quotient increases without bound:
$$\lim_{x\to 4}\frac{5}{(x-4)^2}=+\infty.$$', '[{"option_id": "A", "text": "Denominator to 0 does not imply 0."}, {"option_id": "B", "text": "Square keeps denominator nonnegative."}, {"option_id": "C", "text": "Unbounded same-direction behavior is $+\\infty$."}, {"option_id": "D", "text": "Correct infinite limit."}]', ARRAY['Tests recognizing vertical asymptote behavior from algebraic form.', 'Targets sign reasoning with squared denominators.']::text[], 'published', 1, 2, 1.05, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.14 Connecting infinite limits and vertical asymptotes.', 0.85, 0.15, 'UT1-Q14-InfiniteLimitSquareDenom', 'text', 'InfiniteLimitsVerticalAsymptotes', ARRAY['GraphicalLimit']::text[], NOW(), NOW());

-- Question: UT1-Q15-RationalInfinityEqualDegree
DELETE FROM public.questions WHERE title = 'UT1-Q15-RationalInfinityEqualDegree';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 3, 115, ARRAY['LimitsAtInfinityHorizontalAsymptotes', 'LimitLaws']::text[], ARRAY['InfinityArithmetic', 'NotationMisread']::text[], 'Evaluate the limit.

$$\lim_{x\to \infty}\frac{3x^2-7}{2x^2+5x}$$', '$$\lim_{x\to \infty}\frac{3x^2-7}{2x^2+5x}$$', '[{"id": "A", "text": "$\\frac{3}{2}$", "explanation": "Divide numerator and denominator by $x^2$; leading coefficients give $\\frac{3}{2}$."}, {"id": "B", "text": "$\\frac{3}{5}$", "explanation": "Incorrectly compared $3x^2$ to $5x$ instead of the highest powers."}, {"id": "C", "text": "0", "explanation": "For equal degrees, the limit is not $0$; it is the ratio of leading coefficients."}, {"id": "D", "text": "$\\infty$", "explanation": "Degrees are equal, so the fraction approaches a constant, not infinity."}]', 'A', 'Divide by the highest power $x^2$:
$$\frac{3-7/x^2}{2+5/x} \xrightarrow[x\to\infty]{} \frac{3}{2}.$$', '[{"option_id": "A", "text": "Correct leading-coefficient ratio."}, {"option_id": "B", "text": "Compared wrong terms."}, {"option_id": "C", "text": "Equal degrees do not go to 0."}, {"option_id": "D", "text": "Equal degrees do not blow up."}]', ARRAY['Core end-behavior limit for rational functions.', 'Supports horizontal asymptote identification.']::text[], 'published', 1, 2, 1.1, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.15 Limits at infinity and horizontal asymptotes (equal degrees).', 0.9, 0.1, 'UT1-Q15-RationalInfinityEqualDegree', 'text', 'LimitsAtInfinityHorizontalAsymptotes', ARRAY['LimitLaws']::text[], NOW(), NOW());

-- Question: UT1-Q16-IVTMustTrue
DELETE FROM public.questions WHERE title = 'UT1-Q16-IVTMustTrue';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 5, 170, ARRAY['IVTApplication', 'ContinuityOnInterval']::text[], ARRAY['IVTMisapply', 'EndpointAssumption']::text[], 'Suppose $f$ is continuous on $[1,5]$, with $f(1)=-2$ and $f(5)=4$. Which statement must be true?', '$$f\text{ continuous on }[1,5],\ f(1)=-2,\ f(5)=4$$', '[{"id": "A", "text": "There exists $c$ in $(1,5)$ such that $f(c)=0$ and $f''(c)$ exists.", "explanation": "IVT guarantees a zero, but says nothing about differentiability."}, {"id": "B", "text": "There exists $c$ in $(1,5)$ such that $f(c)=1$ and $f$ is increasing on $[1,5]$.", "explanation": "IVT can guarantee $f(c)=1$, but not monotonicity."}, {"id": "C", "text": "There exists $c$ in $(1,5)$ such that $f(c)=0$.", "explanation": "Since $0$ lies between $-2$ and $4$, IVT guarantees a point where $f(c)=0$."}, {"id": "D", "text": "There exists $c$ in $(1,5)$ such that $f(c)=6$.", "explanation": "IVT only guarantees values between $f(1)$ and $f(5)$; $6$ is not between $-2$ and $4$."}]', 'C', 'By the Intermediate Value Theorem, if $f$ is continuous on $[1,5]$, then for any value $L$ between $f(1)=-2$ and $f(5)=4$, there exists $c\in(1,5)$ with $f(c)=L$. Since $0$ is between $-2$ and $4$, such a $c$ must exist.', '[{"option_id": "A", "text": "Adds differentiability, not implied."}, {"option_id": "B", "text": "Adds monotonicity, not implied."}, {"option_id": "C", "text": "Correct IVT conclusion for 0."}, {"option_id": "D", "text": "6 is outside the guaranteed range."}]', ARRAY['High-discrimination IVT question with tempting extra claims.', 'Reinforces what IVT does and does not guarantee.']::text[], 'published', 1, 3, 1.25, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.16 Working with the Intermediate Value Theorem (must-true statements).', 0.85, 0.15, 'UT1-Q16-IVTMustTrue', 'text', 'IVTApplication', ARRAY['ContinuityOnInterval']::text[], NOW(), NOW());

-- Question: UT1-Q17-RemovableFromOneSided
DELETE FROM public.questions WHERE title = 'UT1-Q17-RemovableFromOneSided';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 4, 145, ARRAY['DiscontinuityClassification', 'ContinuityAtPoint']::text[], ARRAY['ContinuityConditionOmitted', 'OneSidedVsTwoSided']::text[], 'For a function $f$, suppose
$$\lim_{x\to 2^-} f(x)=5\quad\text{and}\quad\lim_{x\to 2^+} f(x)=5,$$
but $f(2)$ is undefined.

Which statement is true?', '$$\lim_{x\to 2^-} f(x)=5,\ \lim_{x\to 2^+} f(x)=5,\ f(2)\text{ undefined}$$', '[{"id": "A", "text": "$\\lim_{x\\to 2} f(x)$ does not exist.", "explanation": "If both one-sided limits exist and are equal, the two-sided limit exists."}, {"id": "B", "text": "$f$ is continuous at $x=2$.", "explanation": "Continuity requires $f(2)$ be defined and equal to the limit."}, {"id": "C", "text": "$x=2$ is a jump discontinuity.", "explanation": "Jump requires unequal one-sided limits."}, {"id": "D", "text": "$\\lim_{x\\to 2} f(x)=5$ and the discontinuity is removable.", "explanation": "The two-sided limit exists (equals 5) but the function value is missing; defining $f(2)=5$ would make it continuous."}]', 'D', 'Since $\lim_{x\to 2^-}f(x)=\lim_{x\to 2^+}f(x)=5$, the two-sided limit exists and equals $5$. Because $f(2)$ is undefined, $f$ is not continuous at $2$, but the discontinuity is removable: defining $f(2)=5$ would restore continuity.', '[{"option_id": "A", "text": "Equal one-sided limits imply limit exists."}, {"option_id": "B", "text": "Continuity requires defined value."}, {"option_id": "C", "text": "Jump requires mismatch."}, {"option_id": "D", "text": "Correct: removable with limit 5."}]', ARRAY['Connects one-sided limits to two-sided limit existence.', 'Reinforces removable discontinuity definition.']::text[], 'published', 1, 3, 1.2, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.10–1.13 Discontinuities + continuity at a point (removable via defining value).', 0.7, 0.3, 'UT1-Q17-RemovableFromOneSided', 'text', 'DiscontinuityClassification', ARRAY['ContinuityAtPoint']::text[], NOW(), NOW());

-- Question: UT1-Q18-IVTGraph
DELETE FROM public.questions WHERE title = 'UT1-Q18-IVTGraph';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 4, 155, ARRAY['IVTApplication', 'GraphicalLimit', 'ContinuityOnInterval']::text[], ARRAY['IVTMisapply', 'EndpointAssumption']::text[], 'Use the graph provided.

The function $p(x)$ is continuous on $[0,3]$. Based on the graph, which value is guaranteed to be attained by $p(x)$ for some $c\in(0,3)$?

(See image.)', '$$p\text{ continuous on }[0,3]$$', '[{"id": "A", "text": "$-2$", "explanation": "The graph shows $p(x)$ stays above about $-1$ on $[0,3]$."}, {"id": "B", "text": "0", "explanation": "From the graph, $p(0)<0$ and $p(3)>0$, so by IVT there is a point where $p(c)=0$."}, {"id": "C", "text": "6", "explanation": "The graph\u2019s endpoint values do not bracket 6, so IVT does not guarantee it."}, {"id": "D", "text": "There is not enough information to guarantee any value.", "explanation": "Continuity plus endpoint values does guarantee intermediate values."}]', 'B', 'Because $p$ is continuous on $[0,3]$, it satisfies IVT. The graph indicates $p(0)$ is negative while $p(3)$ is positive, so $0$ lies between them. Therefore there must exist $c\in(0,3)$ such that $p(c)=0$.', '[{"option_id": "A", "text": "Not supported by the shown range."}, {"option_id": "B", "text": "Correct: sign change guarantees a root."}, {"option_id": "C", "text": "Not bracketed by endpoint values."}, {"option_id": "D", "text": "IVT guarantees intermediate values."}]', ARRAY['Graph-based IVT application with sign change.', 'Targets the misconception that IVT needs a formula.']::text[], 'published', 1, 3, 1.2, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.16 IVT using a graph (guaranteed intermediate value).', 0.8, 0.2, 'UT1-Q18-IVTGraph', 'text_and_image', 'IVTApplication', ARRAY['ContinuityOnInterval']::text[], NOW(), NOW());

-- Question: UT1-Q19-TwoSidedFromOneSided
DELETE FROM public.questions WHERE title = 'UT1-Q19-TwoSidedFromOneSided';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 2, 80, ARRAY['LimitNotation', 'GraphicalLimit']::text[], ARRAY['OneSidedVsTwoSided', 'DirectionConfusion']::text[], 'If
$$\lim_{x\to 4^-} f(x)=2\quad\text{and}\quad\lim_{x\to 4^+} f(x)=2,$$
then what is
$$\lim_{x\to 4} f(x)?$$', '$$\lim_{x\to 4^-} f(x)=2,\ \lim_{x\to 4^+} f(x)=2$$', '[{"id": "A", "text": "Does not exist", "explanation": "Equal one-sided limits imply the two-sided limit exists."}, {"id": "B", "text": "$4$", "explanation": "Confused the approach value $4$ with the limit value."}, {"id": "C", "text": "$2$", "explanation": "When left- and right-hand limits exist and are equal, the two-sided limit equals that common value."}, {"id": "D", "text": "Cannot be determined without knowing $f(4)$", "explanation": "The limit can be determined from one-sided limits even if $f(4)$ is unknown."}]', 'C', 'Because the one-sided limits exist and are equal to the same number, the two-sided limit exists and equals that number:
$$\lim_{x\to 4} f(x)=2.$$', '[{"option_id": "A", "text": "Mismatch would be needed for DNE."}, {"option_id": "B", "text": "Approach value is not the limit value."}, {"option_id": "C", "text": "Correct: common one-sided value."}, {"option_id": "D", "text": "Limit does not require knowing $f(4)$."}]', ARRAY['Fast check of the two-sided limit definition.', 'Targets common confusion about needing $f(a)$.']::text[], 'published', 1, 1, 0.95, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.2 limit notation + two-sided limit definition via one-sided limits.', 0.9, 0.1, 'UT1-Q19-TwoSidedFromOneSided', 'text', 'LimitNotation', ARRAY['GraphicalLimit']::text[], NOW(), NOW());

-- Question: UT1-Q20-OneSidedInfiniteFromDomain
DELETE FROM public.questions WHERE title = 'UT1-Q20-OneSidedInfiniteFromDomain';
INSERT INTO public.questions (course, topic, sub_topic_id, section_id, type, calculator_allowed, difficulty, target_time_seconds, skill_tags, error_tags, prompt, latex, options, correct_option_id, explanation, micro_explanations, recommendation_reasons, status, version, reasoning_level, mastery_weight, representation_type, source, source_year, notes, weight_primary, weight_supporting, title, prompt_type, primary_skill_id, supporting_skill_ids, updated_at, created_at)
VALUES ('Both', 'Both_Limits', 'unit_test', 'unit_test', 'MCQ', FALSE, 4, 135, ARRAY['StrategySelection', 'LimitLaws', 'DiscontinuityClassification']::text[], ARRAY['AsymptoteMisread', 'AlgebraicCancelError']::text[], 'Consider
$$f(x)=\frac{x-5}{\sqrt{x-1}}.$$ 
Which statement about $\lim_{x\to 1^+} f(x)$ is true?', '$$f(x)=\frac{x-5}{\sqrt{x-1}}$$', '[{"id": "A", "text": "The limit is $-\\infty$.", "explanation": "As $x\\to 1^+$, numerator $x-5\\to -4$ (negative) and denominator $\\sqrt{x-1}\\to 0^+$, so the quotient decreases without bound."}, {"id": "B", "text": "The limit is $+\\infty$.", "explanation": "The denominator tends to $0^+$, but the numerator tends to a negative number, so the quotient goes to $-\\infty$."}, {"id": "C", "text": "The limit is $-4$.", "explanation": "This treats the denominator as approaching 1 instead of 0."}, {"id": "D", "text": "The limit does not exist because $x=1$ is not in the domain.", "explanation": "A limit can exist even if the function is not defined at the point; here the one-sided limit is infinite."}]', 'A', 'We consider the right-hand approach since the domain requires $x\ge 1$. As $x\to 1^+$,
$$x-5\to -4<0,\quad \sqrt{x-1}\to 0^+.$$ 
A negative constant divided by a positive number approaching $0$ tends to $-\infty$. Therefore,
$$\lim_{x\to 1^+}\frac{x-5}{\sqrt{x-1}}=-\infty.$$', '[{"option_id": "A", "text": "Correct sign + denominator to $0^+$."}, {"option_id": "B", "text": "Sign error: numerator is negative."}, {"option_id": "C", "text": "Ignored denominator behavior to 0."}, {"option_id": "D", "text": "Limit may exist even if value undefined."}]', ARRAY['Forces one-sided domain reasoning with radicals.', 'Tests sign analysis for infinite one-sided limits.']::text[], 'published', 1, 3, 1.2, 'symbolic', 'NewMaoS Unit 1: Limits and Continuity — Unit Test', 2026, 'Focus: 1.7 strategy selection + one-sided limits from domain restrictions; infinite behavior.', 0.75, 0.25, 'UT1-Q20-OneSidedInfiniteFromDomain', 'text', 'StrategySelection', ARRAY['DiscontinuityClassification', 'LimitLaws']::text[], NOW(), NOW());
COMMIT;
