-- Unit 3.1 (The Chain Rule) — Practice 1–5

UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.1',
  section_id = '3.1',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 90,
  skill_tags = ARRAY['SK_CHAIN_RULE','SK_POWER_RULE','SK_EXP_LOG_DERIVATIVES'],
  primary_skill_id = 'SK_CHAIN_RULE',
  supporting_skill_ids = ARRAY['SK_POWER_RULE', 'SK_EXP_LOG_DERIVATIVES'],
 'SK_EXP_LOG_DERIVATIVES'],'SK_EXP_LOG_DERIVATIVES'],
  error_tags = ARRAY['E_INNER_OUTER_CONFUSION','E_POWER_RULE'],
  prompt = 'Let $f(x)=e^{(3x^2-5x)^4}$. What is $f''(x)$?',
  latex = 'Let $f(x)=e^{(3x^2-5x)^4}$. What is $f''(x)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$e^{(3x^2-5x)^4}(12x-5)$','explanation','This differentiates the outer $e^{u}$ correctly but misses the factor $4(3x^2-5x)^3$ from $u=(3x^2-5x)^4$.'),
    jsonb_build_object('id','B','text','$4(6x-5)e^{(3x^2-5x)^4}$','explanation','This includes the outer derivative and part of the inner derivative but misses the $(3x^2-5x)^3$ factor.'),
    jsonb_build_object('id','C','text','$4(12x-5)(3x^2-5x)^3e^{(3x^2-5x)^4}$','explanation','This doubles the derivative of $3x^2-5x$ (it should be $6x-5$, not $12x-5$).'),
    jsonb_build_object('id','D','text','$4(6x-5)(3x^2-5x)^3e^{(3x^2-5x)^4}$','explanation','Correct: apply chain rule twice: $(e^{u})''=e^{u}u''$ and $u''=4(3x^2-5x)^3(6x-5)$.')
  ),
  correct_option_id = 'D',
  tolerance = 0.0010,
  explanation = 'Let $u=(3x^2-5x)^4$. Then $f(x)=e^{u}$ so $f''(x)=e^{u}u''$. Also $u''=4(3x^2-5x)^3(6x-5)$. Therefore $$f''(x)=4(6x-5)(3x^2-5x)^3e^{(3x^2-5x)^4}.$$',
  recommendation_reasons = ARRAY['Reinforces multi-layer chain rule structure.','Targets inner/outer identification mistakes.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: nested chain rule with exponential outer function.',
  weight_primary = 0.80,
  weight_supporting = 0.20,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.1-P1';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.1',
  section_id = '3.1',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 110,
  skill_tags = ARRAY['SK_CHAIN_RULE','SK_PRODUCT_RULE','SK_TRIG_DERIVATIVES'],
  primary_skill_id = 'SK_CHAIN_RULE',
  supporting_skill_ids = ARRAY['SK_PRODUCT_RULE', 'SK_TRIG_DERIVATIVES'],
 'SK_TRIG_DERIVATIVES'],'SK_TRIG_DERIVATIVES'],
  error_tags = ARRAY['E_INNER_OUTER_CONFUSION','E_PRODUCT_RULE'],
  prompt = 'Let $g(x)=x^2\\sin(5x^3)$. What is $g''(x)$?',
  latex = 'Let $g(x)=x^2\\sin(5x^3)$. What is $g''(x)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$2x\\sin(5x^3)+15x^4\\cos(5x^3)$','explanation','Correct: product rule gives $2x\\sin(5x^3)+x^2\\cdot\\cos(5x^3)\\cdot 15x^2=2x\\sin(5x^3)+15x^4\\cos(5x^3)$.'),
    jsonb_build_object('id','B','text','$2x\\sin(5x^3)+15x^2\\cos(5x^3)$','explanation','Forgot to multiply the chain-rule term by the extra $x^2$ from the product rule.'),
    jsonb_build_object('id','C','text','$2x\\sin(5x^3)+5x^2\\cos(5x^3)$','explanation','Differentiated $5x^3$ incorrectly; it should contribute a factor $15x^2$.'),
    jsonb_build_object('id','D','text','$2x\\cos(5x^3)+15x^4\\sin(5x^3)$','explanation','Mixed up derivatives of $\\sin$ and $\\cos$ and misapplied product rule.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Use product rule: $g''(x)=(x^2)''\\sin(5x^3)+x^2(\\sin(5x^3))''$. Compute $(x^2)''=2x$ and $(\\sin(5x^3))''=\\cos(5x^3)\\cdot 15x^2$. Thus $$g''(x)=2x\\sin(5x^3)+15x^4\\cos(5x^3).$$',
  recommendation_reasons = ARRAY['Checks product-rule bookkeeping with a nested trig input.','Targets missing factor errors in chain rule.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: product rule with trig composite input.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.1-P2';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.1',
  section_id = '3.1',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 140,
  skill_tags = ARRAY['SK_CHAIN_RULE','SK_TRIG_DERIVATIVES','SK_POWER_RULE'],
  primary_skill_id = 'SK_CHAIN_RULE',
  supporting_skill_ids = ARRAY['SK_TRIG_DERIVATIVES', 'SK_POWER_RULE'],
 'SK_POWER_RULE'],'SK_POWER_RULE'],
  error_tags = ARRAY['E_INNER_OUTER_CONFUSION','E_SIGN_ERROR'],
  prompt = 'If $h(x)=\\left(\\cos(2x-1)\\right)^5$, what is $h''\\!\\left(\\tfrac{\\pi}{2}\\right)$?',
  latex = 'If $h(x)=\\left(\\cos(2x-1)\\right)^5$, what is $h''\\!\\left(\\tfrac{\\pi}{2}\\right)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$0$','explanation','This would require factors to be zero at $x=\\tfrac{\\pi}{2}$; they are not forced to be zero.'),
    jsonb_build_object('id','B','text','$-10\\left(\\cos(\\pi-1)\\right)^4\\sin(\\pi-1)$','explanation','Correct: $h''(x)=5(\\cos(2x-1))^4\\cdot(-\\sin(2x-1))\\cdot 2=-10(\\cos(2x-1))^4\\sin(2x-1)$; substitute $2(\\tfrac{\\pi}{2})-1=\\pi-1$.'),
    jsonb_build_object('id','C','text','$10\\left(\\cos(\\pi-1)\\right)^4\\sin(\\pi-1)$','explanation','Sign error: derivative of $\\cos$ is $-\\sin$, giving an overall negative.'),
    jsonb_build_object('id','D','text','$-5\\left(\\cos(\\pi-1)\\right)^4\\sin(\\pi-1)$','explanation','Missing the factor $2$ from differentiating $2x-1$.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Differentiate: $$h''(x)=5(\\cos(2x-1))^4\\cdot(-\\sin(2x-1))\\cdot 2=-10(\\cos(2x-1))^4\\sin(2x-1).$$ At $x=\\tfrac{\\pi}{2}$, $2x-1=\\pi-1$, so $$h''\\!\\left(\\tfrac{\\pi}{2}\\right)=-10\\left(\\cos(\\pi-1)\\right)^4\\sin(\\pi-1).$$',
  recommendation_reasons = ARRAY['Practices chain rule with evaluation at a point.','Targets missing inner-derivative factor and sign errors.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.20,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: chain rule with trig-power composite and point evaluation.',
  weight_primary = 0.80,
  weight_supporting = 0.20,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.1-P3';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.1',
  section_id = '3.1',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 1,
  target_time_seconds = 70,
  skill_tags = ARRAY['SK_CHAIN_RULE','SK_POWER_RULE'],
  primary_skill_id = 'SK_CHAIN_RULE',
  supporting_skill_ids = ARRAY['SK_POWER_RULE'],

  error_tags = ARRAY['E_INNER_OUTER_CONFUSION','E_SIGN_ERROR'],
  prompt = 'Let $p(x)=(7-4x)^{9}$. What is $p''(x)$?',
  latex = 'Let $p(x)=(7-4x)^{9}$. What is $p''(x)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$9(7-4x)^8$','explanation','Missing the factor $(7-4x)''=-4$.'),
    jsonb_build_object('id','B','text','$-36(7-4x)^8$','explanation','Correct: $p''(x)=9(7-4x)^8\\cdot(-4)=-36(7-4x)^8$.'),
    jsonb_build_object('id','C','text','$36(7-4x)^8$','explanation','Sign error: $(7-4x)''=-4$, not $4$.'),
    jsonb_build_object('id','D','text','$-4(7-4x)^9$','explanation','Did not apply power rule to reduce exponent and multiply by $9$.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Using chain rule: $$p''(x)=9(7-4x)^8\\cdot(7-4x)''=9(7-4x)^8\\cdot(-4)=-36(7-4x)^8.$$',
  recommendation_reasons = ARRAY['Fast check for missing inner derivative.','Builds automatic chain-rule habit.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 1,
  mastery_weight = 0.90,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: chain rule with a linear inner function.',
  weight_primary = 1.00,
  weight_supporting = 0.00,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.1-P4';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.1',
  section_id = '3.1',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 120,
  skill_tags = ARRAY['SK_CHAIN_RULE','SK_EXP_LOG_DERIVATIVES','SK_TRIG_DERIVATIVES'],
  primary_skill_id = 'SK_CHAIN_RULE',
  supporting_skill_ids = ARRAY['SK_EXP_LOG_DERIVATIVES', 'SK_TRIG_DERIVATIVES'],
 'SK_TRIG_DERIVATIVES'],'SK_TRIG_DERIVATIVES'],
  error_tags = ARRAY['E_INNER_OUTER_CONFUSION','E_SIGN_ERROR'],
  prompt = 'Let $q(x)=\\ln\\big(\\sin(x^2+1)\\big)$. Which expression equals $q''(x)$?',
  latex = 'Let $q(x)=\\ln\\big(\\sin(x^2+1)\\big)$. Which expression equals $q''(x)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\dfrac{\\cos(x^2+1)}{\\sin(x^2+1)}$','explanation','Missing the factor $(x^2+1)''=2x$.'),
    jsonb_build_object('id','B','text','$\\dfrac{2x\\cos(x^2+1)}{\\sin(x^2+1)}$','explanation','Correct: $(\\ln u)''=u''/u$ with $u=\\sin(x^2+1)$ and $u''=\\cos(x^2+1)\\cdot 2x$.'),
    jsonb_build_object('id','C','text','$\\dfrac{2x\\sin(x^2+1)}{\\cos(x^2+1)}$','explanation','Inverted ratio; $u''/u$ keeps $\\sin(x^2+1)$ in the denominator.'),
    jsonb_build_object('id','D','text','$\\dfrac{-2x\\cos(x^2+1)}{\\sin(x^2+1)}$','explanation','Sign error: derivative of $\\sin$ is $\\cos$, not $-\\cos$.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Let $u=\\sin(x^2+1)$. Then $q(x)=\\ln u$ so $q''(x)=\\dfrac{u''}{u}$. Also $u''=\\cos(x^2+1)\\cdot 2x$. Thus $$q''(x)=\\frac{2x\\cos(x^2+1)}{\\sin(x^2+1)}.$$',
  recommendation_reasons = ARRAY['Combines log derivative with nested trig.','Targets missing inner derivative and sign errors.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: chain rule through $\\ln$ and $\\sin$ with polynomial inner.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.1-P5';



-- Unit 3.2 (Implicit Differentiation) — Practice 1–5

UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.2',
  section_id = '3.2',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 110,
  skill_tags = ARRAY['SK_IMPLICIT_DIFFERENTIATION','SK_PRODUCT_RULE','SK_ALGEBRA_SOLVE_DYDX'],
  primary_skill_id = 'SK_IMPLICIT_DIFFERENTIATION',
  supporting_skill_ids = ARRAY['SK_PRODUCT_RULE', 'SK_ALGEBRA_SOLVE_DYDX'],
 'SK_ALGEBRA_SOLVE_DYDX'],'SK_ALGEBRA_SOLVE_DYDX'],
  error_tags = ARRAY['E_MISSING_DYDX','E_SOLVE_FOR_DYDX'],
  prompt = 'Given $x^2y+3y=7$, what is $\\dfrac{dy}{dx}$ in terms of $x$ and $y$?',
  latex = 'Given $x^2y+3y=7$, what is $\\dfrac{dy}{dx}$ in terms of $x$ and $y$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$-\\dfrac{2xy}{x^2+3}$','explanation','Correct: $2xy+x^2y''+3y''=0\\Rightarrow (x^2+3)y''=-2xy$.'),
    jsonb_build_object('id','B','text','$-\\dfrac{2x}{x^2+3}$','explanation','Dropped the factor $y$ from differentiating $x^2y$.'),
    jsonb_build_object('id','C','text','$-\\dfrac{2xy}{x^2}$','explanation','Forgot that $3y$ contributes $3y''$ after differentiation.'),
    jsonb_build_object('id','D','text','$\\dfrac{2xy}{x^2+3}$','explanation','Sign error when isolating $y''$.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Differentiate implicitly: $(x^2y)''+(3y)''=0$. Product rule gives $2xy+x^2y''$, and $(3y)''=3y''$. Thus $2xy+(x^2+3)y''=0$, so $$\\frac{dy}{dx}=y''=-\\frac{2xy}{x^2+3}.$$',
  recommendation_reasons = ARRAY['Core implicit differentiation pattern.','Targets missing $dy/dx$ and algebra isolation errors.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: product rule inside implicit differentiation, then solve for $dy/dx$.',
  weight_primary = 0.80,
  weight_supporting = 0.20,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.2-P1';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.2',
  section_id = '3.2',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 130,
  skill_tags = ARRAY['SK_IMPLICIT_DIFFERENTIATION','SK_TRIG_DERIVATIVES','SK_ALGEBRA_SOLVE_DYDX'],
  primary_skill_id = 'SK_IMPLICIT_DIFFERENTIATION',
  supporting_skill_ids = ARRAY['SK_TRIG_DERIVATIVES', 'SK_ALGEBRA_SOLVE_DYDX'],
 'SK_ALGEBRA_SOLVE_DYDX'],'SK_ALGEBRA_SOLVE_DYDX'],
  error_tags = ARRAY['E_MISSING_DYDX','E_SOLVE_FOR_DYDX'],
  prompt = 'If $\\sin(xy)=x$, what is $\\dfrac{dy}{dx}$?',
  latex = 'If $\\sin(xy)=x$, what is $\\dfrac{dy}{dx}$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\dfrac{1-y\\cos(xy)}{x\\cos(xy)}$','explanation','Correct: $\\cos(xy)(y+xy'')=1\\Rightarrow xy''\\cos(xy)=1-y\\cos(xy)$.'),
    jsonb_build_object('id','B','text','$\\dfrac{y\\cos(xy)-1}{x\\cos(xy)}$','explanation','Sign error when moving terms to isolate $y''$.'),
    jsonb_build_object('id','C','text','$\\dfrac{1-y\\cos(xy)}{\\cos(xy)}$','explanation','Forgot to divide by $x$ when isolating $y''$.'),
    jsonb_build_object('id','D','text','$\\dfrac{1-y\\sin(xy)}{x\\cos(xy)}$','explanation','Differentiated $\\sin(xy)$ incorrectly; derivative is $\\cos(xy)\\cdot (xy)''$.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Differentiate: $(\\sin(xy))''=\\cos(xy)\\cdot(xy)''=1$. Since $(xy)''=y+xy''$, we have $(y+xy'')\\cos(xy)=1$. Thus $$y''=\\frac{1-y\\cos(xy)}{x\\cos(xy)}.$$',
  recommendation_reasons = ARRAY['High-frequency implicit + trig composite.','Targets missing $(xy)''$ structure and solve-for-$dy/dx$ mistakes.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.20,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: chain rule + product rule within an implicit trig equation.',
  weight_primary = 0.80,
  weight_supporting = 0.20,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.2-P2';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.2',
  section_id = '3.2',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 160,
  skill_tags = ARRAY['SK_IMPLICIT_DIFFERENTIATION','SK_SECOND_DERIVATIVE','SK_ALGEBRA_SOLVE_DYDX'],
  primary_skill_id = 'SK_IMPLICIT_DIFFERENTIATION',
  supporting_skill_ids = ARRAY['SK_SECOND_DERIVATIVE', 'SK_ALGEBRA_SOLVE_DYDX'],
 'SK_ALGEBRA_SOLVE_DYDX'],'SK_ALGEBRA_SOLVE_DYDX'],
  error_tags = ARRAY['E_MISSING_DYDX','E_SOLVE_FOR_DYDX'],
  prompt = 'The curve is defined implicitly by $x^2+y^2=25$. What is $\\dfrac{d^2y}{dx^2}$ at the point $(3,4)$?',
  latex = 'The curve is defined implicitly by $x^2+y^2=25$. What is $\\dfrac{d^2y}{dx^2}$ at the point $(3,4)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$-\\dfrac{25}{64}$','explanation','Correct: computing $y''$ from $y''=-x/y$ and differentiating again gives $y''''=-1/y+(xy'')/y^2$; substituting $(3,4)$ yields $-25/64$.'),
    jsonb_build_object('id','B','text','$\\dfrac{25}{64}$','explanation','Sign error; the computed $y''''$ at $(3,4)$ is negative.'),
    jsonb_build_object('id','C','text','$-\\dfrac{3}{4}$','explanation','This is $y''$ (the first derivative) at $(3,4)$, not $y''''$.'),
    jsonb_build_object('id','D','text','$-\\dfrac{4}{3}$','explanation','Reciprocal slope mistake; from $2x+2yy''=0$, $y''=-x/y$.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Differentiate $x^2+y^2=25$: $2x+2yy''=0\\Rightarrow y''=-\\dfrac{x}{y}$. Differentiate $y''=-xy^{-1}$: $$y''''=-(y^{-1}+x(-1)y^{-2}y'')=-\\frac{1}{y}+\\frac{xy''}{y^2}.$$ At $(3,4)$, $y''=-\\dfrac{3}{4}$, so $$y''''=-\\frac{1}{4}+\\frac{3(-3/4)}{16}=-\\frac{1}{4}-\\frac{9}{64}=-\\frac{25}{64}.$$',
  recommendation_reasons = ARRAY['Classic AP-style second derivative from an implicit curve.','Builds discipline carrying $dy/dx$ into $d^2y/dx^2$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 5,
  mastery_weight = 1.30,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: compute $d^2y/dx^2$ from an implicit relation and evaluate at a point.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.2-P3';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.2',
  section_id = '3.2',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 120,
  skill_tags = ARRAY['SK_IMPLICIT_DIFFERENTIATION','SK_TANGENT_LINE','SK_ALGEBRA_SOLVE_DYDX'],
  primary_skill_id = 'SK_IMPLICIT_DIFFERENTIATION',
  supporting_skill_ids = ARRAY['SK_TANGENT_LINE', 'SK_ALGEBRA_SOLVE_DYDX'],
 'SK_ALGEBRA_SOLVE_DYDX'],'SK_ALGEBRA_SOLVE_DYDX'],
  error_tags = ARRAY['E_MISSING_DYDX','E_SIGN_ERROR'],
  prompt = 'The curve is given by $x^3+y^3=16$. What is the slope of the tangent line at $(2,2)$?',
  latex = 'The curve is given by $x^3+y^3=16$. What is the slope of the tangent line at $(2,2)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$-1$','explanation','Correct: $3x^2+3y^2y''=0\\Rightarrow y''=-x^2/y^2$, so at $(2,2)$ it is $-4/4=-1$.'),
    jsonb_build_object('id','B','text','$1$','explanation','Sign error when solving for $dy/dx$.'),
    jsonb_build_object('id','C','text','$-\\dfrac{2}{3}$','explanation','Power rule applied incorrectly to $y^3$; it should give $3y^2y''$.'),
    jsonb_build_object('id','D','text','$-\\dfrac{4}{3}$','explanation','Kept a factor of $3$ in one term but not the other; the 3s cancel before substituting.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Differentiate: $3x^2+3y^2y''=0$. Solve: $y''=-\\dfrac{x^2}{y^2}$. At $(2,2)$, $$\\frac{dy}{dx}=-\\frac{4}{4}=-1.$$',
  recommendation_reasons = ARRAY['Direct slope-at-a-point implicit question.','Targets forgetting the $dy/dx$ factor on $y$-terms.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: tangent slope from implicit differentiation at a point.',
  weight_primary = 0.80,
  weight_supporting = 0.20,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.2-P4';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_Composite',
  sub_topic_id = '3.2',
  section_id = '3.2',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_IMPLICIT_DIFFERENTIATION','SK_CHAIN_RULE','SK_ALGEBRA_SOLVE_DYDX'],
  primary_skill_id = 'SK_IMPLICIT_DIFFERENTIATION',
  supporting_skill_ids = ARRAY['SK_CHAIN_RULE', 'SK_ALGEBRA_SOLVE_DYDX'],
 'SK_ALGEBRA_SOLVE_DYDX'],'SK_ALGEBRA_SOLVE_DYDX'],
  error_tags = ARRAY['E_MISSING_DYDX','E_PRODUCT_RULE'],
  prompt = 'Given $e^{y}=x^2+xy$, what is $\\dfrac{dy}{dx}$?',
  latex = 'Given $e^{y}=x^2+xy$, what is $\\dfrac{dy}{dx}$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\dfrac{2x+y}{e^{y}-x}$','explanation','Correct: $e^{y}y''=2x+(xy)''=2x+y+xy''$, so $(e^{y}-x)y''=2x+y$.'),
    jsonb_build_object('id','B','text','$\\dfrac{2x+y}{e^{y}+x}$','explanation','Sign error when moving $xy''$ to the left side.'),
    jsonb_build_object('id','C','text','$\\dfrac{2x+y}{e^{y}}$','explanation','Forgot the $xy''$ term from differentiating $xy$.'),
    jsonb_build_object('id','D','text','$\\dfrac{2x+xy}{e^{y}-x}$','explanation','Differentiated $xy$ incorrectly; $(xy)''=y+xy''$.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Differentiate: $(e^{y})''=e^{y}y''$. RHS: $(x^2)''=2x$ and $(xy)''=y+xy''$. So $$e^{y}y''=2x+y+xy''.$$ Then $(e^{y}-x)y''=2x+y$, hence $$\\frac{dy}{dx}=\\frac{2x+y}{e^{y}-x}.$$',
  recommendation_reasons = ARRAY['Mixes implicit differentiation with chain rule on $e^{y}$.','Targets missing product-rule term and missing $dy/dx$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: implicit differentiation with an exponential in $y$ and a product term.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_Composite',
  updated_at = NOW()
WHERE title = '3.2-P5';
