-- Unit 7 (Differential Equations) — Unit Test (20 MCQ)

BEGIN;

UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 105,
  skill_tags = ARRAY['SK_MODELING_DE','SK_EXPONENTIAL_MODEL','SK_SOLVE_PARAMETER','SK_APPLY_INITIAL_CONDITION'],
  error_tags = ARRAY['E_ALGEBRA_SLIP','E_LOG_MISTAKE','E_UNITS_INTERPRETATION'],
  prompt = 'A population $P(t)$ (in bacteria) satisfies $\dfrac{dP}{dt}=kP$ for a constant $k$. If $P(0)=500$ and $P(2)=800$, which value of $k$ is correct?',
  latex = 'A population $P(t)$ (in bacteria) satisfies $\dfrac{dP}{dt}=kP$ for a constant $k$. If $P(0)=500$ and $P(2)=800$, which value of $k$ is correct?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$k=\ln(1.6)$','explanation','This forgets to divide by the time interval $2$.'),
    jsonb_build_object('id','B','text','$k=\dfrac{1}{2}\ln(1.6)$','explanation','Correct: $800=500e^{2k}\Rightarrow e^{2k}=1.6\Rightarrow k=\tfrac12\ln(1.6)$.'),
    jsonb_build_object('id','C','text','$k=\dfrac{\ln(800)}{\ln(500)}$','explanation','This is not a valid step for solving $500e^{2k}=800$.'),
    jsonb_build_object('id','D','text','$k=\dfrac{800-500}{2}$','explanation','This treats exponential growth as linear.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Solve $P(t)=500e^{kt}$. Then $800=500e^{2k}$ so $e^{2k}=1.6$ and $k=\tfrac12\ln(1.6)$.',
  recommendation_reasons = ARRAY['Targets parameter-solving in exponential DE models.','Addresses the common mistake of forgetting the time interval in the exponent.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Exponential model; solve for $k$ from two data points.',
  weight_primary = 0.80,
  weight_supporting = 0.20,
    primary_skill_id = 'SK_MODELING_DE',
  supporting_skill_ids = ARRAY['SK_EXPONENTIAL_MODEL','SK_SOLVE_PARAMETER','SK_APPLY_INITIAL_CONDITION'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q1';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 90,
  skill_tags = ARRAY['SK_VERIFY_SOLUTION','SK_DIFFERENTIATE','SK_SUBSTITUTE_INTO_DE'],
  error_tags = ARRAY['E_DERIVATIVE_MISMATCH','E_ALGEBRA_SLIP'],
  prompt = 'Which function satisfies the differential equation $y''''=2y-x$ for all $x$?',
  latex = 'Which function satisfies the differential equation $y''''=2y-x$ for all $x$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$y=Ce^{2x}+\dfrac{x}{2}+\dfrac{1}{4}$','explanation','Correct: this form satisfies $y''''-2y=-x$ when differentiated and substituted.'),
    jsonb_build_object('id','B','text','$y=Ce^{2x}+\dfrac{x}{2}-\dfrac{1}{4}$','explanation','This leads to $y''''=2y-x-1$ after substitution.'),
    jsonb_build_object('id','C','text','$y=Ce^{x}+\dfrac{x}{2}+\dfrac{1}{4}$','explanation','The homogeneous part should be $e^{2x}$, not $e^{x}$.'),
    jsonb_build_object('id','D','text','$y=Ce^{2x}+\dfrac{x}{4}+\dfrac{1}{4}$','explanation','The particular linear term is incorrect.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Try $y=Ce^{2x}+ax+b$. Then $y''''=2Ce^{2x}+a$ and $2y-x=2Ce^{2x}+(2a-1)x+2b$. Match coefficients: $2a-1=0\Rightarrow a=\tfrac12$ and $a=2b\Rightarrow b=\tfrac14$.',
  recommendation_reasons = ARRAY['Builds fast verification by substitution.','Reinforces matching coefficients for linear DEs.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Verification + recognizing linear form $y''''-2y=-x$.',
  weight_primary = 1.00,
  weight_supporting = 0.00,
    primary_skill_id = 'SK_VERIFY_SOLUTION',
  supporting_skill_ids = ARRAY['SK_DIFFERENTIATE','SK_SUBSTITUTE_INTO_DE'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q2';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 75,
  skill_tags = ARRAY['SK_SLOPE_FIELD_INTERPRET','SK_EVALUATE_DERIVATIVE_AT_POINT'],
  error_tags = ARRAY['E_MISREAD_SLOPE_FIELD','E_SIGN_ERROR'],
  prompt = 'The image shows the slope field for $\dfrac{dy}{dx}=x-y$. At the point $(1,0)$, which slope best matches the field?\n\n![7.0-UT-Q3](7.0-UT-Q3.png)',
  latex = 'The image shows the slope field for $\dfrac{dy}{dx}=x-y$. At the point $(1,0)$, which slope best matches the field?\n\n![7.0-UT-Q3](7.0-UT-Q3.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$-1$','explanation','At $(1,0)$, $x-y=1$, not $-1$.'),
    jsonb_build_object('id','B','text','$0$','explanation','A zero slope would require $x=y$.'),
    jsonb_build_object('id','C','text','$1$','explanation','Correct: $\left.\dfrac{dy}{dx}\right|_{(1,0)}=1-0=1$.'),
    jsonb_build_object('id','D','text','$2$','explanation','This is too steep; the slope is exactly $1$.')
  ),
  correct_option_id = 'C',
  tolerance = 0.0010,
  explanation = 'Compute the slope from the DE: $\dfrac{dy}{dx}=x-y$. At $(1,0)$, the slope is $1$.',
  recommendation_reasons = ARRAY['Connects analytic slope evaluation to slope-field interpretation.','Targets common misread of slope at a point.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 1,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Slope fields: compute slope at a point and match to field.',
  weight_primary = 0.90,
  weight_supporting = 0.10,
    primary_skill_id = 'SK_SLOPE_FIELD_INTERPRET',
  supporting_skill_ids = ARRAY['SK_EVALUATE_DERIVATIVE_AT_POINT'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q3';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 135,
  skill_tags = ARRAY['SK_SLOPE_FIELD_REASON','SK_EQUILIBRIUM','SK_STABILITY'],
  error_tags = ARRAY['E_EQUILIBRIUM_MISCLASSIFY','E_SIGN_ERROR'],
  prompt = 'For the differential equation $\dfrac{dy}{dx}=y(2-y)$, which statement is true?',
  latex = 'For the differential equation $\dfrac{dy}{dx}=y(2-y)$, which statement is true?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$y=0$ and $y=2$ are equilibria and both are unstable.','explanation','One is stable and the other is unstable.'),
    jsonb_build_object('id','B','text','Only $y=0$ is an equilibrium solution.','explanation','Both $y=0$ and $y=2$ make $y''''=0$.'),
    jsonb_build_object('id','C','text','$y=2$ is stable and $y=0$ is unstable.','explanation','Sign analysis shows the opposite.'),
    jsonb_build_object('id','D','text','$y=0$ and $y=2$ are equilibria; $y=2$ is stable and $y=0$ is unstable.','explanation','Correct: for $0<y<2$, $y''''>0$ so solutions increase toward $2$; for $y>2$, $y''''<0$ so solutions decrease toward $2$.')
  ),
  correct_option_id = 'D',
  tolerance = 0.0010,
  explanation = 'Equilibria satisfy $y(2-y)=0\Rightarrow y=0,2$. If $0<y<2$, then $y''''>0$ so solutions rise; if $y>2$, then $y''''<0$ so solutions fall. Thus $y=2$ is stable and $y=0$ is unstable.',
  recommendation_reasons = ARRAY['Uses sign analysis to classify equilibria and stability.','Matches common AP qualitative reasoning tasks.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Autonomous DE: equilibria and stability via sign chart.',
  weight_primary = 0.85,
  weight_supporting = 0.15,
    primary_skill_id = 'SK_SLOPE_FIELD_REASON',
  supporting_skill_ids = ARRAY['SK_EQUILIBRIUM','SK_STABILITY'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q4';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 120,
  skill_tags = ARRAY['SK_EULER_METHOD','SK_NUMERICAL_APPROX','SK_COMPUTE_ITERATES'],
  error_tags = ARRAY['E_EULER_STEP_MISTAKE','E_ALGEBRA_SLIP'],
  prompt = 'Use Euler’s method with step size $h=0.5$ to approximate $y(1)$ for the initial value problem $y''''=x+y$, $y(0)=1$.',
  latex = 'Use Euler’s method with step size $h=0.5$ to approximate $y(1)$ for the initial value problem $y''''=x+y$, $y(0)=1$.',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$2.25$','explanation','This comes from using the wrong slope at a step.'),
    jsonb_build_object('id','B','text','$2.5$','explanation','Correct: $y_1=1+0.5(0+1)=1.5$, then $y_2=1.5+0.5(0.5+1.5)=2.5$.'),
    jsonb_build_object('id','C','text','$3$','explanation','This overestimates by applying the wrong update rule.'),
    jsonb_build_object('id','D','text','$1.5$','explanation','This is only after one step (to $x=0.5$).')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Two steps: $(x_0,y_0)=(0,1)$. $y_1=1+0.5(1)=1.5$ at $x=0.5$. Next slope $=0.5+1.5=2$. So $y_2=1.5+0.5(2)=2.5$ at $x=1$.',
  recommendation_reasons = ARRAY['BC core skill: executing Euler iterates.','Targets common arithmetic and step-index mistakes.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Euler method numeric approximation, step-by-step.',
  weight_primary = 0.90,
  weight_supporting = 0.10,
    primary_skill_id = 'SK_EULER_METHOD',
  supporting_skill_ids = ARRAY['SK_NUMERICAL_APPROX','SK_COMPUTE_ITERATES'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q5';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 140,
  skill_tags = ARRAY['SK_SEPARATION_VARIABLES','SK_INTEGRATE','SK_IMPLICIT_SOLUTION'],
  error_tags = ARRAY['E_SEPARATION_CONSTANT_MISSING','E_ALGEBRA_SLIP'],
  prompt = 'Find the general solution of $\dfrac{dy}{dx}=\dfrac{x}{1+y^2}$.',
  latex = 'Find the general solution of $\dfrac{dy}{dx}=\dfrac{x}{1+y^2}$.',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$y+\dfrac{y^3}{3}=\dfrac{x^2}{2}+C$','explanation','Correct: $(1+y^2)dy=x\,dx$ integrates to $y+\tfrac{y^3}{3}=\tfrac{x^2}{2}+C$.'),
    jsonb_build_object('id','B','text','${\arctan(y)}=\dfrac{x^2}{2}+C$','explanation','This would come from $\dfrac{1}{1+y^2}dy$, but the left side is $(1+y^2)dy$.'),
    jsonb_build_object('id','C','text','$\dfrac{1}{1+y^2}=\dfrac{x^2}{2}+C$','explanation','Incorrect integration and algebra.'),
    jsonb_build_object('id','D','text','$y^2=\dfrac{x^2}{2}+C$','explanation','Misses the $y^3$ term from integrating $y^2$.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Separate: $(1+y^2)dy=x\,dx$. Integrate: $\int(1+y^2)dy=\int x\,dx\Rightarrow y+\tfrac{y^3}{3}=\tfrac{x^2}{2}+C$.',
  recommendation_reasons = ARRAY['Separation with a nontrivial polynomial integral.','Targets the common swap of $(1+y^2)$ with $\tfrac{1}{1+y^2}$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Separation; implicit general solution.',
  weight_primary = 1.00,
  weight_supporting = 0.00,
    primary_skill_id = 'SK_SEPARATION_VARIABLES',
  supporting_skill_ids = ARRAY['SK_INTEGRATE','SK_IMPLICIT_SOLUTION'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q6';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 115,
  skill_tags = ARRAY['SK_SEPARATION_VARIABLES','SK_APPLY_INITIAL_CONDITION','SK_SOLVE_EXPLICIT'],
  error_tags = ARRAY['E_MISSING_INITIAL_CONDITION','E_EXPONENT_ERROR','E_ALGEBRA_SLIP'],
  prompt = 'Solve the initial value problem $\dfrac{dy}{dx}=3xy$, $y(0)=2$, and find $y(1)$.',
  latex = 'Solve the initial value problem $\dfrac{dy}{dx}=3xy$, $y(0)=2$, and find $y(1)$.',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$2e^{3}$','explanation','This uses $\int 3x\,dx=3x^2$ instead of $\tfrac{3}{2}x^2$.'),
    jsonb_build_object('id','B','text','$2e$','explanation','This uses $\int 3x\,dx=x^2$.'),
    jsonb_build_object('id','C','text','$2e^{3/4}$','explanation','This halves the exponent incorrectly.'),
    jsonb_build_object('id','D','text','$2e^{3/2}$','explanation','Correct: $\ln|y|=\tfrac{3}{2}x^2+C$, so $y=2e^{\tfrac{3}{2}x^2}$ and $y(1)=2e^{3/2}$.')
  ),
  correct_option_id = 'D',
  tolerance = 0.0010,
  explanation = 'Separate: $\dfrac{1}{y}dy=3x\,dx$. Integrate: $\ln|y|=\tfrac{3}{2}x^2+C$. Use $y(0)=2$ to get $C=\ln 2$, so $y=2e^{\tfrac{3}{2}x^2}$ and $y(1)=2e^{3/2}$.',
  recommendation_reasons = ARRAY['Separable + IC is a central Unit 7 competency.','Targets the common integration mistake on $3x$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Separable with IC; exponential in $x^2$.',
  weight_primary = 0.85,
  weight_supporting = 0.15,
    primary_skill_id = 'SK_SEPARATION_VARIABLES',
  supporting_skill_ids = ARRAY['SK_APPLY_INITIAL_CONDITION','SK_SOLVE_EXPLICIT'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q7';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 125,
  skill_tags = ARRAY['SK_EXPONENTIAL_MODEL','SK_LOGARITHMS','SK_SOLVE_FOR_TIME'],
  error_tags = ARRAY['E_LOG_MISTAKE','E_ALGEBRA_SLIP','E_UNITS_INTERPRETATION'],
  prompt = 'A cup of coffee cools in a room at $20^\circ\text{C}$ and satisfies $\dfrac{dT}{dt}=-k(T-20)$. If $T(0)=100$ and $T(10)=60$, what is $T(20)$?',
  latex = 'A cup of coffee cools in a room at $20^\circ\text{C}$ and satisfies $\dfrac{dT}{dt}=-k(T-20)$. If $T(0)=100$ and $T(10)=60$, what is $T(20)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$30$','explanation','This applies halving to $T$ instead of to the excess temperature $T-20$.'),
    jsonb_build_object('id','B','text','$35$','explanation','This does not match the exponential decay implied by the model.'),
    jsonb_build_object('id','C','text','$40$','explanation','Correct: the excess temperature halves every 10 minutes, so $T(20)=20+20=40$.'),
    jsonb_build_object('id','D','text','$50$','explanation','This keeps the excess temperature constant.')
  ),
  correct_option_id = 'C',
  tolerance = 0.0010,
  explanation = 'Let $u=T-20$. Then $u''''=-ku$ so $u(t)=80e^{-kt}$. Given $u(10)=40$, we get $e^{-10k}=\tfrac12$. Then $u(20)=80(\tfrac12)^2=20$, so $T(20)=20+20=40$.',
  recommendation_reasons = ARRAY['Classic Newton’s Law of Cooling structure.','Reinforces subtracting ambient temperature before exponential reasoning.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Exponential decay with shift by ambient temperature.',
  weight_primary = 0.80,
  weight_supporting = 0.20,
    primary_skill_id = 'SK_EXPONENTIAL_MODEL',
  supporting_skill_ids = ARRAY['SK_LOGARITHMS','SK_SOLVE_FOR_TIME'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q8';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 80,
  skill_tags = ARRAY['SK_LOGISTIC_MODEL','SK_EVALUATE_DERIVATIVE_AT_POINT','SK_INTERPRET_RATE'],
  error_tags = ARRAY['E_UNITS_INTERPRETATION','E_ALGEBRA_SLIP'],
  prompt = 'A population satisfies the logistic differential equation $\dfrac{dP}{dt}=0.4P\left(1-\dfrac{P}{500}\right)$ with $P(0)=100$. What is $\dfrac{dP}{dt}$ at $t=0$?',
  latex = 'A population satisfies the logistic differential equation $\dfrac{dP}{dt}=0.4P\left(1-\dfrac{P}{500}\right)$ with $P(0)=100$. What is $\dfrac{dP}{dt}$ at $t=0$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$20$','explanation','This omits the factor $\left(1-\tfrac{P}{500}\right)$.'),
    jsonb_build_object('id','B','text','$32$','explanation','Correct: $0.4(100)\left(1-\tfrac{100}{500}\right)=40(0.8)=32$.'),
    jsonb_build_object('id','C','text','$40$','explanation','This ignores crowding by setting the parentheses to $1$.'),
    jsonb_build_object('id','D','text','$80$','explanation','This incorrectly multiplies by $\tfrac{P}{500}$ instead of subtracting it.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Plug in $P=100$: $P''''(0)=0.4\cdot100\left(1-\frac{100}{500}\right)=40\cdot0.8=32$.',
  recommendation_reasons = ARRAY['Quick logistic substitution: very AP-common.','Checks interpretation of instantaneous rate at $t=0$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Logistic model: compute initial growth rate from DE.',
  weight_primary = 0.90,
  weight_supporting = 0.10,
    primary_skill_id = 'SK_LOGISTIC_MODEL',
  supporting_skill_ids = ARRAY['SK_EVALUATE_DERIVATIVE_AT_POINT','SK_INTERPRET_RATE'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q9';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 140,
  skill_tags = ARRAY['SK_SEPARATION_VARIABLES','SK_APPLY_INITIAL_CONDITION','SK_ALGEBRA_SOLVE_FOR_Y'],
  error_tags = ARRAY['E_MISSING_INITIAL_CONDITION','E_SEPARATION_CONSTANT_MISSING','E_ALGEBRA_SLIP'],
  prompt = 'Solve the initial value problem $\dfrac{dy}{dx}=(y-1)^2$, $y(0)=0$. Which solution is correct (for $x>-1$)?',
  latex = 'Solve the initial value problem $\dfrac{dy}{dx}=(y-1)^2$, $y(0)=0$. Which solution is correct (for $x>-1$)?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$y=1+\dfrac{1}{x+1}$','explanation','This has the wrong sign after integrating $\dfrac{1}{(y-1)^2}$.'),
    jsonb_build_object('id','B','text','$y=1-\dfrac{1}{x-1}$','explanation','This does not satisfy $y(0)=0$.'),
    jsonb_build_object('id','C','text','$y=1-\dfrac{1}{1-x}$','explanation','This does not satisfy the integrated form with the given initial condition.'),
    jsonb_build_object('id','D','text','$y=1-\dfrac{1}{x+1}$','explanation','Correct: $-\dfrac{1}{y-1}=x+C$ and $y(0)=0$ gives $C=1$.')
  ),
  correct_option_id = 'D',
  tolerance = 0.0010,
  explanation = 'Separate: $\dfrac{dy}{(y-1)^2}=dx$. Integrate: $-\dfrac{1}{y-1}=x+C$. Use $y(0)=0$: $-\dfrac{1}{-1}=1=C$. So $-\dfrac{1}{y-1}=x+1\Rightarrow y=1-\dfrac{1}{x+1}$ (for $x>-1$).',
  recommendation_reasons = ARRAY['Separable IVP requiring careful algebra inversion.','Targets sign mistakes with $(y-1)^{-2}$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Separable IVP; solve explicitly and respect domain.',
  weight_primary = 0.85,
  weight_supporting = 0.15,
    primary_skill_id = 'SK_SEPARATION_VARIABLES',
  supporting_skill_ids = ARRAY['SK_APPLY_INITIAL_CONDITION','SK_ALGEBRA_SOLVE_FOR_Y'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q10';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 110,
  skill_tags = ARRAY['SK_SEPARATION_VARIABLES','SK_RECOGNIZE_SOLUTION_FORM','SK_EXPONENT_ALGEBRA'],
  error_tags = ARRAY['E_SEPARATION_CONSTANT_MISSING','E_EXPONENT_ERROR'],
  prompt = 'Consider the differential equation $\dfrac{dy}{dx}=xy$ with $y(0)=1$. Which function is the solution?',
  latex = 'Consider the differential equation $\dfrac{dy}{dx}=xy$ with $y(0)=1$. Which function is the solution?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$y=e^{x^2/2}$','explanation','Correct: $\dfrac{1}{y}dy=x\,dx\Rightarrow \ln y=\tfrac{x^2}{2}+C$, and $y(0)=1$ gives $C=0$.'),
    jsonb_build_object('id','B','text','$y=e^{x}$','explanation','This would solve $y''''=y$, not $y''''=xy$.'),
    jsonb_build_object('id','C','text','$y=\dfrac{x^2}{2}+1$','explanation','This is not an exponential solution to $y''''=xy$.'),
    jsonb_build_object('id','D','text','$y=e^{x^2}$','explanation','Exponent should be $\tfrac{x^2}{2}$, not $x^2$.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Separate: $\dfrac{1}{y}dy=x\,dx$. Integrate: $\ln|y|=\tfrac{x^2}{2}+C$. With $y(0)=1$, $C=0$ and $y=e^{x^2/2}$.',
  recommendation_reasons = ARRAY['Fast recognition of a separable solution.','Targets the common missing factor $\tfrac12$ after integrating $x$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Separable recognition; exact solution form.',
  weight_primary = 0.80,
  weight_supporting = 0.20,
    primary_skill_id = 'SK_SEPARATION_VARIABLES',
  supporting_skill_ids = ARRAY['SK_RECOGNIZE_SOLUTION_FORM','SK_EXPONENT_ALGEBRA'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q11';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 85,
  skill_tags = ARRAY['SK_EXPONENTIAL_MODEL','SK_HALF_LIFE','SK_SOLVE_FOR_TIME'],
  error_tags = ARRAY['E_LOG_MISTAKE','E_UNITS_INTERPRETATION'],
  prompt = 'A quantity $V(t)$ satisfies $\dfrac{dV}{dt}=-0.3V$ with $V(0)>0$. What is the half-life (time for $V$ to halve)?',
  latex = 'A quantity $V(t)$ satisfies $\dfrac{dV}{dt}=-0.3V$ with $V(0)>0$. What is the half-life (time for $V$ to halve)?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','${\dfrac{\ln 2}{0.6}}$','explanation','This incorrectly doubles the decay constant.'),
    jsonb_build_object('id','B','text','${\dfrac{2}{0.3}}$','explanation','This treats the model as linear.'),
    jsonb_build_object('id','C','text','${\dfrac{\ln 2}{0.3}}$','explanation','Correct: $\tfrac12=e^{-0.3t}\Rightarrow t=\dfrac{\ln 2}{0.3}$.'),
    jsonb_build_object('id','D','text','$\ln(0.3)$','explanation','Half-life is a time, not a logarithm of the rate.')
  ),
  correct_option_id = 'C',
  tolerance = 0.0010,
  explanation = 'Solution: $V(t)=V(0)e^{-0.3t}$. Half-life: $\tfrac12= e^{-0.3t}\Rightarrow t=\dfrac{\ln 2}{0.3}$.',
  recommendation_reasons = ARRAY['High-frequency exponential interpretation question.','Reinforces half-life setup using ratios.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Half-life from exponential decay DE.',
  weight_primary = 0.85,
  weight_supporting = 0.15,
    primary_skill_id = 'SK_EXPONENTIAL_MODEL',
  supporting_skill_ids = ARRAY['SK_HALF_LIFE','SK_SOLVE_FOR_TIME'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q12';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 120,
  skill_tags = ARRAY['SK_SEPARATION_VARIABLES','SK_APPLY_INITIAL_CONDITION','SK_POWER_LAW_SOLUTION'],
  error_tags = ARRAY['E_MISSING_INITIAL_CONDITION','E_ALGEBRA_SLIP'],
  prompt = 'Given $\dfrac{dy}{dx}=\dfrac{2y}{x}$ and $y(3)=5$, what is $y(6)$?',
  latex = 'Given $\dfrac{dy}{dx}=\dfrac{2y}{x}$ and $y(3)=5$, what is $y(6)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$10$','explanation','This assumes $y$ doubles when $x$ doubles, but the solution scales like $x^2$.'),
    jsonb_build_object('id','B','text','$15$','explanation','This uses proportionality $y\propto x$ instead of $y\propto x^2$.'),
    jsonb_build_object('id','C','text','$20$','explanation','Correct: $y=Cx^2$, then $5=9C\Rightarrow C=\tfrac{5}{9}$ and $y(6)=\tfrac{5}{9}\cdot36=20$.'),
    jsonb_build_object('id','D','text','$25$','explanation','This comes from using $y\propto x$ with $y(6)=10$ then adding incorrectly.')
  ),
  correct_option_id = 'C',
  tolerance = 0.0010,
  explanation = 'Separate: $\dfrac{1}{y}dy=\dfrac{2}{x}dx\Rightarrow \ln y=2\ln x+C\Rightarrow y=Cx^2$. Use $y(3)=5$ so $C=5/9$. Then $y(6)= (5/9)\cdot36=20$.',
  recommendation_reasons = ARRAY['Separable DE leading to power law.','Targets frequent mistake: missing exponent 2 on $x$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Separation with logarithms; apply IC to evaluate.',
  weight_primary = 0.85,
  weight_supporting = 0.15,
    primary_skill_id = 'SK_SEPARATION_VARIABLES',
  supporting_skill_ids = ARRAY['SK_APPLY_INITIAL_CONDITION','SK_POWER_LAW_SOLUTION'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q13';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 95,
  skill_tags = ARRAY['SK_EULER_METHOD','SK_ERROR_ANALYSIS','SK_COMPARE_TO_EXACT'],
  error_tags = ARRAY['E_EULER_STEP_MISTAKE','E_UNITS_INTERPRETATION'],
  prompt = 'For $y''''=y$ with $y(0)=1$, Euler’s method with $h=1$ gives $y(1)\approx 2$. The exact value is $e$. What is the percent error $\left(\dfrac{|2-e|}{e}\right)\times 100\%$ to the nearest whole percent?',
  latex = 'For $y''''=y$ with $y(0)=1$, Euler’s method with $h=1$ gives $y(1)\approx 2$. The exact value is $e$. What is the percent error $\left(\dfrac{|2-e|}{e}\right)\times 100\%$ to the nearest whole percent?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$18\%$','explanation','This uses an incorrect denominator for percent error.'),
    jsonb_build_object('id','B','text','$26\%$','explanation','Correct: $\dfrac{|e-2|}{e}\approx \dfrac{0.718}{2.718}\approx 0.264\approx 26\%$.'),
    jsonb_build_object('id','C','text','$36\%$','explanation','This overestimates the relative error.'),
    jsonb_build_object('id','D','text','$72\%$','explanation','This confuses absolute error $|e-2|$ with percent error.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Relative error is $\dfrac{|e-2|}{e}$. Using $e\approx 2.718$ gives $\dfrac{0.718}{2.718}\approx 0.264$, or $26\%$.',
  recommendation_reasons = ARRAY['BC-style Euler + error concept.','Targets correct definition of percent (relative) error.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Percent error = |approx-exact|/|exact|.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_EULER_METHOD',
  supporting_skill_ids = ARRAY['SK_ERROR_ANALYSIS','SK_COMPARE_TO_EXACT'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q14';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 135,
  skill_tags = ARRAY['SK_EULER_METHOD','SK_USE_TABLE','SK_COMPUTE_ITERATES'],
  error_tags = ARRAY['E_EULER_STEP_MISTAKE','E_ALGEBRA_SLIP'],
  prompt = 'Use Euler’s method with step size $h=0.5$ to approximate $y(1.5)$ for $y''''=y-x$, $y(0)=1$.\n\n![7.0-UT-Q15](7.0-UT-Q15.png)',
  latex = 'Use Euler’s method with step size $h=0.5$ to approximate $y(1.5)$ for $y''''=y-x$, $y(0)=1$.\n\n![7.0-UT-Q15](7.0-UT-Q15.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$2.5$','explanation','Correct: $y_1=1.5$, $y_2=2.0$, $y_3=2.5$ at $x=1.5$.'),
    jsonb_build_object('id','B','text','$2.25$','explanation','This comes from using an averaging method, not Euler’s method.'),
    jsonb_build_object('id','C','text','$3.0$','explanation','This typically results from using the wrong slope expression.'),
    jsonb_build_object('id','D','text','$1.5$','explanation','This is only the value after one step at $x=0.5$.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Euler update: $y_{n+1}=y_n+h(y_n-x_n)$. Start $(0,1)$. $y_1=1+0.5(1-0)=1.5$. $y_2=1.5+0.5(1.5-0.5)=2.0$. $y_3=2.0+0.5(2.0-1.0)=2.5$ at $x=1.5$.',
  recommendation_reasons = ARRAY['Reinforces table-based Euler execution.','Targets common slip: plugging wrong $x_n$ or wrong slope expression.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Euler with multiple steps to a non-integer $x$-value.',
  weight_primary = 0.90,
  weight_supporting = 0.10,
    primary_skill_id = 'SK_EULER_METHOD',
  supporting_skill_ids = ARRAY['SK_USE_TABLE','SK_COMPUTE_ITERATES'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q15';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 90,
  skill_tags = ARRAY['SK_APPLY_INITIAL_CONDITION','SK_VERIFY_SOLUTION','SK_EVALUATE_FUNCTION'],
  error_tags = ARRAY['E_MISSING_INITIAL_CONDITION','E_ALGEBRA_SLIP'],
  prompt = 'A family of functions is given by $y=x^2+C$. If $y$ satisfies $y''''=2x$ and $y(1)=3$, what is $y(4)$?',
  latex = 'A family of functions is given by $y=x^2+C$. If $y$ satisfies $y''''=2x$ and $y(1)=3$, what is $y(4)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$16$','explanation','This ignores the constant $C$ determined by the initial condition.'),
    jsonb_build_object('id','B','text','$17$','explanation','This uses the wrong value of $C$.'),
    jsonb_build_object('id','C','text','$18$','explanation','Correct: $3=1+C\Rightarrow C=2$, so $y(4)=16+2=18$.'),
    jsonb_build_object('id','D','text','$19$','explanation','This uses an incorrect constant $C$.')
  ),
  correct_option_id = 'C',
  tolerance = 0.0010,
  explanation = 'Use $y(1)=3$: $3=1+C$ so $C=2$. Then $y(4)=4^2+2=18$.',
  recommendation_reasons = ARRAY['Quick IC application on a verified solution family.','Targets missing-IC error.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Verify + apply IC; evaluate later value.',
  weight_primary = 0.75,
  weight_supporting = 0.25,
    primary_skill_id = 'SK_APPLY_INITIAL_CONDITION',
  supporting_skill_ids = ARRAY['SK_VERIFY_SOLUTION','SK_EVALUATE_FUNCTION'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q16';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 95,
  skill_tags = ARRAY['SK_LOGISTIC_MODEL','SK_LONG_TERM_BEHAVIOR','SK_EQUILIBRIUM'],
  error_tags = ARRAY['E_EQUILIBRIUM_MISCLASSIFY','E_UNITS_INTERPRETATION'],
  prompt = 'A population satisfies $\dfrac{dP}{dt}=P(3-P)$ with $P(0)=4$. What is $\displaystyle\lim_{t\to\infty}P(t)$?',
  latex = 'A population satisfies $\dfrac{dP}{dt}=P(3-P)$ with $P(0)=4$. What is $\displaystyle\lim_{t\to\infty}P(t)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$0$','explanation','For $P>3$, the derivative is negative, so $P$ decreases, but not toward $0$.'),
    jsonb_build_object('id','B','text','$4$','explanation','$4$ is only the initial value.'),
    jsonb_build_object('id','C','text','$\infty$','explanation','If $P>3$, then $P(3-P)<0$, so unbounded growth is impossible.'),
    jsonb_build_object('id','D','text','$3$','explanation','Correct: solutions with $P(0)>3$ decrease toward the stable equilibrium $P=3$.')
  ),
  correct_option_id = 'D',
  tolerance = 0.0010,
  explanation = 'Equilibria: $P=0,3$. If $P>3$, then $P''''<0$ so $P$ decreases. If $0<P<3$, then $P''''>0$ so $P$ increases. Thus solutions approach $3$.',
  recommendation_reasons = ARRAY['Core logistic qualitative reasoning.','Targets equilibrium/stability interpretation from $P(3-P)$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Autonomous logistic: long-term limit via sign chart.',
  weight_primary = 0.80,
  weight_supporting = 0.20,
    primary_skill_id = 'SK_LOGISTIC_MODEL',
  supporting_skill_ids = ARRAY['SK_LONG_TERM_BEHAVIOR','SK_EQUILIBRIUM'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q17';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 1,
  target_time_seconds = 60,
  skill_tags = ARRAY['SK_SLOPE_FIELD_INTERPRET','SK_EVALUATE_DERIVATIVE_AT_POINT'],
  error_tags = ARRAY['E_MISREAD_SLOPE_FIELD','E_SIGN_ERROR'],
  prompt = 'For $\dfrac{dy}{dx}=x-y$ with initial condition $y(0)=1$, is the solution initially increasing or decreasing at $x=0$?',
  latex = 'For $\dfrac{dy}{dx}=x-y$ with initial condition $y(0)=1$, is the solution initially increasing or decreasing at $x=0$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','Increasing, because $x-y>0$ at $(0,1)$.','explanation','At $(0,1)$, $x-y=-1<0$.'),
    jsonb_build_object('id','B','text','Decreasing, because $x-y<0$ at $(0,1)$.','explanation','Correct: slope $=0-1=-1$ so the solution decreases initially.'),
    jsonb_build_object('id','C','text','Neither; the slope is $0$ at $(0,1)$.','explanation','The slope is $-1$, not $0$.'),
    jsonb_build_object('id','D','text','Cannot be determined without solving explicitly.','explanation','Local behavior is determined by the sign of $y''''$ at the initial point.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Evaluate the slope at the initial point: $y''''(0)=0-1=-1<0$, so the solution decreases initially.',
  recommendation_reasons = ARRAY['Quick slope-at-a-point reasoning.','Targets common sign mistake with $x-y$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 1,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Initial direction from sign of derivative.',
  weight_primary = 0.90,
  weight_supporting = 0.10,
    primary_skill_id = 'SK_SLOPE_FIELD_INTERPRET',
  supporting_skill_ids = ARRAY['SK_EVALUATE_DERIVATIVE_AT_POINT'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q18';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 105,
  skill_tags = ARRAY['SK_EXPONENTIAL_MODEL','SK_LOGARITHMS','SK_SOLVE_FOR_TIME'],
  error_tags = ARRAY['E_LOG_MISTAKE','E_ALGEBRA_SLIP'],
  prompt = 'A population satisfies $\dfrac{dN}{dt}=0.2N$ with $N(0)=50$. How long does it take for the population to reach $200$?',
  latex = 'A population satisfies $\dfrac{dN}{dt}=0.2N$ with $N(0)=50$. How long does it take for the population to reach $200$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$5\ln 4$','explanation','Correct: $200=50e^{0.2t}\Rightarrow 4=e^{0.2t}\Rightarrow t=\dfrac{\ln4}{0.2}=5\ln4$.'),
    jsonb_build_object('id','B','text','$\ln 4$','explanation','This forgets to divide by $0.2$.'),
    jsonb_build_object('id','C','text','$\dfrac{\ln(200)}{\ln(50)}$','explanation','This is not the correct way to solve $50e^{0.2t}=200$.'),
    jsonb_build_object('id','D','text','$\dfrac{150}{0.2}$','explanation','This treats the growth as linear.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Solution: $N(t)=50e^{0.2t}$. Set $200=50e^{0.2t}$ so $4=e^{0.2t}$ and $t=\dfrac{\ln4}{0.2}=5\ln4$.',
  recommendation_reasons = ARRAY['Standard time-to-target in exponential DE models.','Targets the missing-rate division error.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Solve for time using logarithms.',
  weight_primary = 0.85,
  weight_supporting = 0.15,
    primary_skill_id = 'SK_EXPONENTIAL_MODEL',
  supporting_skill_ids = ARRAY['SK_LOGARITHMS','SK_SOLVE_FOR_TIME'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q19';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_DiffEq',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 5,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_EQUILIBRIUM','SK_STABILITY','SK_SIGN_CHART_AUTONOMOUS'],
  error_tags = ARRAY['E_EQUILIBRIUM_MISCLASSIFY','E_SIGN_ERROR'],
  prompt = 'For the autonomous differential equation $\dfrac{dy}{dt}=y^2-y$, which statement is correct?',
  latex = 'For the autonomous differential equation $\dfrac{dy}{dt}=y^2-y$, which statement is correct?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','The only equilibrium is $y=0$, and it is unstable.','explanation','There are two equilibria: $y=0$ and $y=1$.'),
    jsonb_build_object('id','B','text','$y=1$ is stable and $y=0$ is unstable.','explanation','Sign analysis shows the opposite.'),
    jsonb_build_object('id','C','text','$y=0$ and $y=1$ are equilibria; $y=0$ is stable and $y=1$ is unstable.','explanation','Correct: $y''''=y(y-1)$ is negative on $(0,1)$ and positive on $(-\infty,0)$ and $(1,\infty)$.'),
    jsonb_build_object('id','D','text','$y=0$ and $y=1$ are equilibria and both are stable.','explanation','The sign pattern does not support both equilibria being stable.')
  ),
  correct_option_id = 'C',
  tolerance = 0.0010,
  explanation = 'Equilibria: $y(y-1)=0\Rightarrow y=0,1$. If $0<y<1$, then $y(y-1)<0$ so $y$ decreases toward $0$. If $y<0$, then $y(y-1)>0$ so $y$ increases toward $0$. Thus $y=0$ is stable. Near $y=1$, values slightly less than $1$ move down and values slightly greater than $1$ move up, so $y=1$ is unstable.',
  recommendation_reasons = ARRAY['AP-style qualitative stability problem.','Targets high-frequency sign-chart mistakes.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 5,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Autonomous DE stability classification via sign chart.',
  weight_primary = 0.90,
  weight_supporting = 0.10,
    primary_skill_id = 'SK_EQUILIBRIUM',
  supporting_skill_ids = ARRAY['SK_STABILITY','SK_SIGN_CHART_AUTONOMOUS'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_DiffEq',
  updated_at = NOW()
WHERE title = '7.0-UT-Q20';

COMMIT;
