-- Unit 8 Unit Test Questions (Q4 - Q20)

BEGIN;

UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_AREA_BETWEEN_DX', 'SK_INTERSECTIONS', 'SK_SIGN_ANALYSIS'],
  error_tags = ARRAY['E_MISSING_ABS', 'E_INTERSECTION_MISSED', 'E_LIMITS_SWAP'],
  prompt = 'The shaded region between $y=\\sin x$ and $y=\\cos x$ on $[0,\\pi/2]$ is shown in 8.0-UT-Q4.png. Which expression equals the area of the region?',
  latex = 'The shaded region between $y=\\sin x$ and $y=\\cos x$ on $[0,\\pi/2]$ is shown in 8.0-UT-Q4.png. Which expression equals the area of the region?\n\n![8.0-UT-Q4](8.0-UT-Q4.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\int_0^{\\pi/2}(\\sin x-\\cos x)\\,dx$','explanation','This is signed and is negative on part of the interval; it is not guaranteed to equal area.'),
    jsonb_build_object('id','B','text','$\\int_0^{\\pi/4}(\\cos x-\\sin x)\\,dx+\\int_{\\pi/4}^{\\pi/2}(\\sin x-\\cos x)\\,dx$','explanation','Correct: split at $x=\\pi/4$ where $\\sin x=\\cos x$, then subtract top minus bottom on each subinterval.'),
    jsonb_build_object('id','C','text','$\\int_0^{\\pi/2}|\\sin x-\\cos x|\\,dx$','explanation','This also equals area, but the prompt asks for the standard split setup.'),
    jsonb_build_object('id','D','text','$\\int_0^{\\pi/4}(\\sin x-\\cos x)\\,dx+\\int_{\\pi/4}^{\\pi/2}(\\sin x-\\cos x)\\,dx$','explanation','The order is wrong on $[0,\\pi/4]$ where $\\cos x$ is above $\\sin x$.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Solve $\\sin x=\\cos x$ to find the switch point $x=\\pi/4$. On $[0,\\pi/4]$, top is $\\cos x$; on $[\\pi/4,\\pi/2]$, top is $\\sin x$. Therefore\n$$A=\\int_0^{\\pi/4}(\\cos x-\\sin x)\\,dx+\\int_{\\pi/4}^{\\pi/2}(\\sin x-\\cos x)\\,dx.$$',
  recommendation_reasons = ARRAY['Targets splitting at intersection points.', 'Prevents sign errors from not tracking which curve is on top.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Area between curves when the top function changes at an intersection.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_AREA_BETWEEN_DX',
  supporting_skill_ids = ARRAY['SK_INTERSECTIONS','SK_SIGN_ANALYSIS'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q4';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_AREA_BETWEEN_DY', 'SK_INTERSECTIONS'],
  error_tags = ARRAY['E_WRONG_VARIABLE_DYDX', 'E_LIMITS_SWAP', 'E_SIGN_ERROR'],
  prompt = 'The region bounded by $x=y^2$ and $x=2y$ is shown in 8.0-UT-Q5.png. Which integral gives the area of the region?',
  latex = 'The region bounded by $x=y^2$ and $x=2y$ is shown in 8.0-UT-Q5.png. Which integral gives the area of the region?\n\n![8.0-UT-Q5](8.0-UT-Q5.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\int_0^2(2y-y^2)\\,dy$','explanation','Correct: for $0\\le y\\le 2$, right curve is $x=2y$ and left curve is $x=y^2$.'),
    jsonb_build_object('id','B','text','$\\int_0^2(y^2-2y)\\,dy$','explanation','This reverses right minus left and yields a negative value.'),
    jsonb_build_object('id','C','text','$\\int_0^4(\\sqrt{x}-x/2)\\,dx$','explanation','A single $dx$ integral is not correct here without splitting because $y=\\sqrt{x}$ and $y=x/2$ intersect and swap on parts of the interval.'),
    jsonb_build_object('id','D','text','$\\int_0^2(2-y^2)\\,dy$','explanation','This does not represent right minus left in terms of $x(y)$.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Find intersections: $y^2=2y\\Rightarrow y=0,2$. Using horizontal slices,\n$$A=\\int_{0}^{2}\\big(x_{right}-x_{left}\\big)\\,dy=\\int_0^2(2y-y^2)\\,dy.$$',
  recommendation_reasons = ARRAY['Reinforces right-minus-left for $dy$ area.', 'Targets mixing $dx$ and $dy$ setups.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Area between curves given as $x$ functions of $y$.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_AREA_BETWEEN_DY',
  supporting_skill_ids = ARRAY['SK_INTERSECTIONS'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q5';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 120,
  skill_tags = ARRAY['SK_AREA_BETWEEN_DX', 'SK_INTERSECTIONS', 'SK_SIGN_ANALYSIS'],
  error_tags = ARRAY['E_MISSING_ABS', 'E_INTERSECTION_MISSED', 'E_SIGN_ERROR'],
  prompt = 'Let $y=x^2-4x$ and $y=0$. What is the area enclosed by the curves?',
  latex = 'Let $y=x^2-4x$ and $y=0$. What is the area enclosed by the curves?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$-\\frac{32}{3}$','explanation','This is negative because the integrand was not made top-minus-bottom (or absolute value was not used).'),
    jsonb_build_object('id','B','text','$\\frac{32}{3}$','explanation','Correct: on $[0,4]$ the parabola is below the axis, so area is $\\int_0^4(0-(x^2-4x))dx=\\frac{32}{3}$.'),
    jsonb_build_object('id','C','text','$\\frac{16}{3}$','explanation','Arithmetic error in evaluating the integral.'),
    jsonb_build_object('id','D','text','$\\frac{64}{3}$','explanation','This commonly comes from doubling by mistake.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Intersections: $x^2-4x=0\\Rightarrow x=0,4$. On $[0,4]$, $x^2-4x\\le 0$, so\n$$A=\\int_0^4(4x-x^2)\\,dx=\\left[2x^2-\\frac{x^3}{3}\\right]_0^4=32-\\frac{64}{3}=\\frac{32}{3}.$$',
  recommendation_reasons = ARRAY['Targets the sign issue when a curve is below the axis.', 'Reinforces intersection-to-bounds workflow.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Area enclosed by a curve and the x-axis; curve lies below on the interval.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_AREA_BETWEEN_DX',
  supporting_skill_ids = ARRAY['SK_INTERSECTIONS','SK_SIGN_ANALYSIS'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q6';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_VOLUME_CROSS_SECTIONS', 'SK_GEOMETRY_AREA'],
  error_tags = ARRAY['E_FORGET_SQUARE', 'E_WRONG_VARIABLE_DYDX'],
  prompt = 'A solid has base region bounded by $y=\\sqrt{x}$, $y=0$, and $0\\le x\\le 4$ (shown in 8.0-UT-Q7.png). Cross-sections perpendicular to the $x$-axis are squares. What is the volume?',
  latex = 'A solid has base region bounded by $y=\\sqrt{x}$, $y=0$, and $0\\le x\\le 4$ (shown in 8.0-UT-Q7.png). Cross-sections perpendicular to the $x$-axis are squares. What is the volume?\n\n![8.0-UT-Q7](8.0-UT-Q7.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\int_0^4 \\sqrt{x}\\,dx$','explanation','This uses the side length but does not square it to get cross-sectional area.'),
    jsonb_build_object('id','B','text','$8$','explanation','Correct: side length is $\\sqrt{x}$, area is $(\\sqrt{x})^2=x$, so $V=\\int_0^4 x\\,dx=8$.'),
    jsonb_build_object('id','C','text','$\\int_0^4 x^2\\,dx$','explanation','This treats side length as $x$ instead of $\\sqrt{x}$.'),
    jsonb_build_object('id','D','text','$4$','explanation','This results from incorrect bounds or missing the square-area step.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Square cross-sectional area is $A(x)=(\\text{side})^2=(\\sqrt{x})^2=x$. Thus\n$$V=\\int_0^4 A(x)\\,dx=\\int_0^4 x\\,dx=\\left[\\frac{x^2}{2}\\right]_0^4=8.$$',
  recommendation_reasons = ARRAY['Reinforces cross-section volume as $\\int A(x)dx$.', 'Targets the “forgot to square” mistake for squares.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Cross-sections perpendicular to the x-axis; squares.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_VOLUME_CROSS_SECTIONS',
  supporting_skill_ids = ARRAY['SK_GEOMETRY_AREA'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q7';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_VOLUME_CROSS_SECTIONS', 'SK_GEOMETRY_AREA'],
  error_tags = ARRAY['E_FORGET_SQUARE', 'E_RADIUS_DIAMETER'],
  prompt = 'The base of a solid is the region between $y=1$ and $y=x^2$ for $-1\\le x\\le 1$. Cross-sections perpendicular to the $x$-axis are semicircles whose diameter runs from $y=x^2$ to $y=1$. Which integral gives the volume?',
  latex = 'The base of a solid is the region between $y=1$ and $y=x^2$ for $-1\\le x\\le 1$. Cross-sections perpendicular to the $x$-axis are semicircles whose diameter runs from $y=x^2$ to $y=1$. Which integral gives the volume?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\int_{-1}^1 \\frac{\\pi}{2}(1-x^2)^2\\,dx$','explanation','This uses diameter as radius; radius should be $(1-x^2)/2$.'),
    jsonb_build_object('id','B','text','$\\int_{-1}^1 \\frac{\\pi}{8}(1-x^2)^2\\,dx$','explanation','Correct: semicircle area is $\\frac12\\pi\\left(\\frac{1-x^2}{2}\\right)^2=\\frac{\\pi}{8}(1-x^2)^2$.'),
    jsonb_build_object('id','C','text','$\\int_{-1}^1 \\pi(1-x^2)\\,dx$','explanation','This does not match semicircle area scaling.'),
    jsonb_build_object('id','D','text','$\\int_0^1 \\frac{\\pi}{8}(1-x^2)^2\\,dx$','explanation','This uses half the interval but does not multiply by 2 for symmetry.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Diameter is $d(x)=1-x^2$, so radius is $r(x)=\\frac{1-x^2}{2}$. Semicircle area is\n$$A(x)=\\frac12\\pi r(x)^2=\\frac12\\pi\\left(\\frac{1-x^2}{2}\\right)^2=\\frac{\\pi}{8}(1-x^2)^2.$$',
  recommendation_reasons = ARRAY['Targets diameter-vs-radius mistakes.', 'Reinforces constant factors for semicircle area.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Cross-sections: semicircles (diameter given).',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_VOLUME_CROSS_SECTIONS',
  supporting_skill_ids = ARRAY['SK_GEOMETRY_AREA'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q8';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 120,
  skill_tags = ARRAY['SK_VOLUME_DISC', 'SK_SETUP_INTEGRAL'],
  error_tags = ARRAY['E_WRONG_VARIABLE_DYDX', 'E_FORGET_SQUARE'],
  prompt = 'The region under $y=2-x$ above the $x$-axis for $0\\le x\\le 2$ is shown in 8.0-UT-Q9.png. It is revolved about the $y$-axis. Which integral gives the volume using the disc/washer method?',
  latex = 'The region under $y=2-x$ above the $x$-axis for $0\\le x\\le 2$ is shown in 8.0-UT-Q9.png. It is revolved about the $y$-axis. Which integral gives the volume using the disc/washer method?\n\n![8.0-UT-Q9](8.0-UT-Q9.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\pi\\int_0^2(2-y)^2\\,dy$','explanation','Correct: using discs perpendicular to the $y$-axis requires $dy$ and radius $x=2-y$.'),
    jsonb_build_object('id','B','text','$\\pi\\int_0^2(2-x)^2\\,dx$','explanation','This treats $2-x$ as a radius about the $y$-axis while integrating $dx$, which is not the disc setup for this axis.'),
    jsonb_build_object('id','C','text','$2\\pi\\int_0^2 x(2-x)\\,dx$','explanation','This is the shell method setup, not discs/washers.'),
    jsonb_build_object('id','D','text','$\\pi\\int_0^2(2-y)\\,dy$','explanation','Radius must be squared for volume.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Write the boundary as $x=2-y$ for $0\\le y\\le 2$. Revolving about the $y$-axis gives discs of radius $R(y)=2-y$:\n$$V=\\pi\\int_0^2(2-y)^2\\,dy.$$',
  recommendation_reasons = ARRAY['Checks correct variable choice for washers about a vertical axis.', 'Targets missing-square and wrong-method errors.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Disc method about the y-axis prefers $dy$ when $x$ is a function of $y$.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_VOLUME_DISC',
  supporting_skill_ids = ARRAY['SK_SETUP_INTEGRAL'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q9';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_VOLUME_WASHER', 'SK_SETUP_INTEGRAL'],
  error_tags = ARRAY['E_WRONG_VARIABLE_DYDX', 'E_WRONG_RADIUS', 'E_FORGET_SQUARE'],
  prompt = 'The region under $y=x^2$ above the $x$-axis on $0\\le x\\le 1$ is shown in 8.0-UT-Q10.png. It is revolved about the vertical line $x=1$. Which integral gives the volume using washers?',
  latex = 'The region under $y=x^2$ above the $x$-axis on $0\\le x\\le 1$ is shown in 8.0-UT-Q10.png. It is revolved about the vertical line $x=1$. Which integral gives the volume using washers?\n\n![8.0-UT-Q10](8.0-UT-Q10.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\pi\\int_0^1(1-x)^2\\,dx$','explanation','This uses $dx$ with a vertical axis; washer slices should be horizontal ($dy$).'),
    jsonb_build_object('id','B','text','$\\pi\\int_0^1(1-\\sqrt{y})^2\\,dy$','explanation','Correct: at height $y$, the curve gives $x=\\sqrt{y}$ and radius is $1-\\sqrt{y}$.'),
    jsonb_build_object('id','C','text','$2\\pi\\int_0^1(1-x)(x^2)\\,dx$','explanation','This is a shell method setup, not washers.'),
    jsonb_build_object('id','D','text','$\\pi\\int_0^1(1-y)^2\\,dy$','explanation','The radius is horizontal distance $1-\\sqrt{y}$, not $1-y$.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Washers about a vertical line use $dy$. Since $y=x^2$, we have $x=\\sqrt{y}$ for $0\\le y\\le 1$. The radius to $x=1$ is $R(y)=1-\\sqrt{y}$, so\n$$V=\\pi\\int_0^1(1-\\sqrt{y})^2\\,dy.$$',
  recommendation_reasons = ARRAY['Forces correct slice direction for washers about a vertical line.', 'Targets wrong-radius-in-terms-of-$y$ errors.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Washer method about $x=1$; convert $x$ to a function of $y$.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_VOLUME_WASHER',
  supporting_skill_ids = ARRAY['SK_SETUP_INTEGRAL'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q10';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 120,
  skill_tags = ARRAY['SK_VOLUME_WASHER', 'SK_SETUP_INTEGRAL'],
  error_tags = ARRAY['E_WRONG_RADIUS', 'E_FORGET_SQUARE'],
  prompt = 'The region between $y=x$ and $y=x^2$ on $0\\le x\\le 1$ is revolved about the $x$-axis. Which integral gives the volume?',
  latex = 'The region between $y=x$ and $y=x^2$ on $0\\le x\\le 1$ is revolved about the $x$-axis. Which integral gives the volume?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\pi\\int_0^1(x-x^2)\\,dx$','explanation','This is an area-style integrand; volume needs squared radii.'),
    jsonb_build_object('id','B','text','$\\pi\\int_0^1(x^2-x^4)\\,dx$','explanation','Correct: outer radius $R=x$, inner radius $r=x^2$, so $R^2-r^2=x^2-x^4$.'),
    jsonb_build_object('id','C','text','$\\pi\\int_0^1(x^4-x^2)\\,dx$','explanation','Outer and inner radii are reversed, giving a negative integrand.'),
    jsonb_build_object('id','D','text','$2\\pi\\int_0^1 x(x-x^2)\\,dx$','explanation','This is not a washer setup; it resembles a shell expression but does not match the geometry.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Washer method about the $x$-axis:\n$$V=\\pi\\int_0^1\\big(R^2-r^2\\big)dx=\\pi\\int_0^1(x^2-x^4)dx.$$',
  recommendation_reasons = ARRAY['Checks identifying outer vs inner radius.', 'Targets forgetting to square radii.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Standard washer setup about the x-axis.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_VOLUME_WASHER',
  supporting_skill_ids = ARRAY['SK_SETUP_INTEGRAL'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q11';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_VOLUME_WASHER', 'SK_SETUP_INTEGRAL'],
  error_tags = ARRAY['E_WRONG_RADIUS', 'E_FORGET_SQUARE', 'E_LIMITS_SWAP'],
  prompt = 'The region between $y=x$ and $y=x^2$ on $0\\le x\\le 1$ is shown in 8.0-UT-Q12.png. It is revolved about $y=3$. Which integral gives the volume?',
  latex = 'The region between $y=x$ and $y=x^2$ on $0\\le x\\le 1$ is shown in 8.0-UT-Q12.png. It is revolved about $y=3$. Which integral gives the volume?\n\n![8.0-UT-Q12](8.0-UT-Q12.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\pi\\int_0^1\\big((3-x)^2-(3-x^2)^2\\big)dx$','explanation','This reverses outer and inner radii; must have $R\\ge r$.'),
    jsonb_build_object('id','B','text','$\\pi\\int_0^1\\big((3-x^2)^2-(3-x)^2\\big)dx$','explanation','Correct: outer radius uses the lower curve $y=x^2$ so $R=3-x^2$, inner uses $y=x$ so $r=3-x$.'),
    jsonb_build_object('id','C','text','$\\pi\\int_0^1\\big((3-x^2)-(3-x)\\big)dx$','explanation','Missing squares on radii.'),
    jsonb_build_object('id','D','text','$2\\pi\\int_0^1 (3-x)(x-x^2)dx$','explanation','This is not the washer formula for rotation about a horizontal line.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Distances to $y=3$ give radii. Since $x^2\\le x$ on $[0,1]$, the lower curve is $y=x^2$ and is farther from $y=3$, so $R=3-x^2$ and $r=3-x$.\n$$V=\\pi\\int_0^1\\left((3-x^2)^2-(3-x)^2\\right)dx.$$',
  recommendation_reasons = ARRAY['Targets shifted-axis washer radii.', 'Prevents swapping outer/inner radii.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Washers about $y=3$ with vertical slices ($dx$).',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_VOLUME_WASHER',
  supporting_skill_ids = ARRAY['SK_SETUP_INTEGRAL'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q12';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 5,
  target_time_seconds = 180,
  skill_tags = ARRAY['SK_ARC_LENGTH', 'SK_FORMULA_RECALL'],
  error_tags = ARRAY['E_ARC_LENGTH_MISSING_SQRT', 'E_WRONG_DERIVATIVE_ORDER'],
  prompt = 'For a smooth curve $y=f(x)$ on $[a,b]$, which expression gives the arc length?',
  latex = 'For a smooth curve $y=f(x)$ on $[a,b]$, which expression gives the arc length?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\int_a^b\\left(1+(f''(x))^2\\right)dx$','explanation','Missing the square root; arc length requires $\\sqrt{\\cdot}$.'),
    jsonb_build_object('id','B','text','$\\int_a^b\\sqrt{1+f''(x)}\\,dx$','explanation','Derivative must be squared inside the square root.'),
    jsonb_build_object('id','C','text','$\\int_a^b\\sqrt{1+(f''(x))^2}\\,dx$','explanation','Correct: $L=\\int_a^b\\sqrt{1+(f''(x))^2}\\,dx$.'),
    jsonb_build_object('id','D','text','$\\int_a^b\\sqrt{1+(f''''''(x))^2}\\,dx$','explanation','Arc length uses $f''(x)$, not $f''''''(x)$.')
  ),
  correct_option_id = 'C',
  tolerance = 0.0010,
  explanation = 'Arc length for $y=f(x)$ on $[a,b]$ is\n$$L=\\int_a^b\\sqrt{1+(f''(x))^2}\\,dx.$$',
  recommendation_reasons = ARRAY['BC arc-length core formula recognition.', 'Targets mixing $f\\''$ and $f\\''\\''$.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 5,
  mastery_weight = 1.20,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Arc length formula recognition.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_ARC_LENGTH',
  supporting_skill_ids = ARRAY['SK_FORMULA_RECALL'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q13';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 90,
  skill_tags = ARRAY['SK_MOTION_V_FROM_A', 'SK_ACCUMULATION'],
  error_tags = ARRAY['E_ACCUMULATION_CONFUSE', 'E_SIGN_ERROR'],
  prompt = 'A particle has acceleration $a(t)=6t$ and velocity $v(0)=-2$. What is $v(2)$?',
  latex = 'A particle has acceleration $a(t)=6t$ and velocity $v(0)=-2$. What is $v(2)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$10$','explanation','Correct: $v(2)=v(0)+\\int_0^2 6t\\,dt=-2+12=10$.'),
    jsonb_build_object('id','B','text','$4$','explanation','This comes from miscomputing $\\int_0^2 6t\\,dt$.'),
    jsonb_build_object('id','C','text','$-14$','explanation','Sign error: you add the accumulated acceleration.'),
    jsonb_build_object('id','D','text','$-2$','explanation','This ignores the acceleration over time.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Velocity is initial plus accumulated acceleration:\n$$v(2)=v(0)+\\int_0^2 a(t)dt=-2+\\int_0^2 6t\\,dt=-2+[3t^2]_0^2=-2+12=10.$$',
  recommendation_reasons = ARRAY['Connects acceleration to velocity via a definite integral.', 'Targets missing-initial-condition errors.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 0.90,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Motion: acceleration to velocity with initial value.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_MOTION_V_FROM_A',
  supporting_skill_ids = ARRAY['SK_ACCUMULATION'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q14';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = TRUE,
  difficulty = 3,
  target_time_seconds = 120,
  skill_tags = ARRAY['SK_FTC', 'SK_ACCUMULATION'],
  error_tags = ARRAY['E_ACCUMULATION_CONFUSE', 'E_FTC_MISAPPLY'],
  prompt = 'Let $F(x)=\\int_2^x \\sqrt{1+t^4}\\,dt$. Which statement is correct about $F''(x)$ and $F(2)$?',
  latex = 'Let $F(x)=\\int_2^x \\sqrt{1+t^4}\\,dt$. Which statement is correct about $F''(x)$ and $F(2)$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$F''(x)=\\sqrt{1+x^4}$ and $F(2)=0$','explanation','Correct by the Fundamental Theorem of Calculus and $\\int_2^2=0$.'),
    jsonb_build_object('id','B','text','$F''(x)=\\sqrt{1+2^4}$ and $F(2)=0$','explanation','Derivative depends on $x$, not the lower limit.'),
    jsonb_build_object('id','C','text','$F''(x)=\\int_2^x \\sqrt{1+t^4}\\,dt$ and $F(2)=2$','explanation','Confuses the function with its derivative and mis-evaluates $F(2)$.'),
    jsonb_build_object('id','D','text','$F''(x)=\\frac{1}{2}(1+x^4)^{-1/2}$ and $F(2)=0$','explanation','This differentiates the integrand instead of using FTC.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'By FTC, if $F(x)=\\int_2^x g(t)dt$, then $F''(x)=g(x)$. Here $g(x)=\\sqrt{1+x^4}$, and $F(2)=\\int_2^2 g(t)dt=0$.',
  recommendation_reasons = ARRAY['Checks FTC “derivative of accumulation” idea.', 'Targets differentiating the integrand by mistake.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'FTC: accumulation function derivative and initial value.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_FTC',
  supporting_skill_ids = ARRAY['SK_ACCUMULATION'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q15';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_TOTAL_AREA', 'SK_SIGN_ANALYSIS'],
  error_tags = ARRAY['E_MISSING_ABS', 'E_INTERSECTION_MISSED'],
  prompt = 'The graph of $y=\\sin x$ on $[0,2\\pi]$ is shown in 8.0-UT-Q16.png. Which integral equals the total area between the curve and the $x$-axis on $[0,2\\pi]$?',
  latex = 'The graph of $y=\\sin x$ on $[0,2\\pi]$ is shown in 8.0-UT-Q16.png. Which integral equals the total area between the curve and the $x$-axis on $[0,2\\pi]$?\n\n![8.0-UT-Q16](8.0-UT-Q16.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\int_0^{2\\pi}\\sin x\\,dx$','explanation','This is net signed area; it cancels to $0$ on $[0,2\\pi]$.'),
    jsonb_build_object('id','B','text','$\\int_0^{2\\pi}|\\sin x|\\,dx$','explanation','Correct: total area uses absolute value (or splitting at zeros).'),
    jsonb_build_object('id','C','text','$\\int_0^{\\pi}\\sin x\\,dx$','explanation','This only covers half the interval.'),
    jsonb_build_object('id','D','text','$\\int_0^{\\pi}|\\sin x|\\,dx$','explanation','This is only half the total area.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Because $\\sin x$ changes sign, total area is\n$$A=\\int_0^{2\\pi}|\\sin x|\\,dx.$$',
  recommendation_reasons = ARRAY['Separates total area from signed integral.', 'Targets missing absolute value across sign changes.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Total area requires absolute value.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_TOTAL_AREA',
  supporting_skill_ids = ARRAY['SK_SIGN_ANALYSIS'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q16';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 2,
  target_time_seconds = 90,
  skill_tags = ARRAY['SK_AVG_VALUE', 'SK_INTERPRET_UNITS'],
  error_tags = ARRAY['E_AVG_VALUE_DIVIDE', 'E_MISSING_ABS'],
  prompt = 'A car’s speed is $v(t)$ miles/hour for $0\\le t\\le 2$ hours. Which expression gives the car’s average speed on $[0,2]$?',
  latex = 'A car’s speed is $v(t)$ miles/hour for $0\\le t\\le 2$ hours. Which expression gives the car’s average speed on $[0,2]$?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\int_0^2 |v(t)|\\,dt$','explanation','This is total distance, not average speed.'),
    jsonb_build_object('id','B','text','$\\frac{1}{2}\\int_0^2 |v(t)|\\,dt$','explanation','Correct: average speed is total distance divided by total time ($2$ hours).'),
    jsonb_build_object('id','C','text','$\\frac{1}{2}\\int_0^2 v(t)\\,dt$','explanation','This uses signed velocity; speed must be nonnegative.'),
    jsonb_build_object('id','D','text','$\\int_0^2 v(t)\\,dt$','explanation','This is displacement (signed), not average speed.')
  ),
  correct_option_id = 'B',
  tolerance = 0.0010,
  explanation = 'Average speed is distance divided by time:\n$$\\text{Avg speed}=\\frac{1}{2}\\int_0^2 |v(t)|dt.$$',
  recommendation_reasons = ARRAY['Connects average value to units (distance/time).', 'Targets forgetting absolute value for speed.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 0.90,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Average speed as average value of speed.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_AVG_VALUE',
  supporting_skill_ids = ARRAY['SK_INTERPRET_UNITS'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q17';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 3,
  target_time_seconds = 120,
  skill_tags = ARRAY['SK_AREA_BETWEEN_DX', 'SK_INTERSECTIONS'],
  error_tags = ARRAY['E_INTERSECTION_MISSED', 'E_LIMITS_SWAP', 'E_SIGN_ERROR'],
  prompt = 'Find the area between $y=2x$ and $y=x^2$ from their left intersection to their right intersection.',
  latex = 'Find the area between $y=2x$ and $y=x^2$ from their left intersection to their right intersection.',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\int_0^2(2x-x^2)\\,dx$','explanation','Correct: intersections are $x=0,2$, and $2x$ is above $x^2$ on $[0,2]$.'),
    jsonb_build_object('id','B','text','$\\int_0^2(x^2-2x)\\,dx$','explanation','Top-bottom reversed.'),
    jsonb_build_object('id','C','text','$\\int_{-2}^0(2x-x^2)\\,dx$','explanation','Wrong bounds; the intersections are $0$ and $2$.'),
    jsonb_build_object('id','D','text','$\\int_0^2|2x-x^2|\\,dx$','explanation','Absolute value is unnecessary since $2x-x^2\\ge 0$ on $[0,2]$.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'Solve $x^2=2x\\Rightarrow x=0,2$. Since $2x\\ge x^2$ on $[0,2]$, area is\n$$A=\\int_0^2(2x-x^2)dx.$$',
  recommendation_reasons = ARRAY['Reinforces intersection solving.', 'Checks correct top-minus-bottom ordering.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1.00,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Area between a line and parabola.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_AREA_BETWEEN_DX',
  supporting_skill_ids = ARRAY['SK_INTERSECTIONS'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q18';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 5,
  target_time_seconds = 180,
  skill_tags = ARRAY['SK_ARC_LENGTH', 'SK_SETUP_INTEGRAL'],
  error_tags = ARRAY['E_ARC_LENGTH_MISSING_SQRT', 'E_WRONG_DERIVATIVE_ORDER', 'E_LIMITS_SWAP'],
  prompt = 'The curve $y=\\ln x$ on $[1,e]$ is shown in 8.0-UT-Q19.png. Which integral gives the exact arc length from $x=1$ to $x=e$?',
  latex = 'The curve $y=\\ln x$ on $[1,e]$ is shown in 8.0-UT-Q19.png. Which integral gives the exact arc length from $x=1$ to $x=e$?\n\n![8.0-UT-Q19](8.0-UT-Q19.png)',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\int_1^e\\left(1+\\frac{1}{x^2}\\right)dx$','explanation','Missing the square root in the arc length formula.'),
    jsonb_build_object('id','B','text','$\\int_1^e\\sqrt{1+\\frac{1}{x}}\\,dx$','explanation','Uses $1/x$ instead of $(1/x)^2$ inside the square root.'),
    jsonb_build_object('id','C','text','$\\int_1^e\\sqrt{1+\\frac{1}{x^2}}\\,dx$','explanation','Correct: for $y=\\ln x$, $y''=1/x$, so $\\sqrt{1+(y'')^2}=\\sqrt{1+1/x^2}$.'),
    jsonb_build_object('id','D','text','$\\int_0^1\\sqrt{1+\\frac{1}{x^2}}\\,dx$','explanation','Wrong bounds; the interval is $[1,e]$.')
  ),
  correct_option_id = 'C',
  tolerance = 0.0010,
  explanation = 'For $y=f(x)$, arc length is $\\int_a^b\\sqrt{1+(f''(x))^2}dx$. Here $f(x)=\\ln x$ so $f''(x)=1/x$, giving\n$$L=\\int_1^e\\sqrt{1+\\frac{1}{x^2}}\\,dx.$$',
  recommendation_reasons = ARRAY['Arc length setup with a standard derivative.', 'Targets missing square root and wrong derivative order.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 5,
  mastery_weight = 1.20,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Arc length setup for $y=\\ln x$.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_ARC_LENGTH',
  supporting_skill_ids = ARRAY['SK_SETUP_INTEGRAL'],
  prompt_type = 'text_and_image',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q19';


UPDATE public.questions
SET
  course = 'Both',
  topic = 'Both_AppIntegration',
  sub_topic_id = 'unit_test',
  section_id = 'unit_test',
  type = 'MCQ',
  calculator_allowed = FALSE,
  difficulty = 4,
  target_time_seconds = 150,
  skill_tags = ARRAY['SK_VOLUME_WASHER', 'SK_SETUP_INTEGRAL'],
  error_tags = ARRAY['E_FORGET_SQUARE', 'E_WRONG_VARIABLE_DYDX'],
  prompt = 'The region bounded by $x=y$ and $x=y^2$ for $0\\le y\\le 1$ is revolved about the $y$-axis. Which integral gives the volume using washers?',
  latex = 'The region bounded by $x=y$ and $x=y^2$ for $0\\le y\\le 1$ is revolved about the $y$-axis. Which integral gives the volume using washers?',
  options = jsonb_build_array(
    jsonb_build_object('id','A','text','$\\pi\\int_0^1 (y^2-y^4)\\,dy$','explanation','Correct: $R=y$ and $r=y^2$, so $V=\\pi\\int_0^1(R^2-r^2)dy=\\pi\\int_0^1(y^2-y^4)dy$.'),
    jsonb_build_object('id','B','text','$\\pi\\int_0^1 (y^4-y^2)\\,dy$','explanation','Outer/inner reversed gives negative integrand.'),
    jsonb_build_object('id','C','text','$2\\pi\\int_0^1 y(y-y^2)\\,dy$','explanation','This is a shell-method form, not washers.'),
    jsonb_build_object('id','D','text','$\\pi\\int_0^1 (y-y^2)\\,dy$','explanation','Missing squares on radii.')
  ),
  correct_option_id = 'A',
  tolerance = 0.0010,
  explanation = 'With $dy$ washers about the $y$-axis, radii are horizontal: $R=y$ and $r=y^2$.\n$$V=\\pi\\int_0^1\\left(y^2-y^4\\right)dy.$$',
  recommendation_reasons = ARRAY['Checks washer setup in $dy$ about the y-axis.', 'Targets missing-square and shell-vs-washer confusion.'],
  status = 'published',
  version = version + 1,
  reasoning_level = 4,
  mastery_weight = 1.10,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Washers with $dy$ about the y-axis.',
  weight_primary = 0.70,
  weight_supporting = 0.30,
    primary_skill_id = 'SK_VOLUME_WASHER',
  supporting_skill_ids = ARRAY['SK_SETUP_INTEGRAL'],
  prompt_type = 'text',
  representation_type = 'symbolic',
  topic_id = 'Both_AppIntegration',
  updated_at = NOW()
WHERE title = '8.0-UT-Q20';

COMMIT;
