-- Update Unit 1 Limits Questions Part 2 (Chapters 1.5 & 1.6)
BEGIN;

-- Updating U1C15_Q1_Polynomial_Limit_Substitution (26c57f87-799d-4e6a-a786-96f77b64d5c9)
UPDATE public.questions SET
  prompt = 'Evaluate the limit: $$\lim_{x\to 3}\left(2x^2-5x+1\right).$$',
  latex = '$$\lim_{x\to 3}(2x^2-5x+1)$$',
  options = '[{"id": "A", "text": "$4$", "explanation": "Direct substitution gives $2(3^2)-5(3)+1=18-15+1=4$."}, {"id": "B", "text": "$6$", "explanation": "This results from miscomputing $18-15+1$."}, {"id": "C", "text": "$-4$", "explanation": "This comes from sign errors when combining terms."}, {"id": "D", "text": "Does not exist", "explanation": "Polynomials are continuous everywhere, so the limit exists."}]'::jsonb,
  explanation = 'Because polynomials are continuous, $$\lim_{x\to 3}(2x^2-5x+1)=2\cdot 3^2-5\cdot 3+1=4.$$',
  micro_explanations = '{"A": "Use continuity of polynomials and substitute $x=3$.", "B": "Arithmetic error.", "C": "Sign error.", "D": "Continuity guarantees existence."}'::jsonb,
  correct_option_id = 'A',
  skill_tags = ARRAY['limit_laws_evaluate'],
  error_tags = ARRAY['substitution_arithmetic_slip', 'misapply_limit_laws'],
  recommendation_reasons = ARRAY['Reinforces that polynomial limits use direct substitution.', 'Targets common arithmetic and sign errors.'],
  primary_skill_id = 'limit_laws_evaluate',
  supporting_skill_ids = '{}',
  topic_id = 'Both_Limits',
  sub_topic_id = '1.5',
  section_id = '1.5',
  difficulty = 1,
  target_time_seconds = 60,
  updated_at = NOW(),
  title = 'U1C15_Q1_Polynomial_Limit_Substitution',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 1,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Focus: direct substitution via limit laws for polynomials.',
  weight_primary = 1.0,
  weight_supporting = 0.0,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE id = '26c57f87-799d-4e6a-a786-96f77b64d5c9';

-- Updating U1C15_Q2_GraphBased_Limit_Laws (ee05cd56-783f-48e2-b2a5-3134c3b55c37)
UPDATE public.questions SET
  prompt = 'Using the graph of $f$ and $g$ (see image), evaluate $$\lim_{x\to 1}\left(3f(x)-2g(x)\right).$$',
  latex = '$$\lim_{x\to 1}(3f(x)-2g(x))$$',
  options = '[{"id": "A", "text": "$4$", "explanation": "This uses incorrect graph reading for one of the limits."}, {"id": "B", "text": "$8$", "explanation": "This uses the correct limits from the graph: $f\\to 2$, $g\\to -1$."}, {"id": "C", "text": "$-8$", "explanation": "This comes from sign mistakes when computing $-2g$."}, {"id": "D", "text": "Does not exist", "explanation": "Both $f$ and $g$ approach finite values at $x=1$, so the limit exists."}]'::jsonb,
  explanation = 'From the graph, $$\lim_{x\to 1}f(x)=2,\quad \lim_{x\to 1}g(x)=-1.$$ By limit laws, $$\lim_{x\to 1}(3f(x)-2g(x))=3\cdot 2-2\cdot(-1)=6+2=8.$$',
  micro_explanations = '{"A": "At least one limit was read incorrectly from the graph.", "B": "Use $3\\lim f-2\\lim g$ with $\\lim f=2$, $\\lim g=-1$.", "C": "Sign error: $-2(-1)=+2$, not $-2$.", "D": "Finite one-sided approaches match, so it exists."}'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['limit_laws_combine', 'graphical_limit_interpretation'],
  error_tags = ARRAY['read_graph_wrong_value', 'misapply_limit_laws'],
  recommendation_reasons = ARRAY['Connects algebraic limit laws to graphical limit values.', 'Builds reliability reading a limit (not function value) from a graph.'],
  primary_skill_id = 'limit_laws_combine',
  supporting_skill_ids = ARRAY['graphical_limit_interpretation'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.5',
  section_id = '1.5',
  difficulty = 3,
  target_time_seconds = 110,
  updated_at = NOW(),
  title = 'U1C15_Q2_GraphBased_Limit_Laws',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 3,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Image required: graph gives the approaching values of f and g at x=1.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text_and_image',
  representation_type = 'symbolic'
WHERE id = 'ee05cd56-783f-48e2-b2a5-3134c3b55c37';

-- Updating U1C15_Q3_Combine_Given_Limits (5f960cac-a4ff-458c-a372-995fcb81d7f9)
UPDATE public.questions SET
  prompt = 'Suppose $$\lim_{x\to 2}f(x)=5\quad\text{and}\quad \lim_{x\to 2}g(x)=-3.$$ Evaluate $$\lim_{x\to 2}\frac{(f(x))^2}{g(x)+7}.$$',
  latex = '$$\lim_{x\to 2}\frac{(f(x))^2}{g(x)+7}$$',
  options = '[{"id": "A", "text": "$\\dfrac{10}{4}$", "explanation": "This treats $(f(x))^2$ as $2f(x)$, which is incorrect."}, {"id": "B", "text": "$\\dfrac{25}{4}$", "explanation": "Correct: $\\dfrac{(\\lim f)^2}{\\lim(g+7)}=\\dfrac{25}{4}$."}, {"id": "C", "text": "$\\dfrac{25}{-10}$", "explanation": "This adds $7$ incorrectly to the numerator or mishandles the denominator limit."}, {"id": "D", "text": "Does not exist", "explanation": "The denominator limit is $-3+7=4\\ne 0$, so the limit exists."}]'::jsonb,
  explanation = 'By limit laws and continuity of squaring and addition, $$\lim_{x\to 2}\frac{(f(x))^2}{g(x)+7}=\frac{(\lim f(x))^2}{\lim(g(x)+7)}=\frac{5^2}{-3+7}=\frac{25}{4}.$$',
  micro_explanations = '{"A": "Squaring is not doubling.", "B": "Compute $(5)^2$ and divide by $4$.", "C": "Denominator limit is $4$, not $-10$.", "D": "Denominator limit is nonzero."}'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['limit_laws_parametric'],
  error_tags = ARRAY['misapply_limit_laws', 'distribute_powers_incorrectly'],
  recommendation_reasons = ARRAY['Practices combining limits with algebraic operations and powers.', 'Targets common misconception: squaring vs doubling.'],
  primary_skill_id = 'limit_laws_parametric',
  supporting_skill_ids = '{}',
  topic_id = 'Both_Limits',
  sub_topic_id = '1.5',
  section_id = '1.5',
  difficulty = 2,
  target_time_seconds = 90,
  updated_at = NOW(),
  title = 'U1C15_Q3_Combine_Given_Limits',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 2,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Limit laws with given component limits; denominator nonzero check.',
  weight_primary = 1.0,
  weight_supporting = 0.0,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE id = '5f960cac-a4ff-458c-a372-995fcb81d7f9';

-- Updating U1C15_Q4_Quotient_Denominator_Zero (aaecf8d8-17f7-446d-938e-2c6bdebacde1)
UPDATE public.questions SET
  prompt = 'Evaluate (or state that it does not exist): $$\lim_{x\to 2}\frac{x+1}{x^2-4}.$$',
  latex = '$$\lim_{x\to 2}\frac{x+1}{x^2-4}$$',
  options = '[{"id": "A", "text": "$\\dfrac{3}{0}$", "explanation": "A limit is not written as division by zero; you must conclude behavior or nonexistence."}, {"id": "B", "text": "$\\dfrac{3}{4}$", "explanation": "This incorrectly substitutes $x=2$ in the denominator as $4$ rather than $0$."}, {"id": "C", "text": "Does not exist (infinite behavior)", "explanation": "Correct: denominator $\\to 0$ while numerator $\\to 3\\ne 0$, so the limit is unbounded."}, {"id": "D", "text": "$0$", "explanation": "This would be true only if the numerator also approached $0$ appropriately."}]'::jsonb,
  explanation = 'Factor the denominator: $$x^2-4=(x-2)(x+2).$$ As $x\to 2$, the numerator $x+1\to 3$ while the denominator $(x-2)(x+2)\to 0\cdot 4=0$. Since the numerator approaches a nonzero number and the denominator approaches $0$, the expression becomes unbounded, so the two-sided limit does not exist (infinite behavior).',
  micro_explanations = '{"A": "A limit cannot be left as \u201cdivide by zero.\u201d", "B": "Denominator at $2$ is $0$, not $4$.", "C": "Nonzero over $0$ implies unbounded behavior.", "D": "Would require numerator $\\to 0$."}'::jsonb,
  correct_option_id = 'C',
  skill_tags = ARRAY['limit_laws_existence_check', 'asymptotic_behavior_reasoning'],
  error_tags = ARRAY['cancel_zero_improperly', 'assume_dne_when_it_exists'],
  recommendation_reasons = ARRAY['Builds habit of checking denominator limits for quotient forms.', 'Distinguishes DNE due to unbounded behavior from removable cases.'],
  primary_skill_id = 'limit_laws_existence_check',
  supporting_skill_ids = ARRAY['asymptotic_behavior_reasoning'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.5',
  section_id = '1.5',
  difficulty = 4,
  target_time_seconds = 140,
  updated_at = NOW(),
  title = 'U1C15_Q4_Quotient_Denominator_Zero',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 4,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Quotient law with denominator approaching 0; interpret as unbounded/DNE.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE id = 'aaecf8d8-17f7-446d-938e-2c6bdebacde1';

-- Updating U1C15_Q5_Rational_Substitution_NonzeroDen (ed9ed524-ace7-4e8f-831d-f9afe6fc1812)
UPDATE public.questions SET
  prompt = 'Evaluate the limit: $$\lim_{x\to -1}\frac{x^2+3x+2}{x+2}.$$',
  latex = '$$\lim_{x\to -1}\frac{x^2+3x+2}{x+2}$$',
  options = '[{"id": "A", "text": "$0$", "explanation": "This comes from incorrectly making the numerator $0$ at $x=-1$."}, {"id": "B", "text": "$1$", "explanation": "This results from an arithmetic slip in the numerator."}, {"id": "C", "text": "$-1$", "explanation": "Correct: direct substitution gives $\\dfrac{(-1)^2+3(-1)+2}{-1+2}=\\dfrac{0}{1}=0$, so this is not correct."}, {"id": "D", "text": "$0$", "explanation": "Correct: $(-1)^2+3(-1)+2=1-3+2=0$ and denominator is $1$."}]'::jsonb,
  explanation = 'Since the denominator approaches $-1+2=1\ne 0$, use direct substitution: $$\frac{(-1)^2+3(-1)+2}{-1+2}=\frac{1-3+2}{1}=0.$$',
  micro_explanations = '{"A": "This is actually the correct numeric value but not justified by a wrong reason.", "B": "Numerator evaluates to $0$, not $1$.", "C": "The computation shown contradicts the choice.", "D": "Denominator nonzero, so substitute directly."}'::jsonb,
  correct_option_id = 'D',
  skill_tags = ARRAY['limit_laws_evaluate', 'simplify_algebraic_expressions'],
  error_tags = ARRAY['substitution_arithmetic_slip', 'misapply_limit_laws'],
  recommendation_reasons = ARRAY['Reinforces direct substitution when denominator limit is nonzero.', 'Highlights careful arithmetic in rational expressions.'],
  primary_skill_id = 'limit_laws_evaluate',
  supporting_skill_ids = ARRAY['simplify_algebraic_expressions'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.5',
  section_id = '1.5',
  difficulty = 2,
  target_time_seconds = 85,
  updated_at = NOW(),
  title = 'U1C15_Q5_Rational_Substitution_NonzeroDen',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 2,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Limit laws + substitution; denominator nonzero check.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE id = 'ed9ed524-ace7-4e8f-831d-f9afe6fc1812';

-- Updating U1C16_Q1_Factor_Cancel_Basic (517f0d4c-d735-47fc-bbac-90231c61b275)
UPDATE public.questions SET
  prompt = 'Evaluate the limit: $$\lim_{x\to 2}\frac{x^2-4}{x-2}.$$',
  latex = '$$\lim_{x\to 2}\frac{x^2-4}{x-2}$$',
  options = '[{"id": "A", "text": "$2$", "explanation": "This comes from canceling incorrectly or substituting too early."}, {"id": "B", "text": "$4$", "explanation": "Correct: factor $x^2-4=(x-2)(x+2)$, cancel, then substitute."}, {"id": "C", "text": "$0$", "explanation": "This results from substituting $x=2$ before simplifying and getting $0/0$."}, {"id": "D", "text": "Does not exist", "explanation": "This is removable after factoring; the limit exists."}]'::jsonb,
  explanation = 'Factor: $$\frac{x^2-4}{x-2}=\frac{(x-2)(x+2)}{x-2}=x+2\quad (x\ne 2).$$ Thus $$\lim_{x\to 2}\frac{x^2-4}{x-2}=\lim_{x\to 2}(x+2)=4.$$',
  micro_explanations = '{"A": "After canceling, you should get $x+2$, not $x$.", "B": "Cancel the common factor then substitute.", "C": "$0/0$ signals you must simplify first.", "D": "Removable discontinuity implies a finite limit."}'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['limit_algebraic_manipulation_factor'],
  error_tags = ARRAY['cancel_zero_improperly', 'factorization_error'],
  recommendation_reasons = ARRAY['Core technique: factoring to remove $0/0$ indeterminate form.', 'Targets the common mistake of substituting before simplifying.'],
  primary_skill_id = 'limit_algebraic_manipulation_factor',
  supporting_skill_ids = '{}',
  topic_id = 'Both_Limits',
  sub_topic_id = '1.6',
  section_id = '1.6',
  difficulty = 2,
  target_time_seconds = 95,
  updated_at = NOW(),
  title = 'U1C16_Q1_Factor_Cancel_Basic',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 2,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Factoring to resolve indeterminate form $0/0$.',
  weight_primary = 1.0,
  weight_supporting = 0.0,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE id = '517f0d4c-d735-47fc-bbac-90231c61b275';

-- Updating U1C16_Q2_Rationalize_Sqrt_Classic (4ab23ec2-7fee-4ecc-a197-8b7d7573d46d)
UPDATE public.questions SET
  prompt = 'Evaluate the limit: $$\lim_{x\to 0}\frac{\sqrt{1+x}-1}{x}.$$',
  latex = '$$\lim_{x\to 0}\frac{\sqrt{1+x}-1}{x}$$',
  options = '[{"id": "A", "text": "$\\dfrac{1}{2}$", "explanation": "Correct: multiply by the conjugate to simplify."}, {"id": "B", "text": "$1$", "explanation": "This ignores the effect of the conjugate simplification."}, {"id": "C", "text": "$0$", "explanation": "This is from substituting immediately to get $0/0$ and guessing."}, {"id": "D", "text": "Does not exist", "explanation": "After rationalizing, the limit becomes finite."}]'::jsonb,
  explanation = 'Multiply by the conjugate: $$\frac{\sqrt{1+x}-1}{x}\cdot\frac{\sqrt{1+x}+1}{\sqrt{1+x}+1}=\frac{(1+x)-1}{x(\sqrt{1+x}+1)}=\frac{1}{\sqrt{1+x}+1}.$$ Then $$\lim_{x\to 0}\frac{1}{\sqrt{1+x}+1}=\frac{1}{1+1}=\frac{1}{2}.$$',
  micro_explanations = '{"A": "Rationalize to remove the radical in the numerator.", "B": "You must simplify before substituting.", "C": "$0/0$ means simplify, not guess.", "D": "The simplified form is continuous at $x=0$."}'::jsonb,
  correct_option_id = 'A',
  skill_tags = ARRAY['limit_algebraic_manipulation_rationalize', 'simplify_algebraic_expressions'],
  error_tags = ARRAY['rationalize_wrong_conjugate', 'cancel_zero_improperly'],
  recommendation_reasons = ARRAY['Canonical rationalization limit used frequently later.', 'Reinforces conjugate multiplication accuracy.'],
  primary_skill_id = 'limit_algebraic_manipulation_rationalize',
  supporting_skill_ids = ARRAY['simplify_algebraic_expressions'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.6',
  section_id = '1.6',
  difficulty = 4,
  target_time_seconds = 150,
  updated_at = NOW(),
  title = 'U1C16_Q2_Rationalize_Sqrt_Classic',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 4,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Rationalization via conjugate; avoid premature substitution.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE id = '4ab23ec2-7fee-4ecc-a197-8b7d7573d46d';

-- Updating U1C16_Q3_Rationalize_DiffOfRoots (ea511a78-2b62-4d07-9573-a16f6180335a)
UPDATE public.questions SET
  prompt = 'Evaluate the limit: $$\lim_{x\to 3}\frac{x-3}{\sqrt{x}-\sqrt{3}}.$$',
  latex = '$$\lim_{x\to 3}\frac{x-3}{\sqrt{x}-\sqrt{3}}$$',
  options = '[{"id": "A", "text": "$\\sqrt{3}$", "explanation": "This misses a factor of $2\\sqrt{3}$ from simplifying."}, {"id": "B", "text": "$2\\sqrt{3}$", "explanation": "Correct: multiply by the conjugate of the denominator."}, {"id": "C", "text": "$6$", "explanation": "This replaces $\\sqrt{3}$ with $3$ in the final expression."}, {"id": "D", "text": "$\\dfrac{1}{2\\sqrt{3}}$", "explanation": "This is the reciprocal of the correct simplified form."}]'::jsonb,
  explanation = 'Multiply by the conjugate: $$\frac{x-3}{\sqrt{x}-\sqrt{3}}\cdot\frac{\sqrt{x}+\sqrt{3}}{\sqrt{x}+\sqrt{3}}=\frac{(x-3)(\sqrt{x}+\sqrt{3})}{x-3}=\sqrt{x}+\sqrt{3}.$$ Then $$\lim_{x\to 3}(\sqrt{x}+\sqrt{3})=\sqrt{3}+\sqrt{3}=2\sqrt{3}.$$',
  micro_explanations = '{"A": "You should get $\\sqrt{x}+\\sqrt{3}$, not $\\sqrt{x}$.", "B": "Conjugate cancels $(x-3)$ cleanly.", "C": "Do not turn $\\sqrt{3}$ into $3$.", "D": "Not a reciprocal situation; simplify first."}'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['limit_algebraic_manipulation_rationalize'],
  error_tags = ARRAY['rationalize_wrong_conjugate', 'substitution_arithmetic_slip'],
  recommendation_reasons = ARRAY['Rationalization with radicals in denominator.', 'Checks symbolic precision with square roots.'],
  primary_skill_id = 'limit_algebraic_manipulation_rationalize',
  supporting_skill_ids = '{}',
  topic_id = 'Both_Limits',
  sub_topic_id = '1.6',
  section_id = '1.6',
  difficulty = 3,
  target_time_seconds = 125,
  updated_at = NOW(),
  title = 'U1C16_Q3_Rationalize_DiffOfRoots',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 3,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Conjugate technique; cancels a linear factor produced by difference of squares.',
  weight_primary = 1.0,
  weight_supporting = 0.0,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE id = 'ea511a78-2b62-4d07-9573-a16f6180335a';

-- Updating U1C16_Q4_DiffOfCubes_Cancel (93cff0de-5d7c-40ed-8492-2b741df23cad)
UPDATE public.questions SET
  prompt = 'Evaluate the limit: $$\lim_{x\to 1}\frac{x^3-1}{x-1}.$$',
  latex = '$$\lim_{x\to 1}\frac{x^3-1}{x-1}$$',
  options = '[{"id": "A", "text": "$1$", "explanation": "This comes from canceling incorrectly or substituting too early."}, {"id": "B", "text": "$2$", "explanation": "This is from factoring $x^3-1$ incorrectly."}, {"id": "C", "text": "$3$", "explanation": "Correct: $x^3-1=(x-1)(x^2+x+1)$, then substitute $x=1$."}, {"id": "D", "text": "Does not exist", "explanation": "This is removable; the limit exists."}]'::jsonb,
  explanation = 'Use the difference of cubes: $$x^3-1=(x-1)(x^2+x+1).$$ Then $$\frac{x^3-1}{x-1}=x^2+x+1\ (x\ne 1).$$ So $$\lim_{x\to 1}\frac{x^3-1}{x-1}=1^2+1+1=3.$$',
  micro_explanations = '{"A": "After canceling you should have $x^2+x+1$.", "B": "Difference of cubes factorization must be exact.", "C": "Cancel then substitute.", "D": "Removable discontinuity implies a finite limit."}'::jsonb,
  correct_option_id = 'C',
  skill_tags = ARRAY['limit_algebraic_manipulation_factor', 'polynomial_factorization'],
  error_tags = ARRAY['factorization_error', 'cancel_zero_improperly'],
  recommendation_reasons = ARRAY['Reinforces special factoring pattern (difference of cubes).', 'Builds fluency removing $0/0$ forms beyond quadratics.'],
  primary_skill_id = 'limit_algebraic_manipulation_factor',
  supporting_skill_ids = ARRAY['polynomial_factorization'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.6',
  section_id = '1.6',
  difficulty = 3,
  target_time_seconds = 120,
  updated_at = NOW(),
  title = 'U1C16_Q4_DiffOfCubes_Cancel',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 3,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Difference of cubes factoring to remove indeterminate form.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE id = '93cff0de-5d7c-40ed-8492-2b741df23cad';

-- Updating U1C16_Q5_FillTheHole_Continuity (51448cae-3144-4bde-b809-392cdfe4dfa2)
UPDATE public.questions SET
  prompt = 'A function has the graph shown (see image). What value should be defined at $x=3$ to make the function continuous at $x=3$?',
  latex = ' ',
  options = '[{"id": "A", "text": "$3$", "explanation": "This confuses the $x$-coordinate with the needed $y$-value."}, {"id": "B", "text": "$6$", "explanation": "Correct: the hole is at $(3,6)$, so set the function value to $6$."}, {"id": "C", "text": "$0$", "explanation": "This would create a jump from the approaching value shown on the graph."}, {"id": "D", "text": "No value works", "explanation": "A removable discontinuity can be fixed by defining the missing point to match the limit."}]'::jsonb,
  explanation = 'To make a function continuous at $x=3$, its value must equal the two-sided limit at $x=3$. The graph shows a removable hole at $(3,6)$, so $$\lim_{x\to 3}f(x)=6.$$ Define $f(3)=6$ to fill the hole and make the function continuous.',
  micro_explanations = '{"A": "Continuity needs a $y$-value, not the input $x$.", "B": "Set $f(3)$ equal to the approaching $y$-value at the hole.", "C": "Would not match the limit.", "D": "Removable discontinuities are fixable by matching the limit."}'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['continuity_removable_discontinuity', 'limit_algebraic_manipulation_factor'],
  error_tags = ARRAY['confuse_limit_with_function_value', 'cancel_zero_improperly'],
  recommendation_reasons = ARRAY['Connects limit-as-approach to continuity by definition.', 'Targets the frequent confusion between limit value and function value.'],
  primary_skill_id = 'continuity_removable_discontinuity',
  supporting_skill_ids = ARRAY['limit_algebraic_manipulation_factor'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.6',
  section_id = '1.6',
  difficulty = 5,
  target_time_seconds = 170,
  updated_at = NOW(),
  title = 'U1C16_Q5_FillTheHole_Continuity',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 5,
  mastery_weight = 1.0,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Image required: identify the hole’s y-value and set f(3) equal to the limit.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text_and_image',
  representation_type = 'symbolic'
WHERE id = '51448cae-3144-4bde-b809-392cdfe4dfa2';

COMMIT;
