-- Update Unit 1 Limits Questions Part 4 (Chapters 1.9 & 1.10)
BEGIN;

-- Updating 1.9-P1 -> U1C9Q1_Limit_Consistent_With_Graph
UPDATE public.questions SET
  prompt = '{"text": "The graph of $f$ is shown. What is $\\lim_{x\\to 2} f(x)$?", "image": "U1C9Q1_Limit_Consistent_With_Graph.png"}',
  latex = '$$\lim_{x\to 2} f(x)=?$$',
  options = '[{"id": "A", "text": "$3$", "explanation": "From the left, $f(x)$ approaches $3$. From the right, the graph is at $y=3$ near $x=2$. Both one-sided limits match."}, {"id": "B", "text": "$1$", "explanation": "$f(2)=1$ is the filled point, but the limit depends on nearby values, not the value at $x=2$."}, {"id": "C", "text": "Does not exist", "explanation": "The one-sided limits are equal here, so the two-sided limit exists."}, {"id": "D", "text": "$2$", "explanation": "There is no evidence the function approaches $2$ from either side near $x=2$."}]'::jsonb,
  explanation = 'Read the approach values on both sides of $x=2$. The left-hand limit is $3$ and the right-hand limit is also $3$, so $\lim_{x\to 2} f(x)=3$.',
  micro_explanations = '["Identify the y-value approached as $x\\to 2^-$.", "Identify the y-value approached as $x\\to 2^+$.", "If they match, that common value is the limit."]'::jsonb,
  correct_option_id = 'A',
  skill_tags = ARRAY['limit_from_graph', 'one_sided_limits'],
  primary_skill_id = 'limit_from_graph',
  supporting_skill_ids = ARRAY['one_sided_limits'],
error_tags = ARRAY['misread_graph_open_closed', 'confuse_f_of_a_with_limit', 'ignore_one_sided'],
  recommendation_reasons = ARRAY['Targets connecting graphical behavior to two-sided limits.', 'Reinforces difference between $f(2)$ and $\lim_{x\to 2} f(x)$.'],
  primary_skill_id = 'limit_from_graph',
  supporting_skill_ids = ARRAY['one_sided_limits'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.9',
  section_id = '1.9',
  difficulty = 2,
  target_time_seconds = 75,
  updated_at = NOW(),
  title = 'U1C9Q1_Limit_Consistent_With_Graph',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.9 Connecting Multiple Representations of Limits',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text_and_image',
  representation_type = 'symbolic'
WHERE title = '1.9-P1';

-- Updating 1.9-P2 -> U1C9Q2_Limit_Using_Symbolic_With_Redefinition
UPDATE public.questions SET
  prompt = '{"text": "A function satisfies $f(x)=(x-3)(x+1)$ for $x\\ne 3$, and $f(3)=10$. What is $\\lim_{x\\to 3} f(x)$?", "image": null}',
  latex = '$$\lim_{x\to 3} (x-3)(x+1)$$',
  options = '[{"id": "A", "text": "$10$", "explanation": "$10$ is $f(3)$, but the limit uses values near $3$, and the formula for $x\\ne 3$ controls the approach."}, {"id": "B", "text": "$0$", "explanation": "This is the value of $(x-3)(x+1)$ at $x=3$, but $(x-3)$ makes it $0$ only if substituted directly; the expression is defined for $x\\ne 3$, yet the limit can still be found by substitution into the polynomial."}, {"id": "C", "text": "$0$", "explanation": "As $x\\to 3$, $(x-3)(x+1)\\to (0)(4)=0$."}, {"id": "D", "text": "$4$", "explanation": "$4$ is $x+1$ at $x=3$, but you must multiply by the factor approaching $0$."}]'::jsonb,
  explanation = 'For $x\ne 3$, $f(x)$ equals a polynomial. Polynomials are continuous, so the limit equals the polynomial value at $x=3$: $(3-3)(3+1)=0$.',
  micro_explanations = '["Use the given expression valid for $x\\ne 3$ to analyze approach behavior.", "Polynomials have limits equal to their substituted values.", "Compare with $f(3)$ to avoid confusing value with limit."]'::jsonb,
  correct_option_id = 'C',
  skill_tags = ARRAY['limit_from_table', 'limit_algebraic'],
  primary_skill_id = 'limit_from_table',
  supporting_skill_ids = ARRAY['limit_algebraic'],
error_tags = ARRAY['table_rounding_assumption', 'confuse_f_of_a_with_limit'],
  recommendation_reasons = ARRAY['Connects symbolic definition with the idea that the limit can exist even if the function value is redefined.', 'Common AP trap: mixing $f(a)$ with $\lim_{x\to a} f(x)$.'],
  primary_skill_id = 'limit_algebraic',
  supporting_skill_ids = ARRAY['limit_from_table'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.9',
  section_id = '1.9',
  difficulty = 3,
  target_time_seconds = 90,
  updated_at = NOW(),
  title = 'U1C9Q2_Limit_Using_Symbolic_With_Redefinition',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.9 Connecting Multiple Representations of Limits',
  weight_primary = 0.6,
  weight_supporting = 0.4,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.9-P2';

-- Updating 1.9-P3 -> U1C9Q3_Connect_Table_To_OneSided_Limits
UPDATE public.questions SET
  prompt = '{"text": "A table gives values of $g(x)$ near $x=1$. For $x<1$, the values trend toward $2$. For $x>1$, the values trend toward $-1$. Which statement is true?", "image": null}',
  latex = '$$\text{Choose the correct conclusion about }\lim_{x\to 1} g(x).$$',
  options = '[{"id": "A", "text": "$\\lim_{x\\to 1} g(x)=2$", "explanation": "This matches only the left-hand trend, not the right-hand trend."}, {"id": "B", "text": "$\\lim_{x\\to 1} g(x)=-1$", "explanation": "This matches only the right-hand trend, not the left-hand trend."}, {"id": "C", "text": "$g(1)=2$", "explanation": "The table trends do not determine $g(1)$ unless a value at $x=1$ is provided."}, {"id": "D", "text": "$\\lim_{x\\to 1} g(x)$ does not exist", "explanation": "The one-sided limits approach different values ($2$ vs. $-1$), so the two-sided limit does not exist."}]'::jsonb,
  explanation = 'A two-sided limit exists only if the left-hand and right-hand limits are equal. Here they differ, so $\lim_{x\to 1} g(x)$ does not exist.',
  micro_explanations = '["Identify the left-hand approach value from the table trend.", "Identify the right-hand approach value from the table trend.", "Different one-sided limits imply DNE."]'::jsonb,
  correct_option_id = 'D',
  skill_tags = ARRAY['limit_from_table', 'one_sided_limits'],
  primary_skill_id = 'limit_from_table',
  supporting_skill_ids = ARRAY['one_sided_limits'],
error_tags = ARRAY['table_rounding_assumption', 'ignore_one_sided'],
  recommendation_reasons = ARRAY['Forces explicit one-sided reasoning from a representation other than a graph.', 'High-frequency error: declaring the more ''stable-looking'' side as the limit.'],
  primary_skill_id = 'limit_from_table',
  supporting_skill_ids = ARRAY['one_sided_limits'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.9',
  section_id = '1.9',
  difficulty = 4,
  target_time_seconds = 110,
  updated_at = NOW(),
  title = 'U1C9Q3_Connect_Table_To_OneSided_Limits',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.9 Connecting Multiple Representations of Limits',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.9-P3';

-- Updating 1.9-P4 -> U1C9Q4_Limit_From_Table_At_2
UPDATE public.questions SET
  prompt = '{"text": "The table shown gives values of $f(x)$ near $x=2$. Estimate $\\lim_{x\\to 2} f(x)$.", "image": "U1C9Q4_Limit_From_Table_At_2.png"}',
  latex = '$$\lim_{x\to 2} f(x)\approx ?$$',
  options = '[{"id": "A", "text": "$3.61$", "explanation": "That is $f(1.9)$, not the value approached near $x=2$."}, {"id": "B", "text": "$4$", "explanation": "The values $3.9601$ and $4.0401$ cluster around $4$, suggesting the limit is $4$."}, {"id": "C", "text": "$4.41$", "explanation": "That is $f(2.1)$, which is farther from $2$ than $2.01$."}, {"id": "D", "text": "Does not exist", "explanation": "The table suggests approach toward a single value from both sides, so the limit exists."}]'::jsonb,
  explanation = 'As $x$ gets closer to $2$ from both sides, $f(x)$ gets closer to $4$, so $\lim_{x\to 2} f(x)\approx 4$.',
  micro_explanations = '["Focus on inputs closest to $2$ on each side.", "Compare the corresponding outputs.", "Pick the common target value."]'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['limit_from_table', 'limit_from_graph'],
  primary_skill_id = 'limit_from_table',
  supporting_skill_ids = ARRAY['limit_from_graph'],
error_tags = ARRAY['table_rounding_assumption', 'confuse_f_of_a_with_limit'],
  recommendation_reasons = ARRAY['Builds quick table-to-limit estimation used throughout Unit 1.', 'Reinforces choosing the closest x-values over farther ones.'],
  primary_skill_id = 'limit_from_table',
  supporting_skill_ids = ARRAY['limit_from_graph'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.9',
  section_id = '1.9',
  difficulty = 1,
  target_time_seconds = 60,
  updated_at = NOW(),
  title = 'U1C9Q4_Limit_From_Table_At_2',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 1,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.9 Connecting Multiple Representations of Limits',
  weight_primary = 0.8,
  weight_supporting = 0.2,
  prompt_type = 'text_and_image',
  representation_type = 'symbolic'
WHERE title = '1.9-P4';

-- Updating 1.9-P5 -> U1C9Q5_Connect_AbsoluteValue_To_OneSided
UPDATE public.questions SET
  prompt = '{"text": "Define $h(x)=\\dfrac{|x-2|}{x-2}$ for $x\\ne 2$. Which statement is true?", "image": null}',
  latex = '$$h(x)=\frac{|x-2|}{x-2}\quad (x\ne 2)$$',
  options = '[{"id": "A", "text": "$\\lim_{x\\to 2} h(x)=0$", "explanation": "The function takes values $-1$ or $1$, never approaching $0$ near $2$."}, {"id": "B", "text": "$\\lim_{x\\to 2} h(x)=1$", "explanation": "The right-hand limit is $1$, but the left-hand limit is $-1$."}, {"id": "C", "text": "$\\lim_{x\\to 2} h(x)$ does not exist", "explanation": "For $x>2$, $h(x)=1$; for $x<2$, $h(x)=-1$. The one-sided limits differ."}, {"id": "D", "text": "$h(x)=1$ for all $x\\ne 2$", "explanation": "For $x<2$, $|x-2|=-(x-2)$ so $h(x)=-1$."}]'::jsonb,
  explanation = 'Compute one-sided behavior: if $x>2$, then $|x-2|=x-2$ so $h(x)=1$. If $x<2$, then $|x-2|=-(x-2)$ so $h(x)=-1$. Since $1\ne -1$, the two-sided limit does not exist.',
  micro_explanations = '["Rewrite $|x-2|$ piecewise for $x>2$ and $x<2$.", "Evaluate left-hand and right-hand limits separately.", "Conclude DNE if they differ."]'::jsonb,
  correct_option_id = 'C',
  skill_tags = ARRAY['limit_algebraic', 'one_sided_limits'],
  primary_skill_id = 'limit_algebraic',
  supporting_skill_ids = ARRAY['one_sided_limits'],
error_tags = ARRAY['cancel_invalid_at_discontinuity', 'ignore_one_sided'],
  recommendation_reasons = ARRAY['Connects symbolic piecewise reasoning to limit existence.', 'High-discrimination AP item: absolute value in a limit context.'],
  primary_skill_id = 'one_sided_limits',
  supporting_skill_ids = ARRAY['limit_algebraic'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.9',
  section_id = '1.9',
  difficulty = 5,
  target_time_seconds = 140,
  updated_at = NOW(),
  title = 'U1C9Q5_Connect_AbsoluteValue_To_OneSided',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.9 Connecting Multiple Representations of Limits',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.9-P5';

-- Updating 1.10-P1 -> U1C10Q1_Classify_Discontinuity_From_Graph
UPDATE public.questions SET
  prompt = '{"text": "The graph of $f$ is shown. What type of discontinuity does $f$ have at $x=1$?", "image": "U1C10Q1_Classify_Discontinuity_From_Graph.png"}',
  latex = '$$\text{Classify the discontinuity at }x=1.$$',
  options = '[{"id": "A", "text": "Removable discontinuity", "explanation": "A removable discontinuity would have matching one-sided limits. Here the left and right behaviors do not approach the same value."}, {"id": "B", "text": "Infinite discontinuity", "explanation": "An infinite discontinuity requires unbounded behavior near $x=1$, which is not shown."}, {"id": "C", "text": "No discontinuity (continuous at $x=1$)", "explanation": "The left and right sides do not meet at one common value."}, {"id": "D", "text": "Jump discontinuity", "explanation": "The left-hand limit and right-hand limit are finite but unequal, indicating a jump."}]'::jsonb,
  explanation = 'At $x=1$, the graph approaches one finite value from the left and a different finite value from the right, so the discontinuity is a jump discontinuity.',
  micro_explanations = '["Check whether the left-hand and right-hand limits exist.", "Decide whether they are equal.", "Finite but unequal implies jump."]'::jsonb,
  correct_option_id = 'D',
  skill_tags = ARRAY['continuity_discontinuity', 'limit_from_graph'],
  primary_skill_id = 'continuity_discontinuity',
  supporting_skill_ids = ARRAY['limit_from_graph'],
error_tags = ARRAY['jump_vs_removable_confusion', 'misread_graph_open_closed'],
  recommendation_reasons = ARRAY['Core classification skill for discontinuities.', 'Trains reading discontinuity type directly from a graph.'],
  primary_skill_id = 'continuity_discontinuity',
  supporting_skill_ids = ARRAY['limit_from_graph'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.10',
  section_id = '1.10',
  difficulty = 2,
  target_time_seconds = 85,
  updated_at = NOW(),
  title = 'U1C10Q1_Classify_Discontinuity_From_Graph',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.10 Exploring Types of Discontinuities',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text_and_image',
  representation_type = 'symbolic'
WHERE title = '1.10-P1';

-- Updating 1.10-P2 -> U1C10Q2_Remove_Discontinuity_By_Definition
UPDATE public.questions SET
  prompt = '{"text": "Consider $p(x)=\\dfrac{x^2-9}{x-3}$ for $x\\ne 3$. What must $p(3)$ be to make $p$ continuous at $x=3$?", "image": null}',
  latex = '$$p(x)=\frac{x^2-9}{x-3}$$',
  options = '[{"id": "A", "text": "$0$", "explanation": "The limiting value is not $0$; simplify first to find the limit."}, {"id": "B", "text": "$6$", "explanation": "After simplification, the limit at $x=3$ is $6$, so setting $p(3)=6$ fills the removable discontinuity."}, {"id": "C", "text": "$3$", "explanation": "This is the x-value, not the y-value that continuity requires."}, {"id": "D", "text": "No value works", "explanation": "This is a removable discontinuity, so defining the function at $x=3$ can make it continuous."}]'::jsonb,
  explanation = 'Factor: $x^2-9=(x-3)(x+3)$. For $x\ne 3$, $p(x)=x+3$. Thus $\lim_{x\to 3}p(x)=6$. Continuity requires $p(3)=6$.',
  micro_explanations = '["Factor the numerator.", "Cancel $(x-3)$ for $x\\ne 3$ to get the simplified form.", "Set $p(3)$ equal to the limit value."]'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['continuity_discontinuity', 'limit_algebraic'],
  primary_skill_id = 'continuity_discontinuity',
  supporting_skill_ids = ARRAY['limit_algebraic'],
error_tags = ARRAY['cancel_invalid_at_discontinuity', 'confuse_f_of_a_with_limit'],
  recommendation_reasons = ARRAY['Classic removable discontinuity completion problem.', 'Directly connects algebraic limit to continuity definition.'],
  primary_skill_id = 'continuity_discontinuity',
  supporting_skill_ids = ARRAY['limit_algebraic'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.10',
  section_id = '1.10',
  difficulty = 3,
  target_time_seconds = 100,
  updated_at = NOW(),
  title = 'U1C10Q2_Remove_Discontinuity_By_Definition',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 2,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.10 Exploring Types of Discontinuities',
  weight_primary = 0.6,
  weight_supporting = 0.4,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.10-P2';

-- Updating 1.10-P3 -> U1C10Q3_Infinite_Limit_And_Asymptote
UPDATE public.questions SET
  prompt = '{"text": "The graph of $f$ is shown. Which statement is true?", "image": "U1C10Q3_Infinite_Limit_And_Asymptote.png"}',
  latex = '$$\text{Choose the correct statement about limits near }x=0.$$',
  options = '[{"id": "A", "text": "$\\lim_{x\\to 0} f(x)=0$", "explanation": "The function values do not approach $0$; they grow without bound in magnitude."}, {"id": "B", "text": "$\\lim_{x\\to 0^-} f(x)=+\\infty$ and $\\lim_{x\\to 0^+} f(x)=+\\infty$", "explanation": "On the left side the graph goes to $-\\infty$, not $+\\infty$."}, {"id": "C", "text": "$\\lim_{x\\to 0^-} f(x)=-\\infty$ and $\\lim_{x\\to 0^+} f(x)=+\\infty$", "explanation": "The left branch goes downward without bound and the right branch goes upward without bound, indicating a vertical asymptote at $x=0$."}, {"id": "D", "text": "$\\lim_{x\\to 0} f(x)$ exists and is finite", "explanation": "The function is unbounded near $x=0$, so a finite two-sided limit cannot exist."}]'::jsonb,
  explanation = 'From the graph, as $x\to 0^-$ the function decreases without bound, and as $x\to 0^+$ it increases without bound. So there is an infinite discontinuity (vertical asymptote) at $x=0$.',
  micro_explanations = '["Read the end behavior on each side of the vertical line $x=0$.", "Record each one-sided infinite limit with the correct sign.", "Conclude vertical asymptote from infinite behavior."]'::jsonb,
  correct_option_id = 'C',
  skill_tags = ARRAY['asymptote_infinite_limit', 'one_sided_limits'],
  primary_skill_id = 'asymptote_infinite_limit',
  supporting_skill_ids = ARRAY['one_sided_limits'],
error_tags = ARRAY['vertical_asymptote_not_infinite_limit', 'ignore_one_sided'],
  recommendation_reasons = ARRAY['Tests sign awareness for infinite limits.', 'Common error: assuming both sides go to the same infinity.'],
  primary_skill_id = 'asymptote_infinite_limit',
  supporting_skill_ids = ARRAY['one_sided_limits'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.10',
  section_id = '1.10',
  difficulty = 4,
  target_time_seconds = 115,
  updated_at = NOW(),
  title = 'U1C10Q3_Infinite_Limit_And_Asymptote',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.10 Exploring Types of Discontinuities',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text_and_image',
  representation_type = 'symbolic'
WHERE title = '1.10-P3';

-- Updating 1.10-P4 -> U1C10Q4_Classify_Removable_From_Limit_Facts
UPDATE public.questions SET
  prompt = '{"text": "At $x=a$, a function has $\\lim_{x\\to a^-} f(x)=5$ and $\\lim_{x\\to a^+} f(x)=5$, but $f(a)$ is not defined. What type of discontinuity is at $x=a$?", "image": null}',
  latex = '$$\lim_{x\to a^-} f(x)=5,\;\lim_{x\to a^+} f(x)=5,\;f(a)\text{ undefined}$$',
  options = '[{"id": "A", "text": "Removable discontinuity", "explanation": "The two-sided limit exists and is finite, but the function value is missing, so defining $f(a)=5$ would make it continuous."}, {"id": "B", "text": "Jump discontinuity", "explanation": "A jump requires unequal one-sided limits."}, {"id": "C", "text": "Infinite discontinuity", "explanation": "Infinite discontinuities involve unbounded limits."}, {"id": "D", "text": "No discontinuity", "explanation": "Continuity also requires $f(a)$ to exist and equal the limit."}]'::jsonb,
  explanation = 'Equal finite one-sided limits imply the (two-sided) limit exists. Because $f(a)$ is undefined, the discontinuity can be removed by defining $f(a)=5$.',
  micro_explanations = '["Check whether the one-sided limits match.", "If they match and are finite, the limit exists.", "Missing or mismatched function value implies removable discontinuity."]'::jsonb,
  correct_option_id = 'A',
  skill_tags = ARRAY['continuity_discontinuity', 'one_sided_limits'],
  primary_skill_id = 'continuity_discontinuity',
  supporting_skill_ids = ARRAY['one_sided_limits'],
error_tags = ARRAY['jump_vs_removable_confusion', 'confuse_f_of_a_with_limit'],
  recommendation_reasons = ARRAY['Fast classification using limit facts alone.', 'Reinforces the 3-part continuity idea implicitly.'],
  primary_skill_id = 'continuity_discontinuity',
  supporting_skill_ids = ARRAY['one_sided_limits'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.10',
  section_id = '1.10',
  difficulty = 1,
  target_time_seconds = 65,
  updated_at = NOW(),
  title = 'U1C10Q4_Classify_Removable_From_Limit_Facts',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 1,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.10 Exploring Types of Discontinuities',
  weight_primary = 0.8,
  weight_supporting = 0.2,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.10-P4';

-- Updating 1.10-P5 -> U1C10Q5_Removable_When_Value_Differs_From_Limit
UPDATE public.questions SET
  prompt = '{"text": "A function $f$ has $\\lim_{x\\to 4^-} f(x)=2$ and $\\lim_{x\\to 4^+} f(x)=2$. Also $f(4)=7$. Which statement is true?", "image": null}',
  latex = '$$\lim_{x\to 4^-} f(x)=2,\;\lim_{x\to 4^+} f(x)=2,\;f(4)=7$$',
  options = '[{"id": "A", "text": "$f$ is continuous at $x=4$ because both one-sided limits exist", "explanation": "Continuity also requires $f(4)$ to equal the limit."}, {"id": "B", "text": "$\\lim_{x\\to 4} f(x)=7$", "explanation": "The limit is determined by nearby behavior, and both sides approach $2$, not $7$."}, {"id": "C", "text": "$f$ has a removable discontinuity at $x=4$", "explanation": "The limit exists and equals $2$, but $f(4)=7\\ne 2$, so redefining $f(4)$ to $2$ would make it continuous."}, {"id": "D", "text": "$f$ has a jump discontinuity at $x=4$", "explanation": "A jump requires different left- and right-hand limits; here they are equal."}]'::jsonb,
  explanation = 'Since $\lim_{x\to 4^-} f(x)=\lim_{x\to 4^+} f(x)=2$, the two-sided limit exists and equals $2$. But $f(4)=7\ne 2$, so the discontinuity is removable.',
  micro_explanations = '["Equal one-sided limits imply $\\lim_{x\\to 4} f(x)=2$.", "Compare $f(4)$ to the limit.", "Mismatch implies discontinuity; since the limit exists, it is removable."]'::jsonb,
  correct_option_id = 'C',
  skill_tags = ARRAY['continuity_discontinuity', 'one_sided_limits'],
  primary_skill_id = 'continuity_discontinuity',
  supporting_skill_ids = ARRAY['one_sided_limits'],
error_tags = ARRAY['jump_vs_removable_confusion', 'ignore_one_sided', 'confuse_f_of_a_with_limit'],
  recommendation_reasons = ARRAY['High-frequency AP concept: removable discontinuity caused by a misdefined point value.', 'Separates ''limit exists'' from ''function is continuous''.'],
  primary_skill_id = 'continuity_discontinuity',
  supporting_skill_ids = ARRAY['one_sided_limits'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.10',
  section_id = '1.10',
  difficulty = 5,
  target_time_seconds = 150,
  updated_at = NOW(),
  title = 'U1C10Q5_Removable_When_Value_Differs_From_Limit',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = version + 1,
  reasoning_level = 3,
  mastery_weight = 1,
  source = 'NewMaoS',
  source_year = 2026,
  notes = 'Chapter 1.10 Exploring Types of Discontinuities',
  weight_primary = 0.6,
  weight_supporting = 0.4,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.10-P5';

COMMIT;
