-- Update Unit 1 Limits Questions Part 3 (Chapters 1.7 & 1.8)
BEGIN;

-- Updating 1.7-P1 -> C7Q1 Procedure from Graph
UPDATE public.questions SET
  prompt = 'Use the graph of $f$ to evaluate $\lim_{x\to -1} f(x)$. [image:C7Q1 Procedure from Graph.png]',
  latex = '$$\lim_{x\to -1} f(x)$$',
  options = '[{"id": "A", "text": "$\\tfrac{1}{2}$", "explanation": "Both sides approach the open circle on the line at $x=-1$, which is $y=\\tfrac{1}{2}$."}, {"id": "B", "text": "$2$", "explanation": "$2$ is the filled point value at $x=-1$, not the limit."}, {"id": "C", "text": "DNE because there is a hole", "explanation": "A hole does not prevent the limit from existing if both sides approach the same value."}, {"id": "D", "text": "DNE because there is a jump", "explanation": "The jump shown is at $x=0$, not at $x=-1$."}]'::jsonb,
  explanation = 'Near $x=-1$, the curve follows the line segment on both sides and approaches the open-circle height. The filled point at $x=-1$ changes $f(-1)$ but not the limit.',
  micro_explanations = '{"A": "Limit is the approached $y$-value.", "B": "Function value $\\neq$ limit.", "C": "Removable discontinuity can still have a limit.", "D": "Jump is at a different $x$."}'::jsonb,
  correct_option_id = 'A',
  skill_tags = ARRAY['limit_procedure_selection', 'graphical_limit_interpretation'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = ARRAY['graphical_limit_interpretation'],
error_tags = ARRAY['e6_misread_graph', 'e2_ignore_one_sided', 'e1_confuse_value_with_limit'],
  recommendation_reasons = ARRAY['Practice distinguishing limit from function value using a graph.', 'Build method-selection fluency for non-algebraic representations.'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = ARRAY['graphical_limit_interpretation'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.7',
  section_id = '1.7',
  difficulty = 3,
  target_time_seconds = 90,
  updated_at = NOW(),
  title = 'C7Q1 Procedure from Graph',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 3,
  mastery_weight = 1.0,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E1_CONFUSE_VALUE_WITH_LIMIT; E6_MISREAD_GRAPH; E2_IGNORE_ONE_SIDED.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text_and_image',
  representation_type = 'symbolic'
WHERE title = '1.7-P1';

-- Updating 1.7-P2 -> C7Q2 Best Procedure for 0/0
UPDATE public.questions SET
  prompt = 'Which procedure is most efficient for evaluating $\lim_{x\to 3} \dfrac{x^2-9}{x-3}$?',
  latex = '$$\lim_{x\to 3}\frac{x^2-9}{x-3}$$',
  options = '[{"id": "A", "text": "Direct substitution", "explanation": "Direct substitution gives $\\frac{0}{0}$, so more work is needed."}, {"id": "B", "text": "Factor and cancel before substituting", "explanation": "Factor $x^2-9=(x-3)(x+3)$, cancel, then substitute."}, {"id": "C", "text": "Squeeze Theorem", "explanation": "No natural bounding functions are suggested; algebraic simplification is standard."}, {"id": "D", "text": "One-sided limits from a table", "explanation": "A table could work but is less efficient than factoring here."}]'::jsonb,
  explanation = 'This is a removable discontinuity form $\frac{0}{0}$ that resolves by factoring and canceling the common factor, then substituting.',
  micro_explanations = '{"A": "Indeterminate form signals more steps.", "B": "Classic factor-cancel-substitute.", "C": "Squeeze is for bounding/oscillation.", "D": "Table is slower and less exact."}'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['limit_procedure_selection', 'algebraic_limit_evaluation'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = ARRAY['algebraic_limit_evaluation'],
error_tags = ARRAY['e4_wrong_method_choice', 'e3_algebra_slip'],
  recommendation_reasons = ARRAY['Reinforce quick recognition of $\frac{0}{0}$ patterns that require simplification.', 'Reduce overuse of tables/graphs when algebra is cleaner.'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = ARRAY['algebraic_limit_evaluation'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.7',
  section_id = '1.7',
  difficulty = 2,
  target_time_seconds = 75,
  updated_at = NOW(),
  title = 'C7Q2 Best Procedure for 0/0',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 2,
  mastery_weight = 0.9,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E4_WRONG_METHOD_CHOICE; E3_ALGEBRA_SLIP.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.7-P2';

-- Updating 1.7-P3 -> C7Q3 One-Sided Needed at 0
UPDATE public.questions SET
  prompt = 'For $f(x)=\dfrac{|x|}{x}$, what is $\lim_{x\to 0} f(x)$?',
  latex = '$$\lim_{x\to 0}\frac{|x|}{x}$$',
  options = '[{"id": "A", "text": "$0$", "explanation": "The expression approaches $1$ from the right and $-1$ from the left, not $0$."}, {"id": "B", "text": "$1$", "explanation": "$1$ is the right-hand limit only."}, {"id": "C", "text": "$-1$", "explanation": "$-1$ is the left-hand limit only."}, {"id": "D", "text": "DNE", "explanation": "Left-hand and right-hand limits are different, so the two-sided limit does not exist."}]'::jsonb,
  explanation = 'Use one-sided limits: if $x>0$, $\frac{|x|}{x}=1$; if $x<0$, $\frac{|x|}{x}=-1$. Since $1\neq -1$, the limit does not exist.',
  micro_explanations = '{"A": "Not approaching $0$.", "B": "Only $x\\to 0^+$.", "C": "Only $x\\to 0^-$.", "D": "Mismatch of one-sided limits."}'::jsonb,
  correct_option_id = 'D',
  skill_tags = ARRAY['limit_procedure_selection', 'one_sided_limits'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = ARRAY['one_sided_limits'],
error_tags = ARRAY['e2_ignore_one_sided', 'e4_wrong_method_choice'],
  recommendation_reasons = ARRAY['Strengthen automatic check of one-sided limits for absolute value/step behavior.', 'Prevent false ‘plug in’ habits near sign changes.'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = ARRAY['one_sided_limits'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.7',
  section_id = '1.7',
  difficulty = 4,
  target_time_seconds = 110,
  updated_at = NOW(),
  title = 'C7Q3 One-Sided Needed at 0',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 3,
  mastery_weight = 1.1,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E2_IGNORE_ONE_SIDED; E4_WRONG_METHOD_CHOICE.',
  weight_primary = 0.6,
  weight_supporting = 0.4,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.7-P3';

-- Updating 1.7-P4 -> C7Q4 Infinite Limit at a Vertical Asymptote
UPDATE public.questions SET
  prompt = 'Evaluate $\lim_{x\to 2} \dfrac{1}{(x-2)^2}$.',
  latex = '$$\lim_{x\to 2}\frac{1}{(x-2)^2}$$',
  options = '[{"id": "A", "text": "$0$", "explanation": "The denominator approaches $0$, so the expression does not approach $0$."}, {"id": "B", "text": "$+\\infty$", "explanation": "Because $(x-2)^2>0$ and approaches $0$, the reciprocal grows without bound positively."}, {"id": "C", "text": "$-\\infty$", "explanation": "The square keeps the denominator positive, so it cannot go to $-\\infty$."}, {"id": "D", "text": "DNE because of $\\frac{1}{0}$", "explanation": "The limit exists as an infinite limit and equals $+\\infty$."}]'::jsonb,
  explanation = 'As $x\to 2$, $(x-2)^2\to 0^+$, so $\frac{1}{(x-2)^2}\to +\infty$ (vertical asymptote at $x=2$).',
  micro_explanations = '{"A": "Reciprocal of tiny positive is huge.", "B": "Correct infinite limit.", "C": "Square prevents negative values.", "D": "Infinite limits are valid limit behavior."}'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['limit_procedure_selection', 'infinite_limits_asymptotes'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = ARRAY['infinite_limits_asymptotes'],
error_tags = ARRAY['e4_wrong_method_choice', 'e3_algebra_slip'],
  recommendation_reasons = ARRAY['Practice choosing ‘infinite limit’ interpretation when denominator goes to $0^+$.', 'Avoid labeling all blow-ups as DNE without sign analysis.'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = ARRAY['infinite_limits_asymptotes'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.7',
  section_id = '1.7',
  difficulty = 3,
  target_time_seconds = 90,
  updated_at = NOW(),
  title = 'C7Q4 Infinite Limit at a Vertical Asymptote',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 3,
  mastery_weight = 1.0,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E4_WRONG_METHOD_CHOICE; E3_ALGEBRA_SLIP.',
  weight_primary = 0.6,
  weight_supporting = 0.4,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.7-P4';

-- Updating 1.7-P5 -> C7Q5 Procedure Choice for Jump Discontinuity
UPDATE public.questions SET
  prompt = 'A function $h$ is defined by a graph that clearly shows a jump discontinuity at $x=a$. Which statement must be true?',
  latex = '',
  options = '[{"id": "A", "text": "$\\lim_{x\\to a} h(x)$ does not exist", "explanation": "At a jump, the left-hand and right-hand limits are finite but unequal, so the two-sided limit does not exist."}, {"id": "B", "text": "$h(a)$ is undefined", "explanation": "A jump can still have a defined value at $x=a$ (a filled point)."}, {"id": "C", "text": "$\\lim_{x\\to a} h(x)=h(a)$", "explanation": "A jump prevents the two-sided limit from matching a single value."}, {"id": "D", "text": "Both one-sided limits are infinite", "explanation": "A jump is typically finite on both sides; infinite behavior is a vertical asymptote."}]'::jsonb,
  explanation = 'A jump discontinuity means $\lim_{x\to a^-}h(x)$ and $\lim_{x\to a^+}h(x)$ exist (finite) but are not equal, so the two-sided limit does not exist.',
  micro_explanations = '{"A": "Unequal one-sided limits.", "B": "Value at $a$ may be defined.", "C": "Continuity fails at a jump.", "D": "Infinite limits correspond to asymptotes."}'::jsonb,
  correct_option_id = 'A',
  skill_tags = ARRAY['limit_procedure_selection'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = ARRAY[]::text[],
error_tags = ARRAY['e4_wrong_method_choice', 'e1_confuse_value_with_limit'],
  recommendation_reasons = ARRAY['Solidify classification of discontinuities into ‘limit exists’ vs ‘limit DNE’.', 'Reduce confusion between jump vs asymptote vs removable.'],
  primary_skill_id = 'limit_procedure_selection',
  supporting_skill_ids = '{}',
  topic_id = 'Both_Limits',
  sub_topic_id = '1.7',
  section_id = '1.7',
  difficulty = 1,
  target_time_seconds = 60,
  updated_at = NOW(),
  title = 'C7Q5 Procedure Choice for Jump Discontinuity',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 2,
  mastery_weight = 0.8,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E4_WRONG_METHOD_CHOICE; E1_CONFUSE_VALUE_WITH_LIMIT.',
  weight_primary = 1.0,
  weight_supporting = 0.0,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.7-P5';

-- Updating 1.8-P1 -> C8Q1 Trig-Oscillation Product Squeeze
UPDATE public.questions SET
  prompt = 'Evaluate $\lim_{x\to 0} x^2\cos\left(\dfrac{1}{x}\right)$.',
  latex = '$$\lim_{x\to 0} x^2\cos\left(\frac{1}{x}\right)$$',
  options = '[{"id": "A", "text": "DNE because $\\cos(1/x)$ oscillates", "explanation": "Oscillation alone does not prevent a limit when a factor forces the product to $0$."}, {"id": "B", "text": "$1$", "explanation": "$x^2\\to 0$, so the product cannot approach $1$."}, {"id": "C", "text": "$0$", "explanation": "Since $-1\\le \\cos(1/x)\\le 1$, we have $-x^2\\le x^2\\cos(1/x)\\le x^2$ and both bounds go to $0$."}, {"id": "D", "text": "$-1$", "explanation": "The product is between $-x^2$ and $x^2$, so it cannot approach $-1$."}]'::jsonb,
  explanation = 'Use $-1\le \cos(1/x)\le 1$. Multiplying by $x^2\ge 0$ gives $-x^2\le x^2\cos(1/x)\le x^2$. As $x\to 0$, both $\pm x^2\to 0$, so the middle limit is $0$.',
  micro_explanations = '{"A": "Squeeze can tame oscillation.", "B": "$x^2$ kills magnitude.", "C": "Correct squeeze setup.", "D": "Bounds force approach to $0$."}'::jsonb,
  correct_option_id = 'C',
  skill_tags = ARRAY['squeeze_theorem', 'trig_bounds'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['trig_bounds'],
error_tags = ARRAY['e5_assume_squeeze_without_bounds', 'e7_bound_not_tight'],
  recommendation_reasons = ARRAY['Rehearse standard trig bounds $-1\le\sin,\cos\le 1$ for squeeze products.', 'Avoid ‘oscillates therefore DNE’ overgeneralization.'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['trig_bounds'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.8',
  section_id = '1.8',
  difficulty = 3,
  target_time_seconds = 95,
  updated_at = NOW(),
  title = 'C8Q1 Trig-Oscillation Product Squeeze',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 3,
  mastery_weight = 1.0,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E5_ASSUME_SQUEEZE_WITHOUT_BOUNDS; E7_BOUND_NOT_TIGHT.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.8-P1';

-- Updating 1.8-P2 -> C8Q2 Squeeze Visualization
UPDATE public.questions SET
  prompt = 'The graph shows three functions near $x=0$: $y=-|x|$, $y=x\sin(1/x)$, and $y=|x|$. What is $\lim_{x\to 0} x\sin(1/x)$? [image:C8Q2 Squeeze Visualization.png]',
  latex = '$$\lim_{x\to 0} x\sin(1/x)$$',
  options = '[{"id": "A", "text": "DNE", "explanation": "The oscillation is bounded by functions that both go to $0$, so the limit exists."}, {"id": "B", "text": "$0$", "explanation": "Because $-1\\le \\sin(1/x)\\le 1$, multiplying by $x$ gives $-|x|\\le x\\sin(1/x)\\le |x|$, and both bounds go to $0$."}, {"id": "C", "text": "$1$", "explanation": "The middle function stays between $-|x|$ and $|x|$, which both shrink to $0$."}, {"id": "D", "text": "The limit depends on the path to $0$", "explanation": "This is a single-variable limit; squeeze forces a unique value."}]'::jsonb,
  explanation = 'Since $-1\le \sin(1/x)\le 1$, we have $-|x|\le x\sin(1/x)\le |x|$. As $x\to 0$, both $-|x|$ and $|x|$ approach $0$, so by the Squeeze Theorem the limit is $0$.',
  micro_explanations = '{"A": "Squeezed by shrinking bounds.", "B": "Correct: bounds $\\to 0$.", "C": "Not consistent with bounds.", "D": "No path issue in 1D."}'::jsonb,
  correct_option_id = 'B',
  skill_tags = ARRAY['squeeze_theorem', 'inequality_bounding'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['inequality_bounding'],
error_tags = ARRAY['e5_assume_squeeze_without_bounds', 'e6_misread_graph'],
  recommendation_reasons = ARRAY['Connect algebraic inequalities to graphical squeezing.', 'Build confidence recognizing classic $x\sin(1/x)$ squeeze pattern.'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['inequality_bounding'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.8',
  section_id = '1.8',
  difficulty = 2,
  target_time_seconds = 80,
  updated_at = NOW(),
  title = 'C8Q2 Squeeze Visualization',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 2,
  mastery_weight = 0.9,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E5_ASSUME_SQUEEZE_WITHOUT_BOUNDS; E6_MISREAD_GRAPH.',
  weight_primary = 0.6,
  weight_supporting = 0.4,
  prompt_type = 'text_and_image',
  representation_type = 'symbolic'
WHERE title = '1.8-P2';

-- Updating 1.8-P3 -> C8Q3 Oscillation Not Squeezed
UPDATE public.questions SET
  prompt = 'The graph shows $g(x)=\sin(1/x)$ near $x=0$. What is $\lim_{x\to 0} g(x)$? [image:C8Q3 Oscillation Not Squeezed.png]',
  latex = '$$\lim_{x\to 0}\sin(1/x)$$',
  options = '[{"id": "A", "text": "$0$", "explanation": "Although values hit $0$ infinitely often, they also hit values near $1$ and $-1$ arbitrarily close to $0$."}, {"id": "B", "text": "$1$", "explanation": "The function also takes values near $-1$ arbitrarily close to $0$."}, {"id": "C", "text": "$-1$", "explanation": "The function also takes values near $1$ arbitrarily close to $0$."}, {"id": "D", "text": "DNE", "explanation": "The function oscillates between $-1$ and $1$ without approaching a single value."}]'::jsonb,
  explanation = 'Even though $-1\le \sin(1/x)\le 1$, the bounds do not squeeze to a single value. Near $0$, the function attains values arbitrarily close to many numbers in $[-1,1]$, so the limit does not exist.',
  micro_explanations = '{"A": "Hitting $0$ often is not convergence.", "B": "Not approaching only $1$.", "C": "Not approaching only $-1$.", "D": "No single approached value."}'::jsonb,
  correct_option_id = 'D',
  skill_tags = ARRAY['squeeze_theorem', 'graphical_limit_interpretation'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['graphical_limit_interpretation'],
error_tags = ARRAY['e5_assume_squeeze_without_bounds', 'e1_confuse_value_with_limit'],
  recommendation_reasons = ARRAY['Differentiate ‘bounded’ from ‘squeezed’.', 'Prevent incorrect squeeze attempts when bounds do not converge.'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['graphical_limit_interpretation'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.8',
  section_id = '1.8',
  difficulty = 4,
  target_time_seconds = 105,
  updated_at = NOW(),
  title = 'C8Q3 Oscillation Not Squeezed',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 4,
  mastery_weight = 1.1,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E5_ASSUME_SQUEEZE_WITHOUT_BOUNDS; E1_CONFUSE_VALUE_WITH_LIMIT.',
  weight_primary = 0.6,
  weight_supporting = 0.4,
  prompt_type = 'text_and_image',
  representation_type = 'symbolic'
WHERE title = '1.8-P3';

-- Updating 1.8-P4 -> C8Q4 Inequality-Form Squeeze
UPDATE public.questions SET
  prompt = 'Suppose $|f(x)|\le 5|x-2|$ for all $x$ near $2$. What is $\lim_{x\to 2} f(x)$?',
  latex = '$$|f(x)|\le 5|x-2|$$',
  options = '[{"id": "A", "text": "$0$", "explanation": "Since $-5|x-2|\\le f(x)\\le 5|x-2|$ and $5|x-2|\\to 0$, squeeze gives $\\lim_{x\\to 2} f(x)=0$."}, {"id": "B", "text": "$5$", "explanation": "The inequality bounds $f(x)$ by something that goes to $0$, not by $5$."}, {"id": "C", "text": "DNE", "explanation": "The bounds converge to $0$, which forces existence and value $0$."}, {"id": "D", "text": "Cannot be determined", "explanation": "The inequality is enough: it forces $f(x)$ to be trapped near $0$."}]'::jsonb,
  explanation = 'Because $|f(x)|\le 5|x-2|$, we have $-5|x-2|\le f(x)\le 5|x-2|$. As $x\to 2$, both bounds go to $0$, so by Squeeze Theorem $\lim_{x\to 2} f(x)=0$.',
  micro_explanations = '{"A": "Bounds shrink to $0$.", "B": "Misreads inequality.", "C": "Squeeze guarantees a limit here.", "D": "Inequality determines it."}'::jsonb,
  correct_option_id = 'A',
  skill_tags = ARRAY['squeeze_theorem', 'absolute_value_inequalities'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['absolute_value_inequalities'],
error_tags = ARRAY['e7_bound_not_tight', 'e3_algebra_slip'],
  recommendation_reasons = ARRAY['Use absolute value inequalities as ready-made squeeze setups.', 'Practice translating $|f(x)|\le \text{small}$ into two-sided bounds.'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['absolute_value_inequalities'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.8',
  section_id = '1.8',
  difficulty = 3,
  target_time_seconds = 95,
  updated_at = NOW(),
  title = 'C8Q4 Inequality-Form Squeeze',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 3,
  mastery_weight = 1.0,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E7_BOUND_NOT_TIGHT; E3_ALGEBRA_SLIP.',
  weight_primary = 0.7,
  weight_supporting = 0.3,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.8-P4';

-- Updating 1.8-P5 -> C8Q5 Squeeze/Product with Trig Square
UPDATE public.questions SET
  prompt = 'Evaluate $\lim_{x\to 0} \dfrac{\sin^2 x}{x}$.',
  latex = '$$\lim_{x\to 0}\frac{\sin^2 x}{x}$$',
  options = '[{"id": "A", "text": "$1$", "explanation": "$\\frac{\\sin^2 x}{x}=\\left(\\frac{\\sin x}{x}\\right)\\sin x\\to 1\\cdot 0=0$, not $1$."}, {"id": "B", "text": "DNE because it is $\\frac{0}{0}$", "explanation": "An indeterminate form indicates you must analyze; it may still have a limit."}, {"id": "C", "text": "$0$", "explanation": "Rewrite as $\\left(\\frac{\\sin x}{x}\\right)\\sin x$; since $\\frac{\\sin x}{x}\\to 1$ and $\\sin x\\to 0$, the product goes to $0$."}, {"id": "D", "text": "$-1$", "explanation": "The expression is near $0$, not near $-1$."}]'::jsonb,
  explanation = 'Use the factorization $\dfrac{\sin^2 x}{x}=\left(\dfrac{\sin x}{x}\right)\sin x$. As $x\to 0$, $\dfrac{\sin x}{x}\to 1$ and $\sin x\to 0$, so the product tends to $0$.',
  micro_explanations = '{"A": "Forgets extra $\\sin x$ factor.", "B": "$0/0$ needs analysis, not surrender.", "C": "Correct limit product.", "D": "Not consistent with small-angle behavior."}'::jsonb,
  correct_option_id = 'C',
  skill_tags = ARRAY['squeeze_theorem', 'inequality_bounding'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['inequality_bounding'],
error_tags = ARRAY['e5_assume_squeeze_without_bounds', 'e3_algebra_slip'],
  recommendation_reasons = ARRAY['Combine standard small-angle limits with squeeze/product reasoning.', 'Target high-frequency mistake: treating $\sin^2 x/x$ like $\sin x/x$.'],
  primary_skill_id = 'squeeze_theorem',
  supporting_skill_ids = ARRAY['inequality_bounding'],
  topic_id = 'Both_Limits',
  sub_topic_id = '1.8',
  section_id = '1.8',
  difficulty = 5,
  target_time_seconds = 140,
  updated_at = NOW(),
  title = 'C8Q5 Squeeze/Product with Trig Square',
  course = 'BC',
  type = 'MCQ',
  calculator_allowed = FALSE,
  tolerance = 0,
  status = 'published',
  version = 1,
  reasoning_level = 4,
  mastery_weight = 1.2,
  source = 'NewMaoS Original',
  source_year = 2026,
  notes = 'Common Error Patterns: E5_ASSUME_SQUEEZE_WITHOUT_BOUNDS; E3_ALGEBRA_SLIP.',
  weight_primary = 0.6,
  weight_supporting = 0.4,
  prompt_type = 'text',
  representation_type = 'symbolic'
WHERE title = '1.8-P5';

COMMIT;
