-- SQL MIGRATION PART 3 (GLOBAL MATH FIXES)
-- Fix Math for 01dd4c84-50c9-4445-a2c1-4018ab0a24d7 (10.15)
UPDATE questions SET prompt = 'Refer to Table 10.15-A (U10.15_Practice_Table1_SeriesForms.png). Which function could produce $A(x)=1+2x+4x^2+8x^3+\\cdots$?', options = '[{"id":"A","value":"1/(1-2x)"},{"id":"B","value":"1/(1-x)"},{"id":"C","value":"\\ln(1+x)"},{"id":"D","value":"$e^x$"}]'::jsonb, updated_at = NOW() WHERE id = '01dd4c84-50c9-4445-a2c1-4018ab0a24d7';
-- Fix Math for 020c11da-da5a-4654-b7ff-6fdcabcf592e (2.7)
UPDATE questions SET prompt = 'If $f(x)=e^x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$e^x$","explanation":"Correct. \\frac{d}{dx}($$e^{x}$$)=$$e^{x}$$."},{"id":"B","type":"text","label":"B","value":"$xe^{x-1}$","explanation":"This is not a valid derivative rule for $$e^{x}$$."},{"id":"C","type":"text","label":"C","value":"$\\ln x$","explanation":"\\ln x is a different function, not the derivative of $$e^{x}$$."},{"id":"D","type":"text","label":"D","value":"$\\frac{1}{x}$","explanation":"\\frac{1}{x} is the derivative of \\ln x, not $$e^{x}$$."}]'::jsonb, updated_at = NOW() WHERE id = '020c11da-da5a-4654-b7ff-6fdcabcf592e';
-- Fix Math for 0753e4bf-6842-45bf-9514-e80e3e8828b7 (10.3)
UPDATE questions SET prompt = 'Consider the series $\\sum_{n=1}^{\\infty} \\frac{\\sin(n)}{n}$. Which conclusion is correct based only on the nth-term test?', options = '[{"id":"A","value":"The series converges because \\sin(n)/n→0."},{"id":"B","value":"The series diverges because \\sin(n) oscillates."},{"id":"C","value":"The nth-term test is inconclusive because \\sin(n)/n→0."},{"id":"D","value":"The series diverges because \\sin(n)/n is not decreasing."}]'::jsonb, updated_at = NOW() WHERE id = '0753e4bf-6842-45bf-9514-e80e3e8828b7';
-- Fix Math for 09004717-b58d-4f9e-868a-bf58da087a1e (8.1)
UPDATE questions SET prompt = 'The average value of $f(x)=kx^2$ on $[0,2]$ is $\frac{8}{3}$. What is $k$?', options = '[{"id":"A","value":"$1$"},{"id":"B","value":"$2$"},{"id":"C","value":"$4$"},{"id":"D","value":"$8$"}]'::jsonb, updated_at = NOW() WHERE id = '09004717-b58d-4f9e-868a-bf58da087a1e';
-- Fix Math for 0c0a3f5c-4397-45b3-913b-39f6806bd9b4 (unit_test)
UPDATE questions SET prompt = 'Which expression equals the area between $y=\\sin(x)$ and the $x$-axis on $[0,2\\pi]$?', options = '[{"id":"A","value":"$\\int _0^{2\\pi } \\sin(x) dx$"},{"id":"B","value":"$\\int _0^{\\pi } \\sin(x) dx$ - $\\int _{\\pi }^{2\\pi } \\sin(x) dx$"},{"id":"C","value":"$\\int _0^{2\\pi } \\sin(x)^2 dx$"},{"id":"D","value":"|$\\int _0^{2\\pi } \\sin(x) dx$|"}]'::jsonb, updated_at = NOW() WHERE id = '0c0a3f5c-4397-45b3-913b-39f6806bd9b4';
-- Fix Math for 0f1685a4-0118-4400-bfa2-63f046bddd3e (2.10)
UPDATE questions SET prompt = 'If $f(x)=\tan x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$\\sec^2 x$","explanation":"Correct. \\frac{d}{dx}(\\tan x)=sec^2 x."},{"id":"B","type":"text","label":"B","value":"$\\csc^2 x$","explanation":"csc^2 x is the derivative of -\\cot x, not \\tan x."},{"id":"C","type":"text","label":"C","value":"$\\sec x$","explanation":"\\sec x is not the derivative of \\tan x."},{"id":"D","type":"text","label":"D","value":"$-\\sec^2 x$","explanation":"The derivative is positive sec^2 x, not negative."}]'::jsonb, updated_at = NOW() WHERE id = '0f1685a4-0118-4400-bfa2-63f046bddd3e';
-- Fix Math for 1802d153-c90e-4ffa-9f96-9b74b3423d87 (10.6)
UPDATE questions SET prompt = 'To test $\\sum_{n=1}^{\\infty}\\frac{n}{n^3+1}$, which comparison is most appropriate?', options = '[{"id":"A","value":"Compare to ∑ \\frac{1}{n^2} because n/(n^3+1) <= \\frac{1}{n^2} for n>=1."},{"id":"B","value":"Compare to ∑ \\frac{1}{n} because n/(n^3+1) >= \\frac{1}{n} for n>=1."},{"id":"C","value":"Compare to ∑ 1 because n/(n^3+1) >= 1 for n>=1."},{"id":"D","value":"Compare to ∑ n because n/(n^3+1) ≈ n for large n."}]'::jsonb, updated_at = NOW() WHERE id = '1802d153-c90e-4ffa-9f96-9b74b3423d87';
-- Fix Math for 183722f0-ac65-43e7-b928-26efdb8654a8 (10.6)
UPDATE questions SET prompt = 'You know that $\\sum_{n=1}^{\\infty}\\frac{1}{n^2}$ converges. Which inequality would be most useful to prove that $\\sum_{n=1}^{\\infty}\\frac{1}{n^2+5}$ also converges by direct comparison?', options = '[{"id":"A","value":"1/(n^2+5) <= \\frac{1}{n^2} for n>=1"},{"id":"B","value":"1/(n^2+5) >= \\frac{1}{n^2} for n>=1"},{"id":"C","value":"1/(n^2+5) <= \\frac{1}{n} for n>=1"},{"id":"D","value":"1/(n^2+5) >= \\frac{1}{n} for n>=1"}]'::jsonb, updated_at = NOW() WHERE id = '183722f0-ac65-43e7-b928-26efdb8654a8';
-- Fix Math for 1cbf9be0-4580-42cc-99af-8b8e92c9b97b (2.8)
UPDATE questions SET prompt = 'If $f(x)=(\cos x)(e^x)$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$-\\sin x \\cdot e^x + \\cos x \\cdot e^x$","explanation":"Correct. Product rule gives (-\\sin x)$$e^{x}$$ + (\\cos x)$$e^{x}$$."},{"id":"B","type":"text","label":"B","value":"$-\\sin x \\cdot e^x$","explanation":"This differentiates \\cos x but ignores the derivative of $$e^{x}$$."},{"id":"C","type":"text","label":"C","value":"$\\cos x \\cdot e^x$","explanation":"This ignores the derivative of \\cos x entirely."},{"id":"D","type":"text","label":"D","value":"$\\sin x \\cdot e^x + \\cos x \\cdot e^x$","explanation":"The derivative of \\cos x is -\\sin x, not +\\sin x."}]'::jsonb, updated_at = NOW() WHERE id = '1cbf9be0-4580-42cc-99af-8b8e92c9b97b';
-- Fix Math for 20a746ae-7223-4895-8a78-79cbdeaf172a (2.7)
UPDATE questions SET prompt = 'If $f(x)=4\cos x - 3\sin x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$-4\\sin x - 3\\cos x$","explanation":"Correct. Apply trig derivatives and linearity to get -4sin x - 3cos x."},{"id":"B","type":"text","label":"B","value":"$-4\\sin x + 3\\cos x$","explanation":"The sign on the second term is incorrect."},{"id":"C","type":"text","label":"C","value":"$4\\sin x - 3\\cos x$","explanation":"This has the wrong sign for the derivative of \\cos x."},{"id":"D","type":"text","label":"D","value":"$4\\cos x - 3\\sin x$","explanation":"This repeats the original function instead of differentiating."}]'::jsonb, updated_at = NOW() WHERE id = '20a746ae-7223-4895-8a78-79cbdeaf172a';
-- Fix Math for 243a4a21-b161-4357-9fe7-c0288508f525 (8.4)
UPDATE questions SET prompt = 'What is the area of the region between $y=x$ and $y=x^3$ on $[0,1]$?', options = '[{"id":"A","value":"$\\frac{1}{4}$"},{"id":"B","value":"$\\frac{1}{2}$"},{"id":"C","value":"$\\frac{3}{4}$"},{"id":"D","value":"$0$"}]'::jsonb, updated_at = NOW() WHERE id = '243a4a21-b161-4357-9fe7-c0288508f525';
-- Fix Math for 2812d7e8-6aa7-492d-8c60-d4ef49f2f8c6 (10.14)
UPDATE questions SET prompt = 'Refer to Table 10.14-A (U10.14_Practice_Table1_Coefficients.png). The shown coefficients match the beginning of which series?', options = '[{"id":"A","value":"\\ln(1+x) = x - x^\\frac{2}{2} + x^\\frac{3}{3} - x^\\frac{4}{4} + ..."},{"id":"B","value":"1/(1-x) = 1 + x + x^2 + x^3 + ..."},{"id":"C","value":"$$e^{x}$$ = 1 + x + x^\\frac{2}{2} + x^\\frac{3}{6} + ..."},{"id":"D","value":"\\sin x = x - x^\\frac{3}{6} + x^\\frac{5}{120} - ..."}]'::jsonb, updated_at = NOW() WHERE id = '2812d7e8-6aa7-492d-8c60-d4ef49f2f8c6';
-- Fix Math for 2c2b3da0-f358-43bd-8ccd-d3c1c92e32d4 (10.6)
UPDATE questions SET prompt = 'For large $n$, $\\frac{2n^2+1}{n^3-4n}$ behaves most like which term, making it a good choice for limit comparison?', options = '[{"id":"A","value":"\\frac{1}{n}"},{"id":"B","value":"\\frac{1}{n^2}"},{"id":"C","value":"\\frac{1}{n^3}"},{"id":"D","value":"n"}]'::jsonb, updated_at = NOW() WHERE id = '2c2b3da0-f358-43bd-8ccd-d3c1c92e32d4';
-- Fix Math for 2ed209be-7a0d-473b-b3b8-3f254cf47513 (10.1)
UPDATE questions SET prompt = 'Suppose $S_N=\\sum_{n=1}^{N} a_n$ satisfies $S_{2k}=1$ and $S_{2k-1}=0$ for all integers $k\\ge 1$. Which statement is correct about $\\sum_{n=1}^{\\infty} a_n$?', options = '[{"id":"A","value":"The series converges to \\frac{1}{2}"},{"id":"B","value":"The series converges to 1"},{"id":"C","value":"The series diverges because the partial sums do not approach a single limit"},{"id":"D","value":"The series converges because S_N is bounded"}]'::jsonb, updated_at = NOW() WHERE id = '2ed209be-7a0d-473b-b3b8-3f254cf47513';
-- Fix Math for 340f40ac-7ecd-41f2-a128-1ac98f227d6a (10.5)
UPDATE questions SET prompt = 'Determine whether the series $\\sum_{n=1}^{\\infty} \\frac{1}{n^{\frac{3}{2}}}$ converges or diverges.', options = '[{"id":"A","value":"Converges (p-series with p=\\frac{3}{2}>1)"},{"id":"B","value":"Diverges (p-series with p=\\frac{3}{2}>1)"},{"id":"C","value":"Converges because \\frac{1}{n}^{\\frac{3}{2}}→0"},{"id":"D","value":"Diverges because \\frac{1}{n}^{\\frac{3}{2}}→0"}]'::jsonb, updated_at = NOW() WHERE id = '340f40ac-7ecd-41f2-a128-1ac98f227d6a';
-- Fix Math for 382aa404-ba83-4409-b250-937e085ae233 (8.1)
UPDATE questions SET prompt = 'Values of $f$ are given in the table for $x=0,1,2,3,4$. Use the trapezoidal rule with $\\Delta x=1$ to approximate the average value of $f$ on $[0,4]$.', options = '[{"id":"A","value":"$\\frac{21}{8}$"},{"id":"B","value":"$\\frac{21}{4}$"},{"id":"C","value":"$\\frac{9}{4}$"},{"id":"D","value":"$\\frac{21}{2}$"}]'::jsonb, updated_at = NOW() WHERE id = '382aa404-ba83-4409-b250-937e085ae233';
-- Fix Math for 3f92f0dc-2b38-4563-8a4b-2dbc2203027e (2.10)
UPDATE questions SET prompt = 'If $f(x)=3\tan x - 2\cos x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$3\\sec^2 x + 2\\sin x$","explanation":"Correct. \\tan becomes sec^2, and -\\cos becomes +sin."},{"id":"B","type":"text","label":"B","value":"$3\\sec^2 x - 2\\sin x$","explanation":"The sign on the derivative of -2cos x is wrong."},{"id":"C","type":"text","label":"C","value":"$3\\sec x + 2\\sin x$","explanation":"\\sec x is not the derivative of \\tan x."},{"id":"D","type":"text","label":"D","value":"$3\\tan x + 2\\sin x$","explanation":"This fails to differentiate \\tan x correctly."}]'::jsonb, updated_at = NOW() WHERE id = '3f92f0dc-2b38-4563-8a4b-2dbc2203027e';
-- Fix Math for 400ea1f9-d6e4-4e2c-b64d-cb31b3636df3 (5.12)
UPDATE questions SET prompt = 'For the implicit relation $x^2 + x y + y^2 = 7$, what is the slope of the tangent line at the point $(2,1)$?', options = '[{"id":"A","type":"text","label":"A","value":"$-\\frac{5}{4}$","explanation":"Correct: correct substitution gives -\\frac{5}{4}."},{"id":"B","type":"text","label":"B","value":"$-\\frac{4}{5}$","explanation":"Incorrect: reciprocal error."},{"id":"C","type":"text","label":"C","value":"$\\frac{5}{4}$","explanation":"Incorrect: sign error."},{"id":"D","type":"text","label":"D","value":"$\\frac{4}{5}$","explanation":"Incorrect: sign and reciprocal are both wrong."}]'::jsonb, updated_at = NOW() WHERE id = '400ea1f9-d6e4-4e2c-b64d-cb31b3636df3';
-- Fix Math for 4201d232-25c3-4ceb-9f77-cb07fa1d6665 (10.5)
UPDATE questions SET prompt = 'For which value of $p$ does the series $\\sum_{n=1}^{\\infty}\\frac{1}{n^p}$ diverge?', options = '[{"id":"A","value":"p=2"},{"id":"B","value":"p=\\frac{3}{2}"},{"id":"C","value":"p=1"},{"id":"D","value":"p=4"}]'::jsonb, updated_at = NOW() WHERE id = '4201d232-25c3-4ceb-9f77-cb07fa1d6665';
-- Fix Math for 432288c0-0c3b-456a-aeef-07a638861fa8 (unit_test)
UPDATE questions SET prompt = 'If $f(x)=2x^3-4x+\sin x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$6x^2-4+\\cos x$","explanation":"Correct. Apply linearity and known derivative rules."},{"id":"B","type":"text","label":"B","value":"$6x^2-4+\\sin x$","explanation":"The derivative of \\sin x is \\cos x, not \\sin x."},{"id":"C","type":"text","label":"C","value":"$2x^2-4+\\cos x$","explanation":"The derivative of 2x^3 is 6x^2, not 2x^2."},{"id":"D","type":"text","label":"D","value":"$6x^2+4+\\cos x$","explanation":"The derivative of -4x is -4, not +4."}]'::jsonb, updated_at = NOW() WHERE id = '432288c0-0c3b-456a-aeef-07a638861fa8';
-- Fix Math for 44e18621-fe3a-4a50-85f5-a24af76806d9 (8.3)
UPDATE questions SET prompt = 'A quantity changes at rate $r(t)$ (units/hr). Values are given for $t=0,1,2,3,4$. Use the trapezoidal rule with $\\Delta t=1$ to approximate the change in the quantity over $[0,4]$.', options = '[{"id":"A","value":"$12$"},{"id":"B","value":"$\\frac{25}{2}$"},{"id":"C","value":"$13$"},{"id":"D","value":"$10$"}]'::jsonb, updated_at = NOW() WHERE id = '44e18621-fe3a-4a50-85f5-a24af76806d9';
-- Fix Math for 44f58c63-78f3-4a23-91d4-0e6e48196efe (2.7)
UPDATE questions SET prompt = 'If $f(x)=\sin x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$\\cos x$","explanation":"Correct. \\frac{d}{dx}(\\sin x) = \\cos x."},{"id":"B","type":"text","label":"B","value":"$-\\cos x$","explanation":"The negative sign belongs to the derivative of \\cos x, not \\sin x."},{"id":"C","type":"text","label":"C","value":"$\\sin x$","explanation":"This is the original function, not its derivative."},{"id":"D","type":"text","label":"D","value":"$-\\sin x$","explanation":"This is not the correct derivative rule for \\sin x."}]'::jsonb, updated_at = NOW() WHERE id = '44f58c63-78f3-4a23-91d4-0e6e48196efe';
-- Fix Math for 47b30eec-a645-47ae-8618-4b49f1b50c7c (10.12)
UPDATE questions SET prompt = 'Approximate $\\sin(0.1)$ using the 1st-degree Maclaurin polynomial $T_1(x)=x$. A Lagrange error bound is $|R_1(0.1)|\\le M\\frac{0.1^2}{2!}$ on $[0,0.1]$. For $\\sin x$, what is a valid choice for $M$ on this interval?', options = '[{"id":"A","value":"M = 0"},{"id":"B","value":"M = 1"},{"id":"C","value":"M = 0.1"},{"id":"D","value":"M = \\sin(0.1)"}]'::jsonb, updated_at = NOW() WHERE id = '47b30eec-a645-47ae-8618-4b49f1b50c7c';
-- Fix Math for 4823b93a-40eb-4dc5-bd37-d1b2fd59209e (9.1)
UPDATE questions SET prompt = 'The curve shown is given by $x(t)=t^2$ and $y(t)=t^3-t$. The point corresponding to $t=1$ is marked. What is the equation of the tangent line at $t=1$?', options = '[{"id":"A","value":"$y=x-1$"},{"id":"B","value":"$y=-x+1$"},{"id":"C","value":"$y=2x-2$"},{"id":"D","value":"$y=\\frac{1}{2x}-\\frac{1}{2}$"}]'::jsonb, updated_at = NOW() WHERE id = '4823b93a-40eb-4dc5-bd37-d1b2fd59209e';
-- Fix Math for 4f2cc00a-2274-4362-8594-fe05da5ceb9c (10.12)
UPDATE questions SET prompt = 'Use $T_2(x)=1+x+\\frac{x^2}{2}$ to approximate $e^{0.2}$. A valid Lagrange error bound is $|R_2(0.2)|\\le M\\frac{0.2^3}{3!}$ on $[0,0.2]$. What is $M$ for $f(x)=e^x$ on this interval?', options = '[{"id":"A","value":"M = $e^{0}$"},{"id":"B","value":"M = e^{0.2}"},{"id":"C","value":"M = 0.2"},{"id":"D","value":"M = 2"}]'::jsonb, updated_at = NOW() WHERE id = '4f2cc00a-2274-4362-8594-fe05da5ceb9c';
-- Fix Math for 5c62be24-43b3-4597-a213-1a41a88e53ae (10.6)
UPDATE questions SET prompt = 'Use limit comparison to determine the behavior of $\\sum_{n=1}^{\\infty}\\frac{3n+1}{n^2+5}$ by comparing to $\\sum_{n=1}^{\\infty}\\frac{1}{n}$.', options = '[{"id":"A","value":"Converges because the limit comparison constant is 0."},{"id":"B","value":"Diverges because the limit comparison constant is a finite positive number."},{"id":"C","value":"Converges because it is smaller than \\frac{1}{n}."},{"id":"D","value":"The limit comparison test cannot be used with \\frac{1}{n}."}]'::jsonb, updated_at = NOW() WHERE id = '5c62be24-43b3-4597-a213-1a41a88e53ae';
-- Fix Math for 5e169ee0-6316-4280-a797-5682e5a61493 (10.2)
UPDATE questions SET prompt = 'Consider the geometric series $\\sum_{n=0}^{\\infty} 5\\left(\\frac{1}{3}\\right)^n$. What is its sum?', options = '[{"id":"A","value":"5/(1-\\frac{1}{3})"},{"id":"B","value":"5/(1+\\frac{1}{3})"},{"id":"C","value":"1/(1-\\frac{1}{3})"},{"id":"D","value":"The series diverges because \\frac{1}{3}!=0"}]'::jsonb, updated_at = NOW() WHERE id = '5e169ee0-6316-4280-a797-5682e5a61493';
-- Fix Math for 61431c58-5f91-4526-aeb4-56966039a60f (9.2)
UPDATE questions SET prompt = 'A table of values at $t=2$ is shown. Using $\\frac{d^2y}{dx^2}=\\frac{\\frac{d}{dt}(\frac{dy}{dx})}{\frac{dx}{dt}}$, what is $\\frac{d^2y}{dx^2}$ at $t=2$?', options = '[{"id":"A","value":"$\\frac{3}{4}$"},{"id":"B","value":"$\\frac{4}{3}$"},{"id":"C","value":"$3$"},{"id":"D","value":"$\\frac{3}{8}$"}]'::jsonb, updated_at = NOW() WHERE id = '61431c58-5f91-4526-aeb4-56966039a60f';
-- Fix Math for 621c3822-cafe-47b0-ab32-bf321ed2fb48 (10.13)
UPDATE questions SET prompt = 'Find the radius of convergence of $\\sum_{n=1}^{\\infty} n\\left(\\frac{x}{3}\\right)^n$.', options = '[{"id":"A","value":"R = 1"},{"id":"B","value":"R = 3"},{"id":"C","value":"R = \\frac{1}{3}"},{"id":"D","value":"R = ∞"}]'::jsonb, updated_at = NOW() WHERE id = '621c3822-cafe-47b0-ab32-bf321ed2fb48';
-- Fix Math for 6838d020-97d2-499b-abda-a204e72b6efd (8.1)
UPDATE questions SET prompt = 'The graph of $f$ is shown on $[0,4]$. What is the average value of $f$ on $[0,4]$?', options = '[{"id":"A","value":"$1$"},{"id":"B","value":"$\\frac{3}{2}$"},{"id":"C","value":"$2$"},{"id":"D","value":"$3$"}]'::jsonb, updated_at = NOW() WHERE id = '6838d020-97d2-499b-abda-a204e72b6efd';
-- Fix Math for 69737486-d14c-40e6-8c8c-f71c5e557aca (2.8)
UPDATE questions SET prompt = 'If $f(x)=x^2\sin x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$2x \\sin x + x^2 \\cos x$","explanation":"Correct. Product rule gives 2x \\sin x + x^2 \\cos x."},{"id":"B","type":"text","label":"B","value":"$2x \\cos x + x^2 \\sin x$","explanation":"This mixes up which factor gets differentiated into \\cos x."},{"id":"C","type":"text","label":"C","value":"$x^2 \\cos x$","explanation":"This only differentiates \\sin x and ignores the derivative of x^2."},{"id":"D","type":"text","label":"D","value":"$2x \\sin x$","explanation":"This only differentiates x^2 and ignores the derivative of \\sin x."}]'::jsonb, updated_at = NOW() WHERE id = '69737486-d14c-40e6-8c8c-f71c5e557aca';
-- Fix Math for 6a3cd460-a07e-45f6-86ff-c7f8272cde07 (8.8)
UPDATE questions SET prompt = 'The base region $R$ is shown: $0\\le y\\le x$ for $0\\le x\\le 2$. Cross-sections perpendicular to the $x$-axis are right isosceles triangles whose legs equal the vertical width of $R$. What is the volume?', options = '[{"id":"A","value":"$\\frac{4}{3}$"},{"id":"B","value":"$\\frac{8}{3}$"},{"id":"C","value":"$2$"},{"id":"D","value":"$\\frac{2}{3}$"}]'::jsonb, updated_at = NOW() WHERE id = '6a3cd460-a07e-45f6-86ff-c7f8272cde07';
-- Fix Math for 6a8211d0-14d6-4294-8ac3-2065b42cecad (10.2)
UPDATE questions SET prompt = 'For the series $\\sum_{n=1}^{\\infty} 12\\left(-\\frac{2}{3}\\right)^{n-1}$, which statement is true?', options = '[{"id":"A","value":"It diverges because r<0"},{"id":"B","value":"It converges and its sum is 12/(1+\\frac{2}{3})"},{"id":"C","value":"It converges and its sum is 12/(1-(-\\frac{2}{3}))"},{"id":"D","value":"It diverges because |r|>1"}]'::jsonb, updated_at = NOW() WHERE id = '6a8211d0-14d6-4294-8ac3-2065b42cecad';
-- Fix Math for 6b7bb29a-de3d-4830-9095-62bceed17123 (8.4)
UPDATE questions SET prompt = 'The curves $y=x^2$ and $y=4x-x^2$ are shown on $[0,2]$. What is the area of the region between the curves on $[0,2]$?', options = '[{"id":"A","value":"$\\frac{8}{3}$"},{"id":"B","value":"$\\frac{4}{3}$"},{"id":"C","value":"$8$"},{"id":"D","value":"$\\frac{16}{3}$"}]'::jsonb, updated_at = NOW() WHERE id = '6b7bb29a-de3d-4830-9095-62bceed17123';
-- Fix Math for 6c28814b-a841-476c-826b-79f1bb72338b (unit_test)
UPDATE questions SET prompt = 'Which integrand is used to compute the arc length of $y=\\sin(x)$ on an interval (with respect to $x$)?', options = '[{"id":"A","value":"$\\sqrt$(1+co$s^2$($x$))"},{"id":"B","value":"$\\sqrt$(1+si$n^2$($x$))"},{"id":"C","value":"$1+\\cos(x)$"},{"id":"D","value":"$1+cos^2(x)$"}]'::jsonb, updated_at = NOW() WHERE id = '6c28814b-a841-476c-826b-79f1bb72338b';
-- Fix Math for 6d1f1f2e-5090-4f8f-a00d-16a85041bf56 (2.7)
UPDATE questions SET prompt = 'If $f(x)=\ln x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{1}{x}$","explanation":"Correct. \\frac{d}{dx}(\\ln x)=\\frac{1}{x}."},{"id":"B","type":"text","label":"B","value":"$\\ln x$","explanation":"This repeats the original function."},{"id":"C","type":"text","label":"C","value":"$e^x$","explanation":"$$e^{x}$$ is not the derivative of \\ln x."},{"id":"D","type":"text","label":"D","value":"$x$","explanation":"x is not the derivative of \\ln x."}]'::jsonb, updated_at = NOW() WHERE id = '6d1f1f2e-5090-4f8f-a00d-16a85041bf56';
-- Fix Math for 6f60db4b-bc51-44d4-bab8-af2ff6706945 (10.12)
UPDATE questions SET prompt = 'Refer to Table 10.12-A (U10.12_Practice_Table1_LagrangeBound.png), which lists bounds for using $T_2$ at $0$ to approximate $e^x$. Which statement is correct?', options = '[{"id":"A","value":"The bound depends on |x|^2 because the polynomial degree is 2."},{"id":"B","value":"For x>0, a valid choice is M=$$e^{x}$$ on [0,x]."},{"id":"C","value":"For x<0, M must be $$e^{x}$$ because that is always largest."},{"id":"D","value":"The bound is exact, so it equals the true error."}]'::jsonb, updated_at = NOW() WHERE id = '6f60db4b-bc51-44d4-bab8-af2ff6706945';
-- Fix Math for 73fa8c73-5409-41cc-92bf-4e6dd7ec9d57 (unit_test)
UPDATE questions SET prompt = 'If $f(x)=(x^2)(\cos x)$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$2x \\cos x - x^2 \\sin x$","explanation":"Correct. u''v + uv'' gives 2x \\cos x - x^2 \\sin x."},{"id":"B","type":"text","label":"B","value":"$2x \\cos x + x^2 \\sin x$","explanation":"The sign is wrong because (\\cos x)''=-\\sin x."},{"id":"C","type":"text","label":"C","value":"$x^2(-\\sin x)$","explanation":"This includes only uv'' and misses u''v."},{"id":"D","type":"text","label":"D","value":"$2x \\cos x$","explanation":"This includes only u''v and misses uv''."}]'::jsonb, updated_at = NOW() WHERE id = '73fa8c73-5409-41cc-92bf-4e6dd7ec9d57';
-- Fix Math for 78779b1b-59fd-4aea-965a-52b1579635b7 (9.2)
UPDATE questions SET prompt = 'Let $x(t)=t^2+1$ and $y(t)=t^3$. What is $\\frac{d^2y}{dx^2}$ when $t=1$?', options = '[{"id":"A","value":"$\\frac{3}{4}$"},{"id":"B","value":"$\\frac{3}{2}$"},{"id":"C","value":"$\\frac{1}{2}$"},{"id":"D","value":"$\\frac{3}{8}$"}]'::jsonb, updated_at = NOW() WHERE id = '78779b1b-59fd-4aea-965a-52b1579635b7';
-- Fix Math for 7c19f463-35e8-4cb2-b56f-3778f6bd60a9 (10.7)
UPDATE questions SET prompt = 'Consider the series $\\sum_{n=1}^{\\infty} \\frac{(-1)^{n+1}}{n}$. Which statement is correct?', options = '[{"id":"A","value":"It converges absolutely because ∑ \\frac{1}{n} converges."},{"id":"B","value":"It converges conditionally by the alternating series test."},{"id":"C","value":"It diverges because the terms alternate."},{"id":"D","value":"It diverges because \\frac{1}{n}→0."}]'::jsonb, updated_at = NOW() WHERE id = '7c19f463-35e8-4cb2-b56f-3778f6bd60a9';
-- Fix Math for 81053a67-a243-4df9-a902-fab4533825ae (10.5)
UPDATE questions SET prompt = 'Refer to Table 10.5-A (U10.5_Practice_Table1_Harmonic_vs_p2.png). Which statement is correct?', options = '[{"id":"A","value":"Both ∑ \\frac{1}{n} and ∑ \\frac{1}{n^2} diverge because their terms approach 0."},{"id":"B","value":"∑ \\frac{1}{n} converges and ∑ \\frac{1}{n^2} diverges."},{"id":"C","value":"∑ \\frac{1}{n} diverges and ∑ \\frac{1}{n^2} converges."},{"id":"D","value":"Both series converge because the terms decrease."}]'::jsonb, updated_at = NOW() WHERE id = '81053a67-a243-4df9-a902-fab4533825ae';
-- Fix Math for 85bda686-1664-4841-b4fc-81ef3370758f (2.10)
UPDATE questions SET prompt = 'If $f(x)=(\tan x)(x^2)$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$\\sec^2 x \\cdot x^2 + \\tan x \\cdot 2x$","explanation":"Correct. u''v + uv'' is sec^2 x * x^2 + \\tan x * 2x."},{"id":"B","type":"text","label":"B","value":"$\\sec^2 x \\cdot 2x$","explanation":"This differentiates both factors but multiplies them instead of adding terms."},{"id":"C","type":"text","label":"C","value":"$\\tan x \\cdot x^2$","explanation":"This does not differentiate at all."},{"id":"D","type":"text","label":"D","value":"$\\sec^2 x \\cdot x^2$","explanation":"This includes only the u''v part and misses uv''."}]'::jsonb, updated_at = NOW() WHERE id = '85bda686-1664-4841-b4fc-81ef3370758f';
-- Fix Math for 866720da-cafa-4f06-a648-aee393ee7f3e (4.7)
UPDATE questions SET prompt = 'Evaluate the limit as $x$ approaches $0$ of $\frac{1 - \cos x}{x^2}$ using L’Hospital’s Rule.', options = '[{"id":"A","type":"text","label":"A","value":"0","explanation":"If you stop too early, you may incorrectly conclude $0$."},{"id":"B","type":"text","label":"B","value":"\\frac{1}{2}","explanation":"Correct: repeated differentiation leads to $\\frac{1}{2}$."},{"id":"C","type":"text","label":"C","value":"1","explanation":"Too large; not the correct limiting constant."},{"id":"D","type":"text","label":"D","value":"2","explanation":"Far too large; inconsistent with small-angle behavior."}]'::jsonb, updated_at = NOW() WHERE id = '866720da-cafa-4f06-a648-aee393ee7f3e';
-- Fix Math for 8c2ddb77-9a6b-4212-aec1-fb9c0f558733 (10.2)
UPDATE questions SET prompt = 'Which series is geometric?', options = '[{"id":"A","value":"∑_{n=1}^{∞} \\frac{1}{n}"},{"id":"B","value":"∑_{n=0}^{∞} 3·2^n"},{"id":"C","value":"∑_{n=1}^{∞} \\frac{1}{n^2}"},{"id":"D","value":"∑_{n=1}^{∞} n/(n+1)"}]'::jsonb, updated_at = NOW() WHERE id = '8c2ddb77-9a6b-4212-aec1-fb9c0f558733';
-- Fix Math for 9636a22c-3a19-4c2a-a3c5-a8463714ad61 (10.8)
UPDATE questions SET prompt = 'Which series is typically best matched to the ratio test as a first choice?', options = '[{"id":"A","value":"∑ \\frac{1}{n^2}"},{"id":"B","value":"∑ \\ln(n)/n"},{"id":"C","value":"∑ n!/5^n"},{"id":"D","value":"∑ \\frac{1}{n}"}]'::jsonb, updated_at = NOW() WHERE id = '9636a22c-3a19-4c2a-a3c5-a8463714ad61';
-- Fix Math for 997b15cc-b985-4c56-a08a-8ae4cf99dfc6 (unit_test)
UPDATE questions SET prompt = 'If $f(x)=\cos x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$-\\sin x$","explanation":"Correct. \\frac{d}{dx}(\\cos x)=-\\sin x."},{"id":"B","type":"text","label":"B","value":"$\\sin x$","explanation":"This misses the negative sign."},{"id":"C","type":"text","label":"C","value":"$\\cos x$","explanation":"This is the original function."},{"id":"D","type":"text","label":"D","value":"$-\\cos x$","explanation":"This is not the correct trig derivative rule."}]'::jsonb, updated_at = NOW() WHERE id = '997b15cc-b985-4c56-a08a-8ae4cf99dfc6';
-- Fix Math for a1f651c4-75de-4ba2-aa34-65e69faf54f8 (8.5)
UPDATE questions SET prompt = 'For the region bounded by $x=y^2$ and $x=y+2$, the table gives $x_{\\text{left}}$, $x_{\\text{right}}$, and width for several $y$-values. Using the trapezoidal rule with $\\Delta y=1$, approximate the area of the region.', options = '[{"id":"A","value":"$3$"},{"id":"B","value":"$4$"},{"id":"C","value":"$\\frac{9}{2}$"},{"id":"D","value":"$5$"}]'::jsonb, updated_at = NOW() WHERE id = 'a1f651c4-75de-4ba2-aa34-65e69faf54f8';
-- Fix Math for a484a84d-07b5-435a-a497-308d7069756e (10.13)
UPDATE questions SET prompt = 'Find the radius of convergence of $\\sum_{n=1}^{\\infty}\\frac{(x+2)^n}{n^2\\,5^n}$.', options = '[{"id":"A","value":"R = 2"},{"id":"B","value":"R = 5"},{"id":"C","value":"R = \\frac{1}{5}"},{"id":"D","value":"R = ∞"}]'::jsonb, updated_at = NOW() WHERE id = 'a484a84d-07b5-435a-a497-308d7069756e';
-- Fix Math for b1d50a83-ca4c-4198-a784-fb80940e42e6 (4.4)
UPDATE questions SET prompt = 'Water is poured into a cone-shaped container. The cone has fixed height $5$ ft and fixed radius $2$ ft. The water level rises so that the water surface always forms a similar cone. Which relationship correctly connects the water radius $r$ and water height $h$?', options = '[{"id":"A","type":"text","label":"A","value":"$r = h + 3$","explanation":"Similarity creates a proportional ratio, not an additive shift."},{"id":"B","type":"text","label":"B","value":"$\\frac{r}{h} = \\frac{2}{5}$","explanation":"Correct: similarity gives $r/h = \\frac{2}{5}$."},{"id":"C","type":"text","label":"C","value":"$r = \\frac{5h}{2}$","explanation":"This reverses the correct proportional relationship."},{"id":"D","type":"text","label":"D","value":"$r^2 + h^2 = 29$","explanation":"This is a Pythagorean-type relationship, not from similarity."}]'::jsonb, updated_at = NOW() WHERE id = 'b1d50a83-ca4c-4198-a784-fb80940e42e6';
-- Fix Math for b32ee741-8962-4d97-8364-9570478428af (10.11)
UPDATE questions SET prompt = 'Refer to Table 10.11-A (U10.11_Practice_Table1_TaylorApprox.png), where $T_2(x)=1+x+\\frac{x^2}{2}$ approximates $e^x$. Which statement is best supported by the table?', options = '[{"id":"A","value":"The approximation is most accurate when x is closest to 0."},{"id":"B","value":"The approximation is equally accurate for all shown x values."},{"id":"C","value":"The approximation always overestimates $$e^{x}$$."},{"id":"D","value":"The approximation becomes more accurate as |x| increases."}]'::jsonb, updated_at = NOW() WHERE id = 'b32ee741-8962-4d97-8364-9570478428af';
-- Fix Math for ba3f16c0-8b0c-4f94-9500-0afd823b569b (9.1)
UPDATE questions SET prompt = 'Let $x(t)=t^2+1$ and $y(t)=3t-2$. What is $\\frac{dy}{dx}$ when $t=2$?', options = '[{"id":"A","value":"$\\frac{3}{4}$"},{"id":"B","value":"$\\frac{4}{3}$"},{"id":"C","value":"$\\frac{3}{2}$"},{"id":"D","value":"$\\frac{3}{8}$"}]'::jsonb, updated_at = NOW() WHERE id = 'ba3f16c0-8b0c-4f94-9500-0afd823b569b';
-- Fix Math for bd190d6c-24f6-48a2-a1f4-c49857c58c01 (10.7)
UPDATE questions SET prompt = 'Which series is best suited to be tested first with the alternating series test?', options = '[{"id":"A","value":"∑ \\frac{1}{n^2}"},{"id":"B","value":"∑ (-1)^{n+1} \\frac{1}{n}^{\\frac{3}{2}}"},{"id":"C","value":"∑ 2^n/n"},{"id":"D","value":"∑ \\frac{1}{3^n}"}]'::jsonb, updated_at = NOW() WHERE id = 'bd190d6c-24f6-48a2-a1f4-c49857c58c01';
-- Fix Math for c2767b81-d922-4d44-82f9-ebc804e30b26 (5.1)
UPDATE questions SET prompt = 'Let $f(x)=x^2-4x$ on $[1,3]$. Find a value $c$ in $(1,3)$ such that $f''(c)$ equals the average rate of change of $f$ on $[1,3]$.', options = '[{"id":"A","type":"text","label":"A","value":"$c=1$","explanation":"Incorrect: $c$ must be in $(1,3)$ and satisfy $f''(c)=0$; $f''(1)=-2$."},{"id":"B","type":"text","label":"B","value":"$c=\\frac{3}{2}$","explanation":"Incorrect: $f''(\\frac{3}{2})=3-4=-1$, not $0$."},{"id":"C","type":"text","label":"C","value":"$c=2$","explanation":"Correct: $f''(2)=0$ matches the average slope $0$."},{"id":"D","type":"text","label":"D","value":"$c=\\frac{5}{2}$","explanation":"Incorrect: $f''(\\frac{5}{2})=5-4=1$, not $0$."}]'::jsonb, updated_at = NOW() WHERE id = 'c2767b81-d922-4d44-82f9-ebc804e30b26';
-- Fix Math for c2f6f7da-f599-4b53-b171-f647fab31ad6 (10.8)
UPDATE questions SET prompt = 'For $a_n=\\frac{n!}{3^n}$, compute $\\left|\\frac{a_{n+1}}{a_n}\\right|$.', options = '[{"id":"A","value":"(n+1)/3"},{"id":"B","value":"3/(n+1)"},{"id":"C","value":"n/3"},{"id":"D","value":"\\frac{3}{n}"}]'::jsonb, updated_at = NOW() WHERE id = 'c2f6f7da-f599-4b53-b171-f647fab31ad6';
-- Fix Math for c51dff4b-9a2e-4a4a-9eb1-c4d47bbb6534 (4.7)
UPDATE questions SET prompt = 'Which expression is already in a form where L’Hospital’s Rule can be applied directly (assuming conditions are satisfied)?', options = '[{"id":"A","type":"text","label":"A","value":"$(x^2 + 1) / (x + 1)$ as $x$ approaches $1$","explanation":"This is determinate, not $\\frac{0}{0}$ or $\\infty/\\infty$."},{"id":"B","type":"text","label":"B","value":"$(x - 2) / (x^2 - 4)$ as $x$ approaches $2$","explanation":"Correct: it produces $\\frac{0}{0}$ at the limit point."},{"id":"C","type":"text","label":"C","value":"$(x^2 - 4) / (x - 2)$ as $x$ approaches $2$","explanation":"This simplifies to a finite value without needing L’Hospital."},{"id":"D","type":"text","label":"D","value":"$(x^2 + 4) / (x - 2)$ as $x$ approaches $2$","explanation":"This tends to $\\pm\\infty$, not an indeterminate form."}]'::jsonb, updated_at = NOW() WHERE id = 'c51dff4b-9a2e-4a4a-9eb1-c4d47bbb6534';
-- Fix Math for c5cbcbe4-d2e7-4511-831a-14edc9073c7d (8.8)
UPDATE questions SET prompt = 'The base region $R$ is shown: $0\\le y\\le \\sin x$ for $0\\le x\\le \\pi$. Cross-sections perpendicular to the $x$-axis are semicircles with diameter $\\sin x$. What is the volume?', options = '[{"id":"A","value":"$\\pi$^\\frac{2}{16}"},{"id":"B","value":"$\\pi$^\\frac{2}{8}"},{"id":"C","value":"$\\pi$/4"},{"id":"D","value":"$\\pi$/8"}]'::jsonb, updated_at = NOW() WHERE id = 'c5cbcbe4-d2e7-4511-831a-14edc9073c7d';
-- Fix Math for cbaff80f-3bfc-4eac-aa14-52978407d24b (10.4)
UPDATE questions SET prompt = 'Consider the series $\\sum_{n=2}^{\\infty} \\frac{1}{n\\ln(n)}$. If $f(x)=\\frac{1}{x\\ln(x)}$, which statement best matches the integral test conclusion?', options = '[{"id":"A","value":"The integral converges, so the series converges."},{"id":"B","value":"The integral diverges, so the series diverges."},{"id":"C","value":"The integral test cannot be applied because f(x) is positive."},{"id":"D","value":"The series converges because 1/(n \\ln(n))→0."}]'::jsonb, updated_at = NOW() WHERE id = 'cbaff80f-3bfc-4eac-aa14-52978407d24b';
-- Fix Math for cc5c3e35-bda4-45f7-b7e4-f7b2c30e6ecf (10.2)
UPDATE questions SET prompt = 'Which value of $r$ makes the geometric series $\\sum_{n=0}^{\\infty} 7r^n$ converge?', options = '[{"id":"A","value":"r=-2"},{"id":"B","value":"r=1"},{"id":"C","value":"r=\\frac{3}{2}"},{"id":"D","value":"r=-\\frac{3}{4}"}]'::jsonb, updated_at = NOW() WHERE id = 'cc5c3e35-bda4-45f7-b7e4-f7b2c30e6ecf';
-- Fix Math for ccac23a4-de5b-4e29-a10c-d1fa5b31e307 (10.11)
UPDATE questions SET prompt = 'What is the 2nd-degree Maclaurin polynomial for $e^x$?', options = '[{"id":"A","value":"1 + x + x^\\frac{2}{2}"},{"id":"B","value":"1 + x + x^2"},{"id":"C","value":"1 + x/2 + x^\\frac{2}{2}"},{"id":"D","value":"1 + x + x^\\frac{3}{6}"}]'::jsonb, updated_at = NOW() WHERE id = 'ccac23a4-de5b-4e29-a10c-d1fa5b31e307';
-- Fix Math for d4a2f98b-4a93-4279-800a-955f52dbe1ef (10.14)
UPDATE questions SET prompt = 'Let $e^x=1+x+\\frac{x^2}{2}+\\frac{x^3}{6}+\\cdots$. In the Maclaurin expansion of $x^2e^x$, what is the coefficient of $x^3$?', options = '[{"id":"A","value":"0"},{"id":"B","value":"1"},{"id":"C","value":"\\frac{1}{2}"},{"id":"D","value":"\\frac{1}{6}"}]'::jsonb, updated_at = NOW() WHERE id = 'd4a2f98b-4a93-4279-800a-955f52dbe1ef';
-- Fix Math for dbc7fdf0-87a5-4611-ac9f-895147a576f4 (8.7)
UPDATE questions SET prompt = 'The base region $R$ is shown: $0\\le y\\le \\sqrt{x}$ for $0\\le x\\le 4$. Cross-sections perpendicular to the $x$-axis are squares. What is the volume of the solid?', options = '[{"id":"A","value":"$8$"},{"id":"B","value":"$4$"},{"id":"C","value":"$16$"},{"id":"D","value":"$\\frac{32}{3}$"}]'::jsonb, updated_at = NOW() WHERE id = 'dbc7fdf0-87a5-4611-ac9f-895147a576f4';
-- Fix Math for dde972b3-8ff0-44ef-94c0-7551944318f7 (2.8)
UPDATE questions SET prompt = 'If $f(x)=x\ln x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$\\ln x + 1$","explanation":"Correct. Product rule gives \\ln x + 1."},{"id":"B","type":"text","label":"B","value":"\\frac{1}{x}","explanation":"This is only the derivative of \\ln x, missing the product rule."},{"id":"C","type":"text","label":"C","value":"x/x","explanation":"This simplifies to 1 but does not represent the full derivative."},{"id":"D","type":"text","label":"D","value":"$x \\ln x + 1$","explanation":"This incorrectly keeps x \\ln x in the derivative."}]'::jsonb, updated_at = NOW() WHERE id = 'dde972b3-8ff0-44ef-94c0-7551944318f7';
-- Fix Math for e5bfc943-7601-4e22-ad58-283a5e336f49 (2.8)
UPDATE questions SET prompt = 'Which method is most efficient for finding the derivative of $f(x)=(x^2+1)(\sin x)$?', options = '[{"id":"A","type":"text","label":"A","value":"Use the product rule.","explanation":"Correct. A product requires the product rule for an exact result."},{"id":"B","type":"text","label":"B","value":"Use only the power rule on $x^2+1$.","explanation":"Differentiating only one factor misses the contribution from \\sin x."},{"id":"C","type":"text","label":"C","value":"Use only the derivative of $\\sin x$.","explanation":"Differentiating only \\sin x ignores the derivative of x^2+1."},{"id":"D","type":"text","label":"D","value":"Estimate the derivative from a table.","explanation":"A table only approximates and is slower than rules."}]'::jsonb, updated_at = NOW() WHERE id = 'e5bfc943-7601-4e22-ad58-283a5e336f49';
-- Fix Math for e5e544b7-f580-4ba8-9c91-99a252ab4ecc (4.7)
UPDATE questions SET prompt = 'L’Hospital’s Rule is most directly applicable when a limit produces which type of indeterminate form?', options = '[{"id":"A","type":"text","label":"A","value":"A positive number divided by a positive number","explanation":"That is a determinate form, not indeterminate."},{"id":"B","type":"text","label":"B","value":"Zero divided by zero ($\\frac{0}{0}$), or infinity divided by infinity ($\\infty/\\infty$)","explanation":"Correct: the classic direct forms are $\\frac{0}{0}$ and $\\infty/\\infty$."},{"id":"C","type":"text","label":"C","value":"A negative number divided by a positive number","explanation":"This is determinate if the denominator is nonzero."},{"id":"D","type":"text","label":"D","value":"A positive number divided by zero","explanation":"This typically diverges and is not an indeterminate form."}]'::jsonb, updated_at = NOW() WHERE id = 'e5e544b7-f580-4ba8-9c91-99a252ab4ecc';
-- Fix Math for efdf6412-1289-4538-9ce6-acd1b67bafad (unit_test)
UPDATE questions SET prompt = 'If $f(x)=\ln x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{1}{x}$","explanation":"Correct. \\frac{d}{dx}(\\ln x)=\\frac{1}{x}."},{"id":"B","type":"text","label":"B","value":"$\\ln x$","explanation":"This repeats the original function."},{"id":"C","type":"text","label":"C","value":"$e^x$","explanation":"This is unrelated."},{"id":"D","type":"text","label":"D","value":"$x$","explanation":"This is unrelated."}]'::jsonb, updated_at = NOW() WHERE id = 'efdf6412-1289-4538-9ce6-acd1b67bafad';
-- Fix Math for f1639eb1-66f7-4ae0-ac51-668d017b92b6 (5.12)
UPDATE questions SET prompt = 'For the implicit relation $x^2 + x y + y^2 = 7$, which expression correctly gives $\frac{dy}{dx}$?', options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{dy}{dx} = -\\frac{2x + y}{x + 2y}$","explanation":"Correct: matches the result after collecting $\\frac{dy}{dx}$ terms."},{"id":"B","type":"text","label":"B","value":"$\\frac{dy}{dx} = -\\frac{2x + y}{2x + y}$","explanation":"Incorrect: would force $\\frac{dy}{dx} = -1$ always, which is not true."},{"id":"C","type":"text","label":"C","value":"$\\frac{dy}{dx} = \\frac{2x + y}{x + 2y}$","explanation":"Incorrect: sign error."},{"id":"D","type":"text","label":"D","value":"$\\frac{dy}{dx} = -\\frac{2x + 1}{1 + 2y}$","explanation":"Incorrect: treats $y$ like a constant and breaks the product structure."}]'::jsonb, updated_at = NOW() WHERE id = 'f1639eb1-66f7-4ae0-ac51-668d017b92b6';
-- Fix Math for f3451cc2-031f-4440-b416-770d3cbfe4b3 (10.11)
UPDATE questions SET prompt = 'What is the 2nd-degree Maclaurin polynomial for $\\ln(1+x)$?', options = '[{"id":"A","value":"x + x^\\frac{2}{2}"},{"id":"B","value":"x - x^\\frac{2}{2}"},{"id":"C","value":"1 + x - x^\\frac{2}{2}"},{"id":"D","value":"x - x^\\frac{2}{2} + x^\\frac{3}{3}"}]'::jsonb, updated_at = NOW() WHERE id = 'f3451cc2-031f-4440-b416-770d3cbfe4b3';
-- Fix Math for f4a8b441-6671-46a8-af4b-fffbd3b44763 (6.8)
UPDATE questions SET prompt = 'Find $\int \frac{1}{x}\,dx$ for $x>0$.', options = '[{"id":"A","value":"$\\ln x + C$","explanation":"Correct: derivative of $\\ln x$ is $\\frac{1}{x}$."},{"id":"B","value":"$\\frac{1}{x}+C$","explanation":"Wrong: derivative of $\\frac{1}{x}$ is $-\\frac{1}{x^2}$."},{"id":"C","value":"$x\\ln x + C$","explanation":"Wrong: derivative is $\\ln x + 1$, not $\\frac{1}{x}$."},{"id":"D","value":"$\\ln(x^2)+C$","explanation":"Wrong: $\\ln(x^2)=2\\ln x$, which would have derivative $\\frac{2}{x}$."}]'::jsonb, updated_at = NOW() WHERE id = 'f4a8b441-6671-46a8-af4b-fffbd3b44763';
-- Fix Math for f6e6fd46-cd9a-44ad-9f8a-4fc135e1112b (10.1)
UPDATE questions SET prompt = 'Let $a_n=\\frac{1}{n(n+1)}$ and $S_N=\\sum_{n=1}^{N} a_n$. Which expression for $S_N$ is correct?', options = '[{"id":"A","value":"S_N=N/(N+1)"},{"id":"B","value":"S_N=(N+1)/N"},{"id":"C","value":"S_N=\\ln(N+1)"},{"id":"D","value":"S_N=1/(N+1)"}]'::jsonb, updated_at = NOW() WHERE id = 'f6e6fd46-cd9a-44ad-9f8a-4fc135e1112b';
-- Fix Math for f79aa212-a98d-46e3-b9c8-ac3bbfde36f4 (8.7)
UPDATE questions SET prompt = 'A solid has cross-sectional area $A(x)=(x+1)^2$ for $0\\le x\\le 2$ (areas are in square units). What is the volume?', options = '[{"id":"A","value":"$\\frac{26}{3}$"},{"id":"B","value":"$\\frac{13}{3}$"},{"id":"C","value":"$9$"},{"id":"D","value":"$\\frac{8}{3}$"}]'::jsonb, updated_at = NOW() WHERE id = 'f79aa212-a98d-46e3-b9c8-ac3bbfde36f4';
-- Fix Math for f8cda24a-c64d-43d8-8848-d978318dd686 (unit_test)
UPDATE questions SET prompt = 'If $f(x)=2^x$, what is $f''(x)$?', options = '[{"id":"A","type":"text","label":"A","value":"$2^x \\ln 2$","explanation":"Correct. a^x derivative is a^x \\ln(a)."},{"id":"B","type":"text","label":"B","value":"$2^x$","explanation":"This is only true for $$e^{x}$$, not 2^x."},{"id":"C","type":"text","label":"C","value":"$\\ln x$","explanation":"This is a different function."},{"id":"D","type":"text","label":"D","value":"$\\frac{1}{x}$","explanation":"This is the derivative of \\ln x."}]'::jsonb, updated_at = NOW() WHERE id = 'f8cda24a-c64d-43d8-8848-d978318dd686';
-- Fix Math for f9d2fa17-d0e0-4712-892f-dad2169e34d4 (10.4)
UPDATE questions SET prompt = 'Consider the series $\\sum_{n=1}^{\\infty} \\frac{1}{n^2}$. Which statement is correct?', options = '[{"id":"A","value":"It diverges because \\frac{1}{n^2}→0."},{"id":"B","value":"It converges because it is a p-series with p>1."},{"id":"C","value":"It diverges because it is a p-series with p>1."},{"id":"D","value":"The p-series test is inconclusive when p=2."}]'::jsonb, updated_at = NOW() WHERE id = 'f9d2fa17-d0e0-4712-892f-dad2169e34d4';
-- Fix Math for fa0fcc32-64fe-4bd5-9684-67ed0ad9ffac (10.5)
UPDATE questions SET prompt = 'Which series is the harmonic series?', options = '[{"id":"A","value":"∑_{n=1}^{∞} \\frac{1}{n}"},{"id":"B","value":"∑_{n=1}^{∞} \\frac{1}{n^2}"},{"id":"C","value":"∑_{n=1}^{∞} \\frac{1}{2^n}"},{"id":"D","value":"∑_{n=1}^{∞} \\frac{1}{n}!"}]'::jsonb, updated_at = NOW() WHERE id = 'fa0fcc32-64fe-4bd5-9684-67ed0ad9ffac';
-- Fix Math for fa8b3065-6c60-4b7e-8c45-fa68fa79fcbf (8.7)
UPDATE questions SET prompt = 'The base region $R$ is shown in the first quadrant, bounded by $x=y^2$, $x=4$, and $y=0$. Cross-sections perpendicular to the $y$-axis are rectangles with height $2$. What is the volume?', options = '[{"id":"A","value":"$\\frac{32}{3}$"},{"id":"B","value":"$\\frac{16}{3}$"},{"id":"C","value":"$8$"},{"id":"D","value":"$16$"}]'::jsonb, updated_at = NOW() WHERE id = 'fa8b3065-6c60-4b7e-8c45-fa68fa79fcbf';
-- Total Updates: 74
