
-- SQL MIGRATION GENERATED BY SCRIPT

-- Fixed 1.10 P4 Missing Graph
UPDATE questions SET 
  prompt = '["Use the graph provided. What is $\\lim_{x\\to 2} f(x)$?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"image","label":"A","value":"[\"$\\\\infty$\",\"https://xzpjlnkirboevkjzitcx.supabase.co/storage/v1/object/public/images/questions/b55d71f0-0649-4ca1-ab0e-2bb06e7f286a/1769383775068_nhfm4.jpg\"]","explanation":"Correct: both sides rise upward without bound as $x$ approaches 2."},{"id":"B","type":"text","label":"B","value":"$-\\infty$","explanation":"The graph does not decrease without bound; it increases."},{"id":"C","type":"text","label":"C","value":"0","explanation":"The graph does not approach 0 near $x=2$."},{"id":"D","type":"text","label":"D","value":"DNE","explanation":"The limit is an infinite limit ($\\infty$), which is a valid limit statement here."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = 'b06360c6-c478-442e-956b-41b946d58257';

-- Fixed 1.14 Missing Graph for 4a20b9f3-7002-470a-b576-e8a4850d729c
UPDATE questions SET 
  prompt = '["Use the graph provided. Which statement is correct?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"image","label":"A","value":"[\"$\\\\lim_{x\\\\to 1^-} f(x)=\\\\infty$ and $\\\\lim_{x\\\\to 1^+} f(x)=\\\\infty$\",\"https://xzpjlnkirboevkjzitcx.supabase.co/storage/v1/object/public/images/questions/b55d71f0-0649-4ca1-ab0e-2bb06e7f286a/1769384224211_xnrzy.jpg\"]","explanation":"Left side goes downward, not upward."},{"id":"B","type":"text","label":"B","value":"$\\lim_{x\\to 1^-} f(x)=-\\infty$ and $\\lim_{x\\to 1^+} f(x)=\\infty$","explanation":"Correct: opposite infinite behavior on the two sides."},{"id":"C","type":"text","label":"C","value":"$\\lim_{x\\to 1^-} f(x)=0$ and $\\lim_{x\\to 1^+} f(x)=0$","explanation":"The function does not approach 0 near the asymptote."},{"id":"D","type":"text","label":"D","value":"$\\lim_{x\\to 1} f(x)$ exists and equals 1","explanation":"With opposite infinite behavior, the two-sided limit does not exist."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '4a20b9f3-7002-470a-b576-e8a4850d729c';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Evaluate $\lim_{x\to \infty} \frac{4x^2-3}{2x^2+7x}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"0","explanation":"0 would occur if the denominator had higher degree, but degrees are equal here."},{"id":"B","type":"text","label":"B","value":"2","explanation":"Correct: equal degree gives ratio of leading coefficients $\\frac{4}{2}=2$."},{"id":"C","type":"text","label":"C","value":"$\\frac{1}{2}$","explanation":"This is the reciprocal of the correct ratio."},{"id":"D","type":"text","label":"D","value":"$\\infty$","explanation":"A rational function with equal degree approaches a finite value, not infinity."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'f2158552-ce7a-43c0-a13d-1da8103a5a5b';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Evaluate $\lim_{x\to 2} \frac{(x^2-4)}{(x-2)}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"0","explanation":"0 comes from stopping at $\\frac{0}{0}$ or claiming the limit is 0."},{"id":"B","type":"text","label":"B","value":"2","explanation":"This is a common arithmetic slip after simplification."},{"id":"C","type":"text","label":"C","value":"4","explanation":"Correct: simplify to $x+2$ then substitute $x=2$ to get 4."},{"id":"D","type":"text","label":"D","value":"DNE","explanation":"The limit exists after algebraic simplification."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'ed9ed524-ace7-4e8f-831d-f9afe6fc1812';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Evaluate $\lim_{x\to 1} \frac{x-1}{x^2-1}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"0","explanation":"0 comes from claiming $\\frac{0}{0}$ becomes 0 without simplification."},{"id":"B","type":"text","label":"B","value":"$\\frac{1}{2}$","explanation":"Correct: simplifies to $\\frac{1}{x+1}\\to\\frac{1}{2}$."},{"id":"C","type":"text","label":"C","value":"$\\frac{1}{2x}$","explanation":"This is the simplified expression written incorrectly as a final value."},{"id":"D","type":"text","label":"D","value":"DNE","explanation":"After cancellation, the limit exists."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '93cff0de-5d7c-40ed-8492-2b741df23cad';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Evaluate $\lim_{x\to 2} \frac{x^2-5x+6}{x-2}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$-1$","explanation":"Correct: simplifies to $x-3\\to-1$."},{"id":"B","type":"text","label":"B","value":"0","explanation":"0 often comes from stopping at $\\frac{0}{0}$ or incorrect cancellation."},{"id":"C","type":"text","label":"C","value":"1","explanation":"1 is a common sign mistake after simplification."},{"id":"D","type":"text","label":"D","value":"DNE","explanation":"After simplification, the limit exists."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '51448cae-3144-4bde-b809-392cdfe4dfa2';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Which method is most appropriate to evaluate $\lim_{x\to 3} \frac{x^2-9}{x-3}$?',
  options = '[{"id":"A","type":"text","label":"A","value":"Direct substitution","explanation":"Substitution gives $\\frac{0}{0}$, so more work is needed."},{"id":"B","type":"text","label":"B","value":"Factor and cancel","explanation":"Correct: factor $x^2-9=(x-3)(x+3)$ and cancel."},{"id":"C","type":"text","label":"C","value":"Multiply by a conjugate","explanation":"Conjugates are used for radicals, not this factorable expression."},{"id":"D","type":"text","label":"D","value":"Use a table of values","explanation":"A table is optional, but algebra is the standard exact method."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '7e5e4219-1a50-4b7c-8f66-caf8a4aca5db';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Which method is most appropriate to evaluate $\lim_{x\to 0} \frac{\sqrt{x+9}-3}{x}$?',
  options = '[{"id":"A","type":"text","label":"A","value":"Direct substitution","explanation":"Substitution gives $\\frac{0}{0}$, so it does not finish the problem."},{"id":"B","type":"text","label":"B","value":"Factor and cancel","explanation":"Factoring does not remove the radical difference form."},{"id":"C","type":"text","label":"C","value":"Multiply by a conjugate","explanation":"Correct: conjugate rationalization removes the radical and cancels $x$."},{"id":"D","type":"text","label":"D","value":"Use IVT","explanation":"IVT is about existence of roots, not evaluating a limit."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '8a284217-7c14-4f3b-876f-f2d56e95ca85';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Evaluate $\lim_{x\to \infty} \frac{\sin x}{x}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$-1$","explanation":"The expression shrinks toward 0 because the denominator grows without bound."},{"id":"B","type":"text","label":"B","value":"0","explanation":"Correct: it is squeezed between $\\pm \\frac{1}{x}$ which go to 0."},{"id":"C","type":"text","label":"C","value":"1","explanation":"The expression does not stay near 1."},{"id":"D","type":"text","label":"D","value":"DNE","explanation":"Even though $\\sin x$ oscillates, the factor $\\frac{1}{x}$ forces the limit to 0."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'b47292a2-5ca2-486b-af57-cabf8ff5f4fe';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Evaluate $\lim_{x\to 0} x^2\sin\left(\frac{1}{x}\right)$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$-1$","explanation":"The expression is squeezed to 0, not -1."},{"id":"B","type":"text","label":"B","value":"0","explanation":"Correct: the bounds force the limit to be 0."},{"id":"C","type":"text","label":"C","value":"1","explanation":"The expression does not approach 1; it shrinks to 0."},{"id":"D","type":"text","label":"D","value":"DNE","explanation":"Although $\\sin(\\frac{1}{x})$ oscillates, multiplying by $x^2$ forces the limit to 0."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'ad9b29d7-485b-43d8-956c-8770a3f580c5';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Let $f(x)=\frac{x^2-1}{x-1}$ for $x\ne 1$. What is $\lim_{x\to 1} f(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"0","explanation":"0 comes from incorrectly substituting into the unsimplified $\\frac{0}{0}$ form."},{"id":"B","type":"text","label":"B","value":"1","explanation":"1 is a common arithmetic mistake after simplification."},{"id":"C","type":"text","label":"C","value":"2","explanation":"Correct: simplified function approaches 2."},{"id":"D","type":"text","label":"D","value":"DNE","explanation":"The limit exists after cancellation."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'cd685f61-7b8b-4bb8-b637-349deaf4d681';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=\tan x$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\sec^2 x$","explanation":"Correct. \\frac{d}{dx}(tan x)=sec^2 x."},{"id":"B","type":"text","label":"B","value":"$\\csc^2 x$","explanation":"csc^2 x is the derivative of -cot x, not tan x."},{"id":"C","type":"text","label":"C","value":"$\\sec x$","explanation":"sec x is not the derivative of tan x."},{"id":"D","type":"text","label":"D","value":"$-\\sec^2 x$","explanation":"The derivative is positive sec^2 x, not negative."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '0f1685a4-0118-4400-bfa2-63f046bddd3e';

-- Fixed 2.3 Markdown Image for 512e4ef2-cfb6-48ac-91da-fae6d237ea84
UPDATE questions SET 
  prompt = '["The table gives values of $f(x)$. Use the table to estimate $f''(3)$.","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"-2","explanation":"This is too negative compared with the near-symmetric table values."},{"id":"B","type":"text","label":"B","value":"-0.5","explanation":"This is still too negative; the values suggest almost no change near x=3."},{"id":"C","type":"text","label":"C","value":"0","explanation":"Correct. The table suggests the slope near x=3 is approximately 0."},{"id":"D","type":"text","label":"D","value":"2","explanation":"This is too positive compared with the table trend."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '512e4ef2-cfb6-48ac-91da-fae6d237ea84';

-- Fixed 2.3 Markdown Image for ca6b2eda-8919-4bff-9da7-84bdb3322cb2
UPDATE questions SET 
  prompt = '["The graph of $y=g(x)$ is shown, along with the tangent line at $x=1$. What is $g''(1)$?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"-2","explanation":"The tangent is not decreasing at x=1; it is flat."},{"id":"B","type":"text","label":"B","value":"-1","explanation":"The tangent is not decreasing; it is horizontal."},{"id":"C","type":"text","label":"C","value":"0","explanation":"Correct. The slope of a horizontal tangent line is 0."},{"id":"D","type":"text","label":"D","value":"2","explanation":"A positive slope would tilt upward, but the tangent is flat."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = 'ca6b2eda-8919-4bff-9da7-84bdb3322cb2';

-- Fixed 2.3 Markdown Image for 4cf08aad-480a-4ee7-8ad3-aa81da9665a5
UPDATE questions SET 
  prompt = '["The graph of $y=f(x)$ is shown, along with the tangent line at $x=2$. What is the best estimate of $f''(2)$?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"1","explanation":"This underestimates the steepness of the tangent line."},{"id":"B","type":"text","label":"B","value":"2","explanation":"Correct. f''(2) matches the tangent slope, about 2."},{"id":"C","type":"text","label":"C","value":"3","explanation":"This is steeper than the tangent line shown."},{"id":"D","type":"text","label":"D","value":"4","explanation":"This is much steeper than the tangent line shown."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '4cf08aad-480a-4ee7-8ad3-aa81da9665a5';

-- Fixed 2.3 Markdown Image for 72dd142e-bef9-4f05-b426-56c2c61e8c27
UPDATE questions SET 
  prompt = '["The graph of $y=p(x)$ is shown, along with the tangent line at $x=4$. What is the best estimate of $p''(4)$?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"-1.2","explanation":"This is too steep downward compared to the tangent line shown."},{"id":"B","type":"text","label":"B","value":"-0.3","explanation":"Correct. The tangent line shows a small negative slope, about -0.3."},{"id":"C","type":"text","label":"C","value":"0","explanation":"The tangent is not horizontal; it is decreasing."},{"id":"D","type":"text","label":"D","value":"0.3","explanation":"The tangent is decreasing, so the slope cannot be positive."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '72dd142e-bef9-4f05-b426-56c2c61e8c27';

-- Fixed 2.3 Markdown Image for 22333f09-d3e6-4f04-b4ba-a6781c1cb98c
UPDATE questions SET 
  prompt = '["The graph of $y=h(x)$ is shown, along with the tangent line at $x=0$. What is the best estimate of $h''(0)$?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"0","explanation":"The tangent line is not horizontal; it has a small positive slope."},{"id":"B","type":"text","label":"B","value":"0.3","explanation":"Correct. The tangent line shows a small positive slope, about 0.3."},{"id":"C","type":"text","label":"C","value":"1","explanation":"This is too steep for the tangent line shown."},{"id":"D","type":"text","label":"D","value":"3","explanation":"This is far too steep for the tangent line shown."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '22333f09-d3e6-4f04-b4ba-a6781c1cb98c';

-- Fixed 2.4 Markdown Image for 1d9802c3-0bb0-4ee2-b28b-e4c3f9d62d74
UPDATE questions SET 
  prompt = '["The graph of $y=f(x)$ is shown. Is $f$ differentiable at $x=1$?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"Yes, because the function has a defined value at x=1","explanation":"Having a defined value does not guarantee continuity or differentiability."},{"id":"B","type":"text","label":"B","value":"Yes, because both sides approach finite values","explanation":"Even if each side approaches a finite value, they must match for continuity."},{"id":"C","type":"text","label":"C","value":"No, because the function is not continuous at x=1","explanation":"Correct. Not continuous at x=1, so not differentiable."},{"id":"D","type":"text","label":"D","value":"No, because the tangent slope at x=1 is zero","explanation":"The graph does not show a zero tangent slope; the issue is discontinuity."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '1d9802c3-0bb0-4ee2-b28b-e4c3f9d62d74';

-- Fixed 2.4 Markdown Image for 8819d62b-11ae-4131-9a73-f9060b516421
UPDATE questions SET 
  prompt = '["The graph of $y=f(x)$ is shown. Which statement is true about $f$ at $x=0$?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"f is continuous at x=0 and differentiable at x=0","explanation":"A sharp corner prevents differentiability at that point."},{"id":"B","type":"text","label":"B","value":"f is continuous at x=0 but not differentiable at x=0","explanation":"Correct. Continuous at the corner, but not differentiable."},{"id":"C","type":"text","label":"C","value":"f is not continuous at x=0 but is differentiable at x=0","explanation":"A function cannot be differentiable at a point where it is not continuous."},{"id":"D","type":"text","label":"D","value":"f is neither continuous nor differentiable at x=0","explanation":"The function is continuous at x=0; only differentiability fails."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '8819d62b-11ae-4131-9a73-f9060b516421';

-- Fixed 2.4 Markdown Image for 408aed1b-0bf7-4b20-9168-ce3048175967
UPDATE questions SET 
  prompt = '["The graph of $y=f(x)$ is shown. Which statement is true about $f$ at $x=2$?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"f is continuous at x=2 because the function has a value there","explanation":"Continuity requires matching the limit, not just having a defined value."},{"id":"B","type":"text","label":"B","value":"The limit of f(x) as x approaches 2 exists, but f is not continuous at x=2","explanation":"Correct. The limit exists, but f(2) does not equal that limit."},{"id":"C","type":"text","label":"C","value":"f is differentiable at x=2 because the graph is a straight line nearby","explanation":"Even if the nearby graph is linear, the discontinuity prevents differentiability."},{"id":"D","type":"text","label":"D","value":"f is not continuous at x=2 because the function goes to infinity","explanation":"The graph does not show infinite behavior; it shows a removable discontinuity."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '408aed1b-0bf7-4b20-9168-ce3048175967';

-- Fixed 2.4 Markdown Image for d90dc96e-148d-4ac8-a406-2903dbd38e8a
UPDATE questions SET 
  prompt = '["The graph of $y=f(x)$ is shown. Which statement is true about $f$ at $x=1$?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"f is differentiable at x=1 because the graph is unbroken there","explanation":"Continuity does not guarantee differentiability."},{"id":"B","type":"text","label":"B","value":"f is continuous at x=1 but not differentiable at x=1","explanation":"Correct. Vertical tangent means not differentiable, but the graph is continuous."},{"id":"C","type":"text","label":"C","value":"f is not continuous at x=1 but is differentiable at x=1","explanation":"Differentiability cannot happen without continuity."},{"id":"D","type":"text","label":"D","value":"f is neither continuous nor differentiable at x=1","explanation":"The graph is continuous at x=1, so this is too strong."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = 'd90dc96e-148d-4ac8-a406-2903dbd38e8a';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=x^{\frac{1}{2}}$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{1}{2}x^{-\\frac{1}{2}}$","explanation":"Correct. Multiply by \\frac{1}{2} and subtract 1 from the exponent."},{"id":"B","type":"text","label":"B","value":"$\\frac{1}{2}x^{\\frac{1}{2}}$","explanation":"This multiplies by \\frac{1}{2} but forgets to change the exponent."},{"id":"C","type":"text","label":"C","value":"$x^{-\\frac{1}{2}}$","explanation":"This misses the coefficient \\frac{1}{2}."},{"id":"D","type":"text","label":"D","value":"$-\\frac{1}{2}x^{-\\frac{3}{2}}$","explanation":"This uses the wrong exponent change."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'add0bc6f-e828-405d-87ea-f5e224796bf1';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=\sin x$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\cos x$","explanation":"Correct. \\frac{d}{dx}(sin x) = cos x."},{"id":"B","type":"text","label":"B","value":"$-\\cos x$","explanation":"The negative sign belongs to the derivative of cos x, not sin x."},{"id":"C","type":"text","label":"C","value":"$\\sin x$","explanation":"This is the original function, not its derivative."},{"id":"D","type":"text","label":"D","value":"$-\\sin x$","explanation":"This is not the correct derivative rule for sin x."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '44f58c63-78f3-4a23-91d4-0e6e48196efe';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=\ln x$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{1}{x}$","explanation":"Correct. \\frac{d}{dx}(ln x)=\\frac{1}{x}."},{"id":"B","type":"text","label":"B","value":"$\\ln x$","explanation":"This repeats the original function."},{"id":"C","type":"text","label":"C","value":"$e^x$","explanation":"e^x is not the derivative of ln x."},{"id":"D","type":"text","label":"D","value":"$x$","explanation":"x is not the derivative of ln x."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '6d1f1f2e-5090-4f8f-a00d-16a85041bf56';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=e^x$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$e^x$","explanation":"Correct. \\frac{d}{dx}(e^x)=e^x."},{"id":"B","type":"text","label":"B","value":"$xe^{x-1}$","explanation":"This is not a valid derivative rule for e^x."},{"id":"C","type":"text","label":"C","value":"$\\ln x$","explanation":"ln x is a different function, not the derivative of e^x."},{"id":"D","type":"text","label":"D","value":"$\\frac{1}{x}$","explanation":"\\frac{1}{x} is the derivative of ln x, not e^x."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '020c11da-da5a-4654-b7ff-6fdcabcf592e';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=x\ln x$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\ln x + 1$","explanation":"Correct. Product rule gives ln x + 1."},{"id":"B","type":"text","label":"B","value":"\\frac{1}{x}","explanation":"This is only the derivative of ln x, missing the product rule."},{"id":"C","type":"text","label":"C","value":"x/x","explanation":"This simplifies to 1 but does not represent the full derivative."},{"id":"D","type":"text","label":"D","value":"$x \\ln x + 1$","explanation":"This incorrectly keeps x ln x in the derivative."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'dde972b3-8ff0-44ef-94c0-7551944318f7';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=\frac{\ln x}{x}$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{(\\frac{1}{x})(x) - (\\ln x)(1)}{x^2}$","explanation":"Correct. u''v - uv'' over v^2 gives the right structure."},{"id":"B","type":"text","label":"B","value":"$\\frac{(\\frac{1}{x})(x) + (\\ln x)(1)}{x^2}$","explanation":"This uses + instead of - in the numerator."},{"id":"C","type":"text","label":"C","value":"$\\frac{\\frac{1}{x}}{x}$","explanation":"This ignores the subtraction term from the quotient rule."},{"id":"D","type":"text","label":"D","value":"$\\frac{\\ln x}{x^2}$","explanation":"This changes only the denominator and is missing the u''v term."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '3828181b-4115-4bf0-bc85-5f5813ca1857';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Find the derivative of $h(x)=\sqrt{x^2+1}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{1}{2\\sqrt{x^2+1}}$","explanation":"This differentiates the outside but ignores the derivative of the inside $x^2+1$."},{"id":"B","type":"text","label":"B","value":"$\\frac{x}{\\sqrt{x^2+1}}$","explanation":"Correct: outer gives $\\frac{1}{2}(x^2+1)^{-\\frac{1}{2}}$ and inner gives $2x$."},{"id":"C","type":"text","label":"C","value":"$\\frac{2x}{\\sqrt{x^2+1}}$","explanation":"This doubles the result; the factor 2 should cancel with the outer $\\frac{1}{2}$."},{"id":"D","type":"text","label":"D","value":"$\\sqrt{x^2+1}$","explanation":"This is the original function, not its derivative."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '5ba089cb-f6b9-427f-8b66-dec62446e2f6';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $3x^2+2y=xy$, find $\frac{dy}{dx}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{y-6x}{2-x}$","explanation":"Correct: $6x+2(\\frac{dy}{dx})=x(\\frac{dy}{dx})+y$ leading to $(2-x)\\frac{dy}{dx}=y-6x$."},{"id":"B","type":"text","label":"B","value":"$\\frac{6x-y}{2-x}$","explanation":"This has the numerator sign reversed."},{"id":"C","type":"text","label":"C","value":"$\\frac{y-6x}{x-2}$","explanation":"This is equivalent to choice B after multiplying top/bottom by -1."},{"id":"D","type":"text","label":"D","value":"$\\frac{6x-y}{x-2}$","explanation":"This matches the wrong sign pattern from incorrect rearranging."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'eb432132-45c2-4c67-a8dc-b16e3e885d16';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Given $xy=x+y$, find $\frac{dy}{dx}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{1-y}{x-1}$","explanation":"Correct: $x(\\frac{dy}{dx})+y=1+(\\frac{dy}{dx})$ so $(x-1)\\frac{dy}{dx}=1-y$."},{"id":"B","type":"text","label":"B","value":"$\\frac{y-1}{x-1}$","explanation":"This flips the sign in the numerator."},{"id":"C","type":"text","label":"C","value":"$\\frac{1+y}{x+1}$","explanation":"This comes from differentiating as if it were a quotient or from incorrect algebra."},{"id":"D","type":"text","label":"D","value":"$\\frac{y-1}{1-x}$","explanation":"This is algebraically equivalent to choice B, not the correct result."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '813fb837-2d2c-496e-a3d0-9d2aabd140cc';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $x^2+xy+y^2=7$, what is $\frac{dy}{dx}$ at the point $(1,2)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$-\\frac{4}{5}$","explanation":"Correct: after implicit differentiation, substitute $(1,2)$ and solve for $\\frac{dy}{dx}$."},{"id":"B","type":"text","label":"B","value":"$\\frac{4}{5}$","explanation":"This misses the negative sign from moving terms."},{"id":"C","type":"text","label":"C","value":"$-\\frac{5}{4}$","explanation":"This is the reciprocal of the correct answer."},{"id":"D","type":"text","label":"D","value":"$\\frac{5}{4}$","explanation":"This has both the reciprocal and the sign wrong."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '9948ca83-d7e5-436a-9732-7a0459aa8485';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $x^2+y^2=25$, find $\frac{dy}{dx}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{dy}{dx}=\\frac{x}{y}$","explanation":"The sign is incorrect after moving terms to isolate $\\frac{dy}{dx}$."},{"id":"B","type":"text","label":"B","value":"$\\frac{dy}{dx}=-\\frac{x}{y}$","explanation":"Correct: $2x+2y(\\frac{dy}{dx})=0 \\Rightarrow \\frac{dy}{dx}=-x/y$."},{"id":"C","type":"text","label":"C","value":"$\\frac{dy}{dx}=\\frac{y}{x}$","explanation":"This swaps numerator and denominator incorrectly."},{"id":"D","type":"text","label":"D","value":"$\\frac{dy}{dx}=-\\frac{y}{x}$","explanation":"This swaps the fraction and changes the sign incorrectly."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '59ef59bc-c73f-499e-9eb5-4572d8ac5352';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'The table below gives values of $f$ and $f''$. What is $(f^{-1})''(5)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$4$","explanation":"This uses $f''(2)$ directly instead of taking the reciprocal."},{"id":"B","type":"text","label":"B","value":"$\\frac{1}{4}$","explanation":"Correct: since $f(2)=5$, we use $(f^{-1})''(5)=\\frac{1}{f}''(2)=\\frac{1}{4}$."},{"id":"C","type":"text","label":"C","value":"$\\frac{1}{5}$","explanation":"This incorrectly uses the output 5 as if it were the derivative value."},{"id":"D","type":"text","label":"D","value":"$\\frac{5}{4}$","explanation":"This incorrectly mixes the output with the derivative."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '43f54028-932d-4324-93bd-bc7b66d4aa60';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'The graph of $f$ is shown. The tangent line at $x=3$ is drawn. What is $(f^{-1})''(1)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$2$","explanation":"This uses the tangent slope directly instead of taking the reciprocal."},{"id":"B","type":"text","label":"B","value":"$\\frac{1}{2}$","explanation":"Correct: the tangent slope at $x=3$ is $2$, so the inverse slope at the corresponding output is $\\frac{1}{2}$."},{"id":"C","type":"text","label":"C","value":"$-2$","explanation":"This incorrectly changes the sign of the slope."},{"id":"D","type":"text","label":"D","value":"$-\\frac{1}{2}$","explanation":"This uses the reciprocal but incorrectly changes the sign."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '2c8a01b6-04cf-4640-8859-1e7693ddff10';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Let $f$ be differentiable and invertible. If $f(3)=4$ and $f''(3)=5$, find $\frac{d}{dx}\left[f^{-1}(x^2)\right]$ at $x=2$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{1}{5}$","explanation":"This uses $(f^{-1})''(4)=\\frac{1}{5} but forgets to multiply by $2x$ at $x=2$."},{"id":"B","type":"text","label":"B","value":"$\\frac{2}{5}$","explanation":"This multiplies by $2$ instead of by $2x$ at $x=2$."},{"id":"C","type":"text","label":"C","value":"$\\frac{4}{5}$","explanation":"Correct: $(f^{-1})''(4)=\\frac{1}{f}''(3)=\\frac{1}{5}$, then multiply by $2x=4$ giving $\\frac{4}{5}$."},{"id":"D","type":"text","label":"D","value":"$\\frac{5}{4}$","explanation":"This flips the fraction and mixes inputs incorrectly."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'd90169b7-1b2d-4b99-b142-5fbf168c4e47';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(2)=5$ and $f''(2)=3$, what is $(f^{-1})''(5)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$3$","explanation":"This incorrectly uses $f''(2)$ instead of taking its reciprocal."},{"id":"B","type":"text","label":"B","value":"$\\frac{1}{3}$","explanation":"Correct: $(f^{-1})''(5)=\\frac{1}{f}''(2)=\\frac{1}{3}$."},{"id":"C","type":"text","label":"C","value":"$\\frac{1}{5}$","explanation":"This incorrectly uses the output value 5 in the reciprocal step."},{"id":"D","type":"text","label":"D","value":"$\\frac{5}{3}$","explanation":"This mixes the output and derivative values incorrectly."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'd59b784d-995b-4b67-8fc4-ae8cab832f9d';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(1)=4$ and $f''(1)=-2$, what is $(f^{-1})''(4)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$-2$","explanation":"This uses $f''(1)$ instead of taking its reciprocal."},{"id":"B","type":"text","label":"B","value":"$\\frac{1}{2}$","explanation":"This ignores the negative sign from $f''(1)=-2$."},{"id":"C","type":"text","label":"C","value":"$-\\frac{1}{2}$","explanation":"Correct: $(f^{-1})''(4)=\\frac{1}{f}''(1)=-\\frac{1}{2}$."},{"id":"D","type":"text","label":"D","value":"$2$","explanation":"This is the opposite sign and wrong magnitude."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'e83c7313-4921-4d24-bfd9-5cb3c28fc38b';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Which method is most appropriate to find $\frac{dy}{dx}$ if $x^2y+\sin(y)=3$?',
  options = '[{"id":"A","type":"text","label":"A","value":"Implicit differentiation (with product rule on $x^2y$)","explanation":"Correct: $x^2y$ requires product structure and $\\sin(y)$ requires \\frac{dy}{dx}."},{"id":"B","type":"text","label":"B","value":"Derivative of an inverse function","explanation":"No inverse relationship is given."},{"id":"C","type":"text","label":"C","value":"Only the chain rule","explanation":"Chain rule alone is not sufficient; the equation is implicit."},{"id":"D","type":"text","label":"D","value":"Higher-order derivatives first","explanation":"You must find the first derivative method before thinking about higher-order."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'ddd27b7b-19ad-4540-8b4e-644ed93bd859';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Which method is most appropriate to evaluate $\lim_{x\to 2} \frac{x^2-4}{x-2}$?',
  options = '[{"id":"A","type":"text","label":"A","value":"Direct substitution","explanation":"Substitution gives an indeterminate form $\\frac{0}{0}$."},{"id":"B","type":"text","label":"B","value":"Factor and cancel","explanation":"Correct: factoring removes the removable discontinuity."},{"id":"C","type":"text","label":"C","value":"Multiply by a conjugate","explanation":"Conjugates are for radicals, not polynomials."},{"id":"D","type":"text","label":"D","value":"Use IVT","explanation":"IVT is unrelated to evaluating this limit."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'a3d4039d-b209-4027-9fd1-093c022401d0';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Evaluate $\lim_{x\to 0} \frac{\sqrt{1+x}-1}{x}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$0$","explanation":"The expression approaches a nonzero finite value."},{"id":"B","type":"text","label":"B","value":"$\\frac{1}{2}$","explanation":"Correct: conjugate simplifies to $1/(\\sqrt{1+x}+1)\\to \\frac{1}{2}$."},{"id":"C","type":"text","label":"C","value":"$1$","explanation":"This would occur if you forget the +1 in the denominator."},{"id":"D","type":"text","label":"D","value":"$2$","explanation":"This is the reciprocal of the correct value."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '4be50f42-dfe8-46b0-a397-ce4bcb1d0402';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=\ln x$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{1}{x}$","explanation":"Correct. \\frac{d}{dx}(ln x)=\\frac{1}{x}."},{"id":"B","type":"text","label":"B","value":"$\\ln x$","explanation":"This repeats the original function."},{"id":"C","type":"text","label":"C","value":"$e^x$","explanation":"This is unrelated."},{"id":"D","type":"text","label":"D","value":"$x$","explanation":"This is unrelated."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'efdf6412-1289-4538-9ce6-acd1b67bafad';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=2^x$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$2^x \\ln 2$","explanation":"Correct. a^x derivative is a^x ln(a)."},{"id":"B","type":"text","label":"B","value":"$2^x$","explanation":"This is only true for e^x, not 2^x."},{"id":"C","type":"text","label":"C","value":"$\\ln x$","explanation":"This is a different function."},{"id":"D","type":"text","label":"D","value":"$\\frac{1}{x}$","explanation":"This is the derivative of ln x."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'f8cda24a-c64d-43d8-8848-d978318dd686';

-- Fixed UT2 Markdown Image for 271d5001-ab77-40ee-863d-ecb908e00ee7
UPDATE questions SET 
  prompt = '["The graph of $f$ is provided. Estimate $f''(1)$.","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"About 2","explanation":"Correct. The slope looks positive and near 2."},{"id":"B","type":"text","label":"B","value":"About 0","explanation":"The tangent is not flat at x=1."},{"id":"C","type":"text","label":"C","value":"About -2","explanation":"The function is increasing at x=1, so the slope is not negative."},{"id":"D","type":"text","label":"D","value":"About 4","explanation":"This is too steep compared to the visible tangent."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '271d5001-ab77-40ee-863d-ecb908e00ee7';

-- Fixed UT2 Markdown Image for 4eb3349b-6d4c-469f-9a3b-aada3e83c2c1
UPDATE questions SET 
  prompt = '["The graph of $g$ is provided. At $x=0$, which is true?","https://placehold.co/600x400/png?text=Graph+Missing"]',
  options = '[{"id":"A","type":"text","label":"A","value":"$g$ is continuous but not differentiable.","explanation":"Correct. A corner is continuous but not differentiable."},{"id":"B","type":"text","label":"B","value":"$g$ is differentiable but not continuous.","explanation":"Differentiable implies continuous, so this cannot happen."},{"id":"C","type":"text","label":"C","value":"$g$ is neither continuous nor differentiable.","explanation":"The graph does not break at x=0, so it is continuous."},{"id":"D","type":"text","label":"D","value":"$g$ is differentiable and has $g''(0)=0$.","explanation":"A corner means the derivative does not exist at x=0."}]'::jsonb,
  prompt_type = 'text_and_image',
  updated_at = NOW()
WHERE id = '4eb3349b-6d4c-469f-9a3b-aada3e83c2c1';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'If $f(x)=\cos x$, what is $f''(x)$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$-\\sin x$","explanation":"Correct. \\frac{d}{dx}(cos x)=-sin x."},{"id":"B","type":"text","label":"B","value":"$\\sin x$","explanation":"This misses the negative sign."},{"id":"C","type":"text","label":"C","value":"$\\cos x$","explanation":"This is the original function."},{"id":"D","type":"text","label":"D","value":"$-\\cos x$","explanation":"This is not the correct trig derivative rule."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '997b15cc-b985-4c56-a08a-8ae4cf99dfc6';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'The tangent line to $y=f(x)$ at $x=2$ has slope 4, and $f(2)=5$. What is the equation of the normal line at $x=2$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$y-5=-(\\frac{1}{4})(x-2)$","explanation":"Correct. Normal slope is -\\frac{1}{4} through (2,5)."},{"id":"B","type":"text","label":"B","value":"$y-5=4(x-2)$","explanation":"This is the tangent line slope, not the normal."},{"id":"C","type":"text","label":"C","value":"$y-5=(\\frac{1}{4})(x-2)$","explanation":"This uses the reciprocal but misses the negative sign."},{"id":"D","type":"text","label":"D","value":"$y-2=-(\\frac{1}{4})(x-5)$","explanation":"This uses the correct slope form but the point is wrong."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '754f482a-844c-422c-b23d-aff2d66ca4fc';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Find the derivative of $y=\sqrt{5x^2-1}$.',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{10x}{\\sqrt{5x^2-1}}$","explanation":"This is too large by a factor of 2; it forgets the outer derivative coefficient $\\frac{1}{2}$."},{"id":"B","type":"text","label":"B","value":"$\\frac{5x}{\\sqrt{5x^2-1}}$","explanation":"Correct: $\\frac{1}{2}(5x^2-1)^{-\\frac{1}{2}}\\cdot 10x=\\frac{5x}{\\sqrt{5x^2-1}}$."},{"id":"C","type":"text","label":"C","value":"$\\frac{10}{\\sqrt{5x^2-1}}$","explanation":"This drops the variable factor $x$ incorrectly."},{"id":"D","type":"text","label":"D","value":"$\\frac{1}{2\\sqrt{5x^2-1}}$","explanation":"This only differentiates the outer square root and ignores the inside derivative."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'c5013f1b-d22c-40ac-9b2a-04cce9be4846';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Which expression produces a $\frac{0}{0}$ form as $x$ approaches $2$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{x^2-4}{x-2}$","explanation":"This is $\\frac{0}{0}$ too, but it simplifies cleanly without L’Hospital."},{"id":"B","type":"text","label":"B","value":"$\\frac{x^2+4}{x-2}$","explanation":"This goes to a nonzero/$0$ form, not $\\frac{0}{0}$."},{"id":"C","type":"text","label":"C","value":"$\\frac{x-2}{x^2-4}$","explanation":"Correct: numerator and denominator both go to $0$ at $x=2$."},{"id":"D","type":"text","label":"D","value":"$\\frac{x^2+1}{x+1}$","explanation":"This is determinate at $x=2$."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '75e5fa48-b47f-4bf4-b2ab-65a3dfd8e00f';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Which limit form is directly appropriate for applying L’Hospital’s Rule (assuming conditions are met)?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{5}{7}$","explanation":"This is determinate, not indeterminate."},{"id":"B","type":"text","label":"B","value":"$\\frac{0}{0}$","explanation":"Correct: $\\frac{0}{0}$ is an indeterminate form."},{"id":"C","type":"text","label":"C","value":"$\\frac{3}{0}$","explanation":"This typically diverges and is not indeterminate."},{"id":"D","type":"text","label":"D","value":"$\\frac{0}{5}$","explanation":"This equals $0$, not indeterminate."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '304b711c-69e9-4052-adb3-8f09af6d01c2';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Evaluate the limit as $x$ approaches $0$ of $\\frac{\\sin x - x}{x^3}$ using L’Hospital’s Rule.',
  options = '[{"id":"A","type":"text","label":"A","value":"$-\\frac{1}{6}$","explanation":"Correct: repeated differentiation gives a negative constant $-\\frac{1}{6}$."},{"id":"B","type":"text","label":"B","value":"0","explanation":"Stopping too early may incorrectly suggest $0$."},{"id":"C","type":"text","label":"C","value":"$\\frac{1}{6}$","explanation":"Correct magnitude but wrong sign."},{"id":"D","type":"text","label":"D","value":"1","explanation":"Much too large for this small-angle limit."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '5dabb2e1-5bd2-40f8-9485-d5b6c46fea30';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'A student sees a $\frac{0}{0}$ limit and immediately applies L’Hospital’s Rule, even though factoring would cancel a common factor in one step. Which best describes the AP-style strategy?',
  options = '[{"id":"A","type":"text","label":"A","value":"Always use L’Hospital because it is more advanced.","explanation":"Advanced does not mean best; efficiency matters."},{"id":"B","type":"text","label":"B","value":"Choose the simplest valid method; factoring may be faster and cleaner.","explanation":"Correct: simplest correct method is preferred."},{"id":"C","type":"text","label":"C","value":"Never factor when a derivative method exists.","explanation":"Factoring is often the cleanest way to remove $\\frac{0}{0}$."},{"id":"D","type":"text","label":"D","value":"L’Hospital is required whenever $\\frac{0}{0}$ appears.","explanation":"L’Hospital is optional, not required in every $\\frac{0}{0}$ case."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '6d0ae77d-f1ad-4445-b420-6d5b88b87f8e';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'For the implicit relation $x^2 + x y + y^2 = 7$, which expression correctly gives $\frac{dy}{dx}$?',
  options = '[{"id":"A","type":"text","label":"A","value":"$\\frac{dy}{dx} = -\\frac{2x + y}{x + 2y}$","explanation":"Correct: Correct collection of $\\frac{dy}{dx}$ terms."},{"id":"B","type":"text","label":"B","value":"$\\frac{dy}{dx} = -\\frac{2x + y}{2x + y}$","explanation":"Incorrect: Would force $\\frac{dy}{dx}$=-1 always, which is not true."},{"id":"C","type":"text","label":"C","value":"$\\frac{dy}{dx} = \\frac{2x + y}{x + 2y}$","explanation":"Incorrect: Sign error."},{"id":"D","type":"text","label":"D","value":"$\\frac{dy}{dx} = -\\frac{2x + 1}{1 + 2y}$","explanation":"Incorrect: Breaks the product differentiation structure."}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '3ed0605e-79c0-4239-bbbd-a263a437f3af';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Let $f(x)=x^2-1$. What is the average value of $f$ on $[0,2]$?',
  options = '[{"id":"A","value":"$\\frac{1}{3}$"},{"id":"B","value":"$\\frac{2}{3}$"},{"id":"C","value":"$\\frac{4}{3}$"},{"id":"D","value":"$\\frac{1}{6}$"}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '60aea1df-a460-485b-8013-12ddffdcf88c';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'The base region $R$ is shown between $y=x$ and $y=2$ for $0\\le x\\le 2$. Cross-sections perpendicular to the $x$-axis are squares. What is the volume?',
  options = '[{"id":"A","value":"$\\frac{8}{3}$"},{"id":"B","value":"$4$"},{"id":"C","value":"$\\frac{16}{3}$"},{"id":"D","value":"8$\\pi$/3"}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'a5266a5e-801a-42eb-b4a8-035d81680c60';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Use limit comparison to determine $\\sum_{n=1}^{\\infty}\\frac{3n^2+1}{n^3-4}$.',
  options = '[{"id":"A","value":"Converges (like ∑\\frac{1}{n^2})"},{"id":"B","value":"Diverges (like ∑\\frac{1}{n})"},{"id":"C","value":"Diverges because it is geometric"},{"id":"D","value":"Converges by alternating series test"}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '7f6d1929-542e-4efa-9385-e56cfcada878';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'What is the 3rd-degree Maclaurin polynomial for $\\sin x$?',
  options = '[{"id":"A","value":"x + x^\\frac{3}{6}"},{"id":"B","value":"x - x^\\frac{3}{6}"},{"id":"C","value":"1 - x + x^\\frac{2}{2}"},{"id":"D","value":"x - x^\\frac{2}{2}"}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '9de35a25-9aec-45a4-a67a-184e7d8ab26e';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Determine the behavior of $\\sum_{n=1}^{\\infty}\\frac{1}{n^2+1}$.',
  options = '[{"id":"A","value":"Converges by comparison with ∑\\frac{1}{n^2}"},{"id":"B","value":"Diverges by comparison with ∑\\frac{1}{n^2}"},{"id":"C","value":"Diverges by the nth-term test"},{"id":"D","value":"Converges only if alternating"}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = 'b6995059-a35c-4d1d-8534-c6a400cecc8c';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Does $\\sum_{n=1}^{\\infty}\\frac{n}{n+1}$ converge?',
  options = '[{"id":"A","value":"Converges by comparison with ∑\\frac{1}{n^2}"},{"id":"B","value":"Converges by telescoping"},{"id":"C","value":"Diverges because lim_{n→∞} n/(n+1) ≠ 0"},{"id":"D","value":"Converges because terms are less than 1"}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '196d1013-501e-4b7a-a2a4-1a57d2885f28';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Which series is an example of conditional convergence?',
  options = '[{"id":"A","value":"∑\\frac{1}{n^2}"},{"id":"B","value":"∑(-1)^n \\frac{1}{n}"},{"id":"C","value":"∑(-1)^n \\frac{1}{n^2}"},{"id":"D","value":"∑\\frac{1}{n}"}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '04b65a33-db22-4e56-83f2-ee93a097dae4';

-- Auto-fix content content
UPDATE questions SET 
  prompt = 'Use the Ratio Test to determine $\\sum_{n=1}^{\\infty}\\frac{n!}{3^n}$.',
  options = '[{"id":"A","value":"Converges because the limit is \\frac{1}{3}"},{"id":"B","value":"Diverges because the ratio limit is ∞"},{"id":"C","value":"Converges by p-series"},{"id":"D","value":"Diverges by the Integral Test"}]'::jsonb,
  prompt_type = 'text',
  updated_at = NOW()
WHERE id = '7a4898c5-ea34-49e9-8bf6-d2c5bf729c20';

-- Fix Section 2.7 Title
UPDATE sections SET title = '2.7 Derivatives of $\cos x$, $\sin x$, $e^x$, and $\ln x$' WHERE id = '2.7';
