-- SQL MIGRATION PART 4 (FINAL FIXES)
-- Fix Part 4 for 56541f46-f0a5-40c5-9d6a-55a39efe0c80
UPDATE questions SET prompt = 'Consider $f(x)=\\frac{1}{x}$ on $(0,1]$. Which statement is true?', options = '[{"id":"A","text":"$f$ has an absolute maximum on $(0,1]$.","value":"$f$ has an absolute maximum on $(0,1]$."},{"id":"B","text":"$f$ has an absolute minimum on $(0,1]$.","value":"$f$ has an absolute minimum on $(0,1]$."},{"id":"C","text":"$f$ has both an absolute maximum and minimum on $(0,1]$ by EVT.","value":"$f$ has both an absolute maximum and minimum on $(0,1]$ by EVT."},{"id":"D","text":"$f$ has neither an absolute maximum nor an absolute minimum on $(0,1]$.","value":"$f$ has neither an absolute maximum nor an absolute minimum on $(0,1]$."}]'::jsonb, updated_at = NOW() WHERE id = '56541f46-f0a5-40c5-9d6a-55a39efe0c80';
-- Fix Part 4 for 5e169ee0-6316-4280-a797-5682e5a61493
UPDATE questions SET prompt = 'Consider the geometric series $\\sum_{n=0}^{\\infty} 5\\left(\\$\frac{1}{3}$\\right)^n$. What is its sum?', options = '[{"id":"A","value":"5/(1-\\$\\frac{1}{3}$)"},{"id":"B","value":"5/(1+\\$\\frac{1}{3}$)"},{"id":"C","value":"1/(1-\\$\\frac{1}{3}$)"},{"id":"D","value":"The series diverges because \\$\\frac{1}{3}$$\\neq$0"}]'::jsonb, updated_at = NOW() WHERE id = '5e169ee0-6316-4280-a797-5682e5a61493';
-- Fix Part 4 for 74f9ad60-45c5-43cc-a37b-0addd0270ffc
UPDATE questions SET prompt = 'Which statement must be true?', options = '[{"id":"A","text":"If $f$ has an absolute maximum at $x=c$ in $(a,b)$, then $f''(c)=0$.","value":"If $f$ has an absolute maximum at $x=c$ in $(a,b)$, then $f''(c)=0$."},{"id":"B","text":"If $f''(c)=0$, then $f$ has a local maximum at $x=c$.","value":"If $f''(c)=0$, then $f$ has a local maximum at $x=c$."},{"id":"C","text":"If $f$ has a local maximum at $x=c$, then $f(c)$ is the absolute maximum on $[a,b]$.","value":"If $f$ has a local maximum at $x=c$, then $f(c)$ is the absolute maximum on $[a,b]$."},{"id":"D","text":"If $f$ is continuous on $(a,b)$, then $f$ has an absolute maximum on $(a,b)$.","value":"If $f$ is continuous on $(a,b)$, then $f$ has an absolute maximum on $(a,b)$."}]'::jsonb, updated_at = NOW() WHERE id = '74f9ad60-45c5-43cc-a37b-0addd0270ffc';
-- Fix Part 4 for 7e1fe3de-5a9c-422d-b076-42dd8a6de041
UPDATE questions SET prompt = 'Let $f(x)=x^3-3x$ on $[-2,2]$. At which $x$-values must you evaluate $f$ to find the absolute maximum and minimum on $[-2,2]$?', options = '[{"id":"A","text":"$x=-2,0,2$","value":"$x=-2,0,2$"},{"id":"B","text":"$x=-1,1$","value":"$x=-1,1$"},{"id":"C","text":"$x=-2,-1,1,2$","value":"$x=-2,-1,1,2$"},{"id":"D","text":"$x=0$ only","value":"$x=0$ only"}]'::jsonb, updated_at = NOW() WHERE id = '7e1fe3de-5a9c-422d-b076-42dd8a6de041';
-- Fix Part 4 for e97d9f47-cd92-4659-8656-39a7fa1c88b7
UPDATE questions SET prompt = 'Which statement is sufficient to guarantee that a function $f$ has both an absolute maximum and an absolute minimum on $[a,b]$?', options = '[{"id":"A","text":"$f$ is continuous on $[a,b]$.","value":"$f$ is continuous on $[a,b]$."},{"id":"B","text":"$f$ is differentiable on $(a,b)$.","value":"$f$ is differentiable on $(a,b)$."},{"id":"C","text":"$f$ is continuous on $(a,b)$.","value":"$f$ is continuous on $(a,b)$."},{"id":"D","text":"$f$ is differentiable on $[a,b]$.","value":"$f$ is differentiable on $[a,b]$."}]'::jsonb, updated_at = NOW() WHERE id = 'e97d9f47-cd92-4659-8656-39a7fa1c88b7';
-- Fix Part 4 for ed37296f-ebee-40e6-86ab-4e7265ae61a9
UPDATE questions SET prompt = 'Let $f(x)=|x-2|+\\frac{1}{x}$ with domain $x\ne 0$. Which $x$-values are critical numbers of $f$?', options = '[{"id":"A","text":"$x=0$ only","value":"$x=0$ only"},{"id":"B","text":"$x=2$ only","value":"$x=2$ only"},{"id":"C","text":"$x=2$ and $x=0$","value":"$x=2$ and $x=0$"},{"id":"D","text":"None","value":"None"}]'::jsonb, updated_at = NOW() WHERE id = 'ed37296f-ebee-40e6-86ab-4e7265ae61a9';
-- Total Updates: 6
