-- Attributes:
--   id: text
--   name: text
--   unit: text
--   metadata: jsonb

INSERT INTO public.skills (id, name, unit, prerequisites)
VALUES

('SK_ALGEBRA_RATIONAL', 'Working with Rational Functions', 'Unit 9', '{}'),
('SK_EVALUATE_AT_PARAMETER', 'Evaluating at a Parameter Value', 'Unit 9', '{}'),
('SK_PARAM_CONCAVITY_FROM_T', 'Concavity of Parametric Curves', 'Unit 9', '{}'),
('SK_PARAM_DYDX_FROM_T', 'Finding dy/dx from Parametric Equations', 'Unit 9', '{}'),
('SK_PARAM_ELIMINATE_PARAMETER', 'Eliminating the Parameter', 'Unit 9', '{}'),
('SK_PARAM_HORIZONTAL_VERTICAL_TANGENTS', 'Horizontal and Vertical Tangents (Parametric)', 'Unit 9', '{}'),
('SK_PARAM_SECOND_DERIVATIVE', 'Second Derivative of Parametric Curves', 'Unit 9', '{}'),
('SK_DOT_PRODUCT', 'Dot Product', 'Unit 9', '{}'),
('SK_INTEGRATION_SUB', 'Integration by Substitution', 'Unit 9', '{}'),
('SK_TRIG_DERIV', 'Derivatives of Trigonometric Functions (General)', 'Unit 9', '{}'),
('SK_U9_ARC_LENGTH', 'Arc Length of Parametric Curves (Unit 9)', 'Unit 9', '{}'),
('SK_U9_DYDX_PARAM', 'Finding dy/dx from Parametric Equations (Unit 9)', 'Unit 9', '{}'),
('SK_U9_PARAM_SPEED', 'Speed of a Particle (Parametric)', 'Unit 9', '{}'),
('SK_U9_TANGENT_LINE', 'Tangent Line to a Parametric Curve (Vector Form)', 'Unit 9', '{}'),
('SK_U9_VECTOR_DERIV', 'Derivative of a Vector-Valued Function', 'Unit 9', '{}'),
('SK_U9_VECTOR_SPEED', 'Speed of a Vector-Valued Function', 'Unit 9', '{}'),
('SK_PARAM_TANGENT_LINE', 'Tangent Line to a Parametric Curve', 'Unit 9', '{}'),
('SK_PARAM_TANGENT_SLOPE_ZERO', 'Finding Where Tangent Slope is Zero (Parametric)', 'Unit 9', '{}'),
('SK_SOLVE_TRIG_EQUATIONS', 'Solving Trigonometric Equations', 'Unit 9', '{}'),
('SK_VV_INT_COMPONENTWISE', 'Vector-Valued Integration (Componentwise)', 'Unit 9', '{}'),
('SK_DEF_INT_VECTOR_DISPLACEMENT', 'Definite Integral as Vector Displacement', 'Unit 9', '{}'),
('SK_VV_POSITION_FROM_VELOCITY', 'Position from Velocity (Vector)', 'Unit 9', '{}'),
('SK_INITIAL_CONDITION_VECTOR', 'Applying Vector Initial Conditions', 'Unit 9', '{}'),
('SK_DISPLACEMENT_VS_DISTANCE', 'Displacement vs Distance (Vector)', 'Unit 9', '{}'),
('SK_VV_AVERAGE_VALUE', 'Average Value of Vector-Valued Function', 'Unit 9', '{}'),
('SK_VECTOR_SCALAR_MULTIPLICATION', 'Vector Scalar Multiplication', 'Unit 9', '{}'),
('SK_VELOCITY_VECTOR_FROM_POSITION', 'Velocity Vector from Position', 'Unit 9', '{}'),
('SK_SPEED_MAGNITUDE', 'Speed as Magnitude of Velocity', 'Unit 9', '{}'),
('SK_PARTICLE_STOPS_SOLVE_VELOCITY_ZERO', 'Particle Stops (Velocity Zero)', 'Unit 9', '{}'),
('SK_ACCELERATION_VECTOR', 'Acceleration Vector', 'Unit 9', '{}'),
('SK_POLAR_DYDX', 'Polar dy/dx Formula', 'Unit 9', '{}'),
('SK_CHAIN_RULE', 'Chain Rule', 'Unit 9', '{}'),
('SK_POLAR_TANGENT_TESTS', 'Polar Horizontal/Vertical Tangents', 'Unit 9', '{}'),
('SK_POLAR_EQUIVALENT_COORDS', 'Equivalent Polar Coordinates', 'Unit 9', '{}'),
('SK_PRODUCT_RULE', 'Product Rule', 'Unit 9', '{}'),
('SK_POLAR_GRAPH_MATCH', 'Polar Graph Matching', 'Unit 9', '{}'),
('SK_POLAR_SYMMETRY', 'Polar Symmetry Tests', 'Unit 9', '{}'),
('SK_POLAR_AREA_SINGLE', 'Area of Polar Region (Single Curve)', 'Unit 9', '{}'),
('SK_TRIG_IDENTITY_HALF_ANGLE', 'Half-Angle Identities', 'Unit 9', '{}'),
('SK_BOUNDS_TRACE_ONCE', 'Polar Bounds Tracing Once', 'Unit 9', '{}'),
('SK_POLAR_AREA_BETWEEN', 'Area Between Two Polar Curves', 'Unit 9', '{}'),
('SK_SOLVE_INTERSECTIONS', 'Solving Intersections', 'Unit 9', '{}'),
('SK_POLAR_AREA_BETWEEN_CURVES', 'Area Between Two Polar Curves (General)', 'Unit 9', '{}'),
('SK_TRIG_INTEGRATION', 'Trigonometric Integration', 'Unit 9', '{}'),
('SK_LIMITS_THETA', 'Finding Theta Limits', 'Unit 9', '{}'),
('SK_FIND_INTERSECTION_POLAR', 'Finding Polar Intersections', 'Unit 9', '{}'),
('SK_INTEGRAL_SETUP', 'Integral Setup', 'Unit 9', '{}'),
('SK_PARAM_DYDX', 'Parametric dy/dx Formula', 'Unit 9', '{}'),
('SK_ALGEBRA_SIMPLIFY', 'Algebraic Simplification', 'Unit 9', '{}'),
('SK_PARAM_D2YDX2', 'Parametric Second Derivative', 'Unit 9', '{}'),
('SK_PARAM_ARC_LENGTH', 'Parametric Arc Length', 'Unit 9', '{}'),
('SK_VECTOR_INTEGRAL', 'Vector Integration', 'Unit 9', '{}'),
('SK_INITIAL_CONDITIONS', 'Initial Conditions', 'Unit 9', '{}'),
('SK_MOTION_SPEED', 'Motion Speed', 'Unit 9', '{}'),
('SK_POLAR_DR', 'Polar dr/dtheta', 'Unit 9', '{}'),
('SK_OVERCOUNT_SYMMETRY', 'Symmetry Overcounting', 'Unit 9', '{}'),
('SK_TANGENT_CONDITIONS', 'Tangent Conditions', 'Unit 9', '{}'),
('SK_VECTOR_COMPONENTS', 'Vector Components', 'Unit 9', '{}'),
('SK_INTERSECTIONS', 'Intersections', 'Unit 9', '{}'),
('SK_RELRATES_SETUP', 'Related Rates Setup', 'Unit 9', '{}'),
('SK_IMPLICIT_DIFFERENTIATION', 'Implicit Differentiation', 'Unit 9', '{}'),
('SK_SIMILAR_TRIANGLES', 'Similar Triangles (Applications)', 'Unit 9', '{}')

 ON CONFLICT (id) DO NOTHING;
