-- Insert missing Unit 6 skills
INSERT INTO public.skills (id, name, unit, prerequisites) VALUES
('SK_ACCUM_NET_CHANGE', 'Accumulation as Net Change', 'Unit 6', '{}'),
('SK_AREA_UNDER_CURVE', 'Area Under Curve Interpretation', 'Unit 6', '{}'),
('SK_DEF_INT_INTERP', 'Definite Integral Interpretation', 'Unit 6', '{}'),
('SK_FTC1_DERIV_ACCUM', 'FTC Part 1: Derivative of Accumulation Function', 'Unit 6', '{}'),
('SK_FTC2_EVAL_INTEGRAL', 'FTC Part 2: Evaluating Definite Integrals', 'Unit 6', '{}'),
('SK_LEFT_RIGHT_COMPARE', 'Comparing Left and Right Riemann Sums', 'Unit 6', '{}'),
('SK_LEIBNIZ_RULE', 'Leibniz Rule (Differentiation under Integral Sign)', 'Unit 6', '{}'),
('SK_MONOTONICITY', 'Monotonicity and Riemann Sums', 'Unit 6', '{}'),
('SK_NET_CHANGE_THEOREM', 'Net Change Theorem Application', 'Unit 6', '{}'),
('SK_PARTITION_DELTA_X', 'Partition and Delta x', 'Unit 6', '{}'),
('SK_RIEMANN_SUMS', 'Riemann Sums General Understanding', 'Unit 6', '{}'),
('SK_RIEMANN_SUM_NUMERIC', 'Numerical Riemann Sum Calculation', 'Unit 6', '{}'),
('SK_RIEMANN_TO_INTEGRAL', 'Converting Riemann Sum to Definite Integral', 'Unit 6', '{}'),
('SK_SIGMA_TO_INTEGRAL', 'Converting Sigma Notation to Integral', 'Unit 6', '{}'),
('SK_SIGMA_TO_RIEMANN', 'Converting Sigma Notation to Riemann Sum', 'Unit 6', '{}'),
('SK_SIGNED_AREA_FROM_GRAPH', 'Signed Area from Graph', 'Unit 6', '{}'),
('SK_UNITS', 'Units in Integration', 'Unit 6', '{}'),
('SK_ACCUM_BEHAVIOR', 'Behavior of Accumulation Functions', 'Unit 6', '{}'),
('SK_ACCUM_VALUE', 'Value of Accumulation Functions', 'Unit 6', '{}'),
('SK_ANTIDERIV_PATTERN', 'Antiderivative Patterns', 'Unit 6', '{}'),
('SK_AREA_GEOMETRY', 'Geometric Area Interpretation', 'Unit 6', '{}'),
('SK_CHAIN_RULE_LIMITS', 'Chain Rule with Integration Limits', 'Unit 6', '{}'),
('SK_CONCAVITY_FROM_DERIV', 'Determining Concavity from Derivative', 'Unit 6', '{}'),
('SK_EVEN_ODD', 'Even and Odd Functions', 'Unit 6', '{}'),
('SK_FTC1', 'Fundamental Theorem of Calculus Part 1', 'Unit 6', '{}'),
('SK_FTC_DEFINT_EVAL', 'Evaluating Definite Integrals via FTC', 'Unit 6', '{}'),
('SK_FTC_PART1', 'Fundamental Theorem of Calculus Part 1', 'Unit 6', '{}'),
('SK_INDEF_EXP_RULE', 'Indefinite Integral: Exponential Rule', 'Unit 6', '{}'),
('SK_INDEF_LOG_RULE', 'Indefinite Integral: Logarithmic Rule', 'Unit 6', '{}'),
('SK_INDEF_POWER_RULE', 'Indefinite Integral: Power Rule', 'Unit 6', '{}'),
('SK_INDEF_TRIG_RULE', 'Indefinite Integral: Trigonometric Rule', 'Unit 6', '{}'),
('SK_INT_ADDITIVITY', 'Additivity of Integrals', 'Unit 6', '{}'),
('SK_INT_BOUNDS', 'Bounds of Integrals', 'Unit 6', '{}'),
('SK_INT_LINEARITY', 'Linearity of Integrals', 'Unit 6', '{}'),
('SK_INT_PROPERTIES', 'Properties of Integrals', 'Unit 6', '{}'),
('SK_IVP_FROM_DERIV', 'Initial Value Problem from Derivative', 'Unit 6', '{}'),
('SK_SIGNED_AREA', 'Signed Area', 'Unit 6', '{}'),
('SK_ALGEBRA_SIMPLIFICATION', 'Algebraic Simplification', 'Unit 6', '{}'),
('SK_ALGEBRA_SIMPLIFY', 'Algebraic Simplify', 'Unit 6', '{}'),
('SK_CHAIN_RULE_RECOGNITION', 'Chain Rule Recognition', 'Unit 6', '{}'),
('SK_COMPLETE_THE_SQUARE', 'Completing the Square', 'Unit 6', '{}'),
('SK_DEFINITE_INTEGRAL_EVALUATION', 'Definite Integral Evaluation', 'Unit 6', '{}'),
('SK_DEFINITE_INTEGRAL_LIMITS', 'Definite Integral Limits', 'Unit 6', '{}'),
('SK_INTEGRATE_RATIONAL_FUNCTIONS', 'Integrating Rational Functions', 'Unit 6', '{}'),
('SK_INT_BY_PARTS', 'Integration by Parts', 'Unit 6', '{}'),
('SK_INVERSE_TRIG_ANTIDERIVATIVES', 'Inverse Trigonometric Antiderivatives', 'Unit 6', '{}'),
('SK_LONG_DIVISION_POLYNOMIALS', 'Polynomial Long Division', 'Unit 6', '{}'),
('SK_PARTIAL_FRACTIONS_LINEAR', 'Partial Fractions (Linear Factors)', 'Unit 6', '{}'),
('SK_TRIG_IDENTITY_REWRITE', 'Trigonometric Identity Rewrite', 'Unit 6', '{}'),
('SK_U_SUBSTITUTION', 'Integration by Substitution', 'Unit 6', '{}'),
('SK_COMPLETE_SQUARE', 'Completing the Square', 'Unit 6', '{}'),
('SK_FPRIME_OVER_F', 'Integration of f-prime/f', 'Unit 6', '{}'),
('SK_IMPROPER_CONVERGENCE', 'Improper Integral Convergence', 'Unit 6', '{}'),
('SK_IMPROPER_CONVERGENCE_TESTS', 'Improper Integral Convergence Tests', 'Unit 6', '{}'),
('SK_IMPROPER_EVAL', 'Evaluating Improper Integrals', 'Unit 6', '{}'),
('SK_IMPROPER_FINITE_ENDPOINT', 'Improper Integral Finite Endpoint', 'Unit 6', '{}'),
('SK_INTEGRATION_BY_PARTS', 'Integration by Parts', 'Unit 6', '{}'),
('SK_INV_TRIG_ANTIDERIV', 'Inverse Trigonometric Antiderivatives', 'Unit 6', '{}'),
('SK_LONG_DIVISION_RATIONAL', 'Rational Function Long Division', 'Unit 6', '{}'),
('SK_POWER_ANTIDERIV', 'Power Rule Antiderivative', 'Unit 6', '{}'),
('SK_SUBSTITUTION_SPECIAL', 'Special Substitution Techniques', 'Unit 6', '{}'),
('SK_TECHNIQUE_SELECT', 'Selecting Integration Techniques', 'Unit 6', '{}'),
('SK_ACCUM_RATE', 'Accumulation Rate Context', 'Unit 6', '{}'),
('SK_ALG_SIMPLIFY', 'Algebraic Simplification', 'Unit 6', '{}'),
('SK_ALG_TECHNIQUE', 'Algebraic Integration Techniques', 'Unit 6', '{}'),
('SK_ANTIDERIV_RULES', 'Antiderivative Rules', 'Unit 6', '{}'),
('SK_AREA_BETWEEN', 'Area Between Curves', 'Unit 6', '{}'),
('SK_AVG_VALUE', 'Average Value of Function', 'Unit 6', '{}'),
('SK_CHAIN_INTEGRALS', 'Chain Rule in Integrals', 'Unit 6', '{}'),
('SK_DEF_INT_CONCEPT', 'Definite Integral Concept', 'Unit 6', '{}'),
('SK_FTC_ACCUM_FUNC', 'FTC Accumulation Function', 'Unit 6', '{}'),
('SK_FTC_EVAL', 'FTC Evaluation', 'Unit 6', '{}'),
('SK_IMPROPER_INT', 'Improper Integrals', 'Unit 6', '{}'),
('SK_PARTIAL_FRAC', 'Partial Fractions', 'Unit 6', '{}'),
('SK_PLUS_C', 'Indefinite Integral Constant', 'Unit 6', '{}'),
('SK_SIGMA_NOTATION', 'Sigma Notation', 'Unit 6', '{}'),
('SK_TECH_SELECT', 'Integration Technique Selection', 'Unit 6', '{}'),
('SK_TRIG_INT', 'Trigonometric Integrals', 'Unit 6', '{}'),
('SK_UNITS_CONTEXT', 'Units in Integration Context', 'Unit 6', '{}')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    unit = EXCLUDED.unit;
